### ISSUE TITLE
Face unlock feature missing

### ISSUE THREAD

**Issue by rhudsonsamuel** [phhusson/treble_experimentations#1022]
When i tried to check face unlock feature in settings...
I got few options...when i select those options i got force stop window...

**https://del.dog/ollidimosi.txt**
time: 1576740960638
msg: java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
stacktrace: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.android.settings/com.android.settings.SubSettings}: java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3270)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
	at com.android.settings.biometrics.face.FaceSettings.onCreate(FaceSettings.java:138)
	at androidx.fragment.app.Fragment.performCreate(Fragment.java:2596)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:831)
	at androidx.fragment.app.FragmentTransition.addToFirstInLastOut(FragmentTransition.java:1197)
	at androidx.fragment.app.FragmentTransition.calculateFragments(FragmentTransition.java:1080)
	at androidx.fragment.app.FragmentTransition.startTransitions(FragmentTransition.java:119)
	at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1853)
	at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1811)
	at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1717)
	at androidx.fragment.app.FragmentManagerImpl.executePendingTransactions(FragmentManagerImpl.java:183)
	at com.android.settings.SettingsActivity.switchToFragment(SettingsActivity.java:567)
	at com.android.settings.SettingsActivity.launchSettingFragment(SettingsActivity.java:360)
	at com.android.settings.SettingsActivity.onCreate(SettingsActivity.java:268)
	at android.app.Activity.performCreate(Activity.java:7824)
	at android.app.Activity.performCreate(Activity.java:7813)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
	... 11 more

**Comment by eg-abdurrahman** [comment]
I just copy facelock app to system from my stock rom.
And it successfully working.

**Comment by piyush97** [comment]
You can copy app from your stock rom

**Comment by rhudsonsamuel** [comment]
From stock means my stock OS !!! (Asus Zenfone Max M1)...

**Comment by eg-abdurrahman** [comment]
Yes..
But I think it's won't work with Android 10 ..
It's compatibility with Android Oreo and pie Gsi

**Comment by rhudsonsamuel** [comment]
oh.....but in pie i saw face unlock feature already available

**Comment by eg-abdurrahman** [comment]
For me...face unlock feature not working all of the gsi.

**Comment by rhudsonsamuel** [comment]
oh okay...thanks for your reply

**Comment by lorenzo12floxy** [comment]
If it is the google faceunlock then flash a gapps with faceunlock included worked for me on most phones and most androids at least

**Comment by insighty** [comment]
> You can copy app from your stock rom

what's it called? Can't find *face* in my product or vendor or system folders
