### ISSUE TITLE
[Realme X2 Pro] System becomes unusable after a couple of hours usage

### ISSUE THREAD

**Issue by mKenfenheuer** [phhusson/treble_experimentations#1123]
Steps to reproduce:

- Flash v210
- Use the device for a couple of hours and wait for the system ui to crash
- Once the system ui is back, unlock and use for a couple of seconds
- The touchscreen will stop working
- Locking and unlocking it will not work anymore (screen stays the same, not the lock screen though)
- If the lock screen is displayed, unlocking will result in a blank background.
- Also no apps can be used anymore (e.g. settings app through the notification shortcut)

Device Boot/Vendor/Dtbo/etc. (from A09 System Update)
I'll try with A08 too and report back

**Comment by phhusson** [comment]
Sounds like dead/crashing SystemUI, next time take logcat

**Comment by mKenfenheuer** [comment]
Yes, i tried. Adb dies too so i was not able to grab logcat.  Any other idea how to get it? With A08
i did not yet had any issues so far.

________________________________

**Comment by mKenfenheuer** [comment]
Same issue with A08 today. I'll try to grab logcat somehow.

**Comment by mKenfenheuer** [comment]
Here we go:

[logcat.txt](https://github.com/phhusson/treble_experimentations/files/4239445/logcat.txt)

**Comment by phhusson** [comment]
Okay so the issue is pretty simple. I believe that if you disable auto-rotation you won't hit it anymore.

The issue is that rotation sensor reports rotation 4, which is illegal
```
02-22 15:14:02.527  1339  3118 E ActivityManager: java.lang.ArrayIndexOutOfBoundsException: length=4; index=4
02-22 15:14:02.527  1339  3118 E ActivityManager:   at com.android.server.wm.DisplayPolicy.getNavigationBarHeight(DisplayPolicy.java:2845)
02-22 15:14:02.527  1339  3118 E ActivityManager:   at com.android.server.wm.DisplayPolicy.getNonDecorDisplayHeight(DisplayPolicy.java:2880)
```

I know Lineage hit the same issue, I'll need to check how they fixed it.

**Comment by phhusson** [comment]
Found it:

https://review.lineageos.org/c/LineageOS/android_frameworks_base/+/238017

cherry-picked.
