### ISSUE TITLE
Android 10 GSI, Chrome 80 and later and inline web video don't play nice.

### ISSUE THREAD

**Issue by fourofspades** [phhusson/treble_experimentations#1213]
Webpages with video (eg. BBC News, Twitter) videos in webpages don't play in Chrome 80 on this GSI, downgrading to 79 works, WebKit app in 80 works, Chrome 80 on the same websites on other devices also work.

Very reproducible here.

(Gapps comes with Chrome 75 or so, so works, but if you grab a Google play store update of Chrome it breaks.  Ditto for Dev, canary and beta channel builds)

**Comment by phhusson** [comment]
On my Realme X2 Pro running my v214, with Chrome 80.0.3987.149, I opened bbc.com/news, clicked on first piece of news, then the triangle to play video, and it played the video

**Comment by Frimium** [comment]
Same problem. In Chrome 80, some videos work, some do not. For example, it works on YouTube, but does not work on Twitter, Instagram. In the Instagram application and some others, the video works, but it has very poor quality. Maybe this is a non-snapdragon issue.
Phone: Umidigi F1
mediatek

**Comment by fourofspades** [comment]
It could be hardware specific, I'm seeing this on KIRIN960 Hi3660  SoC

**Comment by fourofspades** [comment]
@Frimium   If you uninstall updates (back to Chrome 75, then grab  Chrome 79 bundle from APKMirror, it should work again.

**Comment by Frimium** [comment]
@fourofspades I don’t think that switching to the previous version is a way out of the situation, because in this case we will put an end to all subsequent updates of Chrome and, in principle, to the browser as a whole. I temporarily use Firefox (everything works in it), but I also need working Chrome. Just as I wrote above, I still have some problems with video in some applications.

**Comment by fourofspades** [comment]
Indeed, it's a temporary workaround at best,.

**Comment by phhusson** [comment]
@Frimium could you please test with the system.img from Google in https://ci.android.com/builds/submitted/6337924/aosp_arm64-userdebug/latest/aosp_arm64-img-6337924.zip ?

**Comment by Frimium** [comment]
@phhusson. On the second link, I previously installed GSI 10 from Google, but it seems my display did not work. In the coming days, I can try to install the image from the first link and the second.

**Comment by Frimium** [comment]
@phhusson Should I take only system.img from aosp gsi or something else? I have vendor and so on in the stock firmware. 
![2020-04-01](https://user-images.githubusercontent.com/35657457/78070453-d991c680-73ac-11ea-85a8-d01ed7d4cc08.png)

**Comment by phhusson** [comment]
only system.img

vendor/boot in AOSP's tree are for emulator

**Comment by Frimium** [comment]
@phhusson The phone does not start with images from Google :(

**Comment by michaelstubbs** [comment]
I would like to add that I am also experiencing this issue on Cubot X19 hardware.

* My video acceleration is at least partially broken, which definitely seems to be a common factor.

* As a temporary workaround, Firefox can be used.

**Comment by Frimium** [comment]
@phhusson Google GSI has the same problems with the video, plus those that you have already fixed. This error is a continuation of the problem with mediatek codecs (possibly with others too). If you disable the mediatek codecs, then the web video works everywhere and in good quality, and the video on the device does not work (I also tried to disable different codecs and options in the codecs separately, but something changed only when h.264 AVC was turned off). This could be a solution for me, because I only watch web video, but sometimes when watching a video the android crashes . (Another minor issue is flickering, but it is fixed by disabling HW overlays)
After you fixed some problems with the video, mediatek video worked, but not everywhere, it seems to me that this is due to the fact that some of the codecs still do not work correctly or not at all.

**Comment by fourofspades** [comment]
If I understand the comment correctly, I can get video working for me by disabling mediatek codecs (I am not using a mediatek based device).  How did you do this? Thanks.

**Comment by Frimium** [comment]
@fourofspades Mediatek codecs must be on a phone with a mediatek processor. You should probably have kirin codecs. I do not know what codecs Kirin uses. I'm not sure if this will work for you. 
---------
I deleted or commented out the lines of media_codecs_mediatek_video.xml in vendor/etc/media_codecs.xml
or
h264 decoding codec in vendor/ etc/media_codecs_mediatek_video.xml
To do this, you need ROOT

**Comment by Frimium** [comment]
@phhusson . At Mediatek, I am sure that this is due to the h264 decoder. On the android site it is indicated that this codec should play 3gp, mp4 and mpeg-ts. I think that h264 mediatek is having problems with TS and maybe that’s why the manufacturer even added mpeg2 decoder to vendor.img, but it seems to me that most applications do not see this decoder. Tell me if I am wrong.

**Comment by fourofspades** [comment]
Captured some logs of the issue.  Anyone help working out what I need to do to fix this? Sticking on Chrome 79 is no longer an option with the critical Chrome issue now in the wild...

04-20 07:15:54.056 I/OMXMaster(840): makeComponentInstance(OMX.hisi.video.decoder.avc) in omx@1.0-service process
04-20 07:15:54.061 D/HIOMX_CORE(840): OMX_GetHandle :: component name:OMX.hisi.video.decoder.avc
04-20 07:15:54.061 E/HIOMX_CORE(840): opening file: No such file or directory 
04-20 07:15:54.061 D/HIOMX_CORE(840): OMX_GetHandle :: prepare to load  libOMX.hisi.video.decoder.so
04-20 07:15:54.073 D/HIOMX_CORE(840): OMX_GetHandle :: load  libOMX.hisi.video.decoder.so ok
04-20 07:15:54.075 D/HISI_OMXVDEC(840): Init OMX component OMX.hisi.video.decoder, State Loaded
04-20 07:15:54.091 I/MediaCodec(28422): MediaCodec will operate in async mode
04-20 07:15:54.093 D/SurfaceUtils(28422): connecting to surface 0xdad87808, reason connectToSurface
04-20 07:15:54.093 I/MediaCodec(28422): [OMX.hisi.video.decoder.avc] setting surface generation to 29104165
04-20 07:15:54.093 D/SurfaceUtils(28422): disconnecting from surface 0xdad87808, reason connectToSurface(reconnect)
04-20 07:15:54.093 D/SurfaceUtils(28422): connecting to surface 0xdad87808, reason connectToSurface(reconnect)
04-20 07:15:54.096 D/HISI_OMXVDEC(840): set native buffer enable, stride align step 1 -> 128!
04-20 07:15:54.096 E/HISI_OMXVDEC(840): allocate native buffer: Bad port index 1
04-20 07:15:54.096 E/OMXNodeInstance(840): setParameter(0xec3b1f60:hisi.decoder.avc, OMX.google.android.index.allocateNativeHandle(0x7f000008): Output:1 en=0) ERROR: BadPortIndex(0x8000101b)
04-20 07:15:54.096 E/HISI_OMXVDEC(840): OMX.google.android.index.storeANWBufferInMetadata not implemented!
04-20 07:15:54.096 E/HISI_OMXVDEC(840): OMX.google.android.index.storeMetaDataInBuffers not implemented!
04-20 07:15:54.096 E/OMXNodeInstance(840): getExtensionIndex(0xec3b1f60:hisi.decoder.avc, OMX.google.android.index.storeMetaDataInBuffers) ERROR: NotImplemented(0x80001006)
04-20 07:15:54.096 E/ACodec  (28422): [OMX.hisi.video.decoder.avc] setPortMode on output to DynamicANWBuffer failed w/ err -2147483648
04-20 07:15:54.096 D/HISI_OMXVDEC(840): set adaptive playback enable 1!
04-20 07:15:54.097 E/HISI_OMXVDEC(840): allocate native buffer: Bad port index 1
04-20 07:15:54.097 E/OMXNodeInstance(840): setParameter(0xec3b1f60:hisi.decoder.avc, OMX.google.android.index.allocateNativeHandle(0x7f000008): Output:1 en=0) ERROR: BadPortIndex(0x8000101b)
04-20 07:15:54.097 D/HISI_OMXVDEC(840): set native buffer enable, stride align step 1 -> 128!
04-20 07:15:54.097 E/HISI_OMXVDEC(840): OMX.google.android.index.storeANWBufferInMetadata not implemented!
04-20 07:15:54.097 E/HISI_OMXVDEC(840): OMX.google.android.index.storeMetaDataInBuffers not implemented!
04-20 07:15:54.097 E/OMXNodeInstance(840): getExtensionIndex(0xec3b1f60:hisi.decoder.avc, OMX.google.android.index.storeMetaDataInBuffers) ERROR: NotImplemented(0x80001006)
04-20 07:15:54.097 E/HISI_OMXVDEC(840): Invalid stride 128 != cal_stride 384 of width 360
04-20 07:15:54.097 E/HISI_OMXVDEC(840): Invalid stride convert to 384
04-20 07:15:54.097 D/HISI_OMXVDEC(840): prepare to update_picture_info.
04-20 07:15:54.097 D/HISI_OMXVDEC(840): update_picture_info_in_detail: dec_w 360, dec_h 184, disp_w 360, disp_h 184, stride 384, buffer_size 110592, min_count 1, max_count 4
04-20 07:15:54.097 D/HISI_OMXVDEC(840): update_in_buffer_info set in buffer size = 2097152
04-20 07:15:54.097 E/HISI_OMXVDEC(840): >>>>>>>portDefn->nPortIndex = 0 xFramerate = 0
04-20 07:15:54.098 E/HISI_OMXVDEC(840): xFramerate > 60000, not reasonalbe , mFrameRate = 0
04-20 07:15:54.098 E/HISI_OMXVDEC(840): OMX.google.android.index.storeMetaDataInBuffers not implemented!
04-20 07:15:54.098 E/HISI_OMXVDEC(840): OMX.google.android.index.storeANWBufferInMetadata not implemented!
04-20 07:15:54.098 E/HISI_OMXVDEC(840): OMX.google.android.index.configureVideoTunnelMode not implemented!
04-20 07:15:54.098 E/HISI_OMXVDEC(840): OMX.google.android.index.useAndroidNativeBuffer not implemented!
04-20 07:15:54.098 I/HISI_OMXVDEC(840): set config index 0x7f00000b OMX_GoogleIndexDescribeColorAspects
04-20 07:15:54.098 I/HISI_OMXVDEC(840): Range 2 Primaries 4 MatrixCoeffs 3 Tansfer 3
04-20 07:15:54.098 E/HISI_OMXVDEC(840): OMX.google.android.index.describeHDRStaticInfo not implemented!
04-20 07:15:54.099 D/HISI_OMXVDEC(840): OMX_IndexConfigCommonOutputCrop: nLeft 0, nTop 0, nWidth 360, nHeight 184
04-20 07:15:54.099 I/HISI_OMXVDEC(840): set config index 0x7f00000b OMX_GoogleIndexDescribeColorAspects
04-20 07:15:54.099 I/HISI_OMXVDEC(840): Range 2 Primaries 4 MatrixCoeffs 3 Tansfer 3
04-20 07:15:54.099 I/HISI_OMXVDEC(840): get config OMX_GoogleIndexDescribeColorAspects
04-20 07:15:54.099 I/HISI_OMXVDEC(840): Range 2 Primaries 4 MatrixCoeffs 3 Tansfer 3
04-20 07:15:54.099 I/HISI_OMXVDEC(840): get config OMX_GoogleIndexDescribeColorAspects
04-20 07:15:54.099 I/HISI_OMXVDEC(840): Range 2 Primaries 4 MatrixCoeffs 3 Tansfer 3
04-20 07:15:54.114 D/HISI_OMXVDEC(840): [OmxState] Loaded --> Idle_Pending
04-20 07:15:54.123 I/OAM     (1164): [check_file_size:511]/data/vendor/log/hi110x/bfg_log/bfg_log_1 log file beyond size=10240Byte, creat new file
04-20 07:15:54.123 I/OAM     (1164): [rename_old_file:216]rename_old_file
04-20 07:15:54.123 I/OAM     (1164): 
04-20 07:15:54.141 E/HISI_OMXVDEC(840): OMX.google.android.index.AndroidNativeBufferConsumerUsage not implemented!
04-20 07:15:54.141 D/SurfaceUtils(28422): disconnecting from surface 0xdad87808, reason setNativeWindowSizeFormatAndUsage
04-20 07:15:54.141 D/SurfaceUtils(28422): connecting to surface 0xdad87808, reason setNativeWindowSizeFormatAndUsage
04-20 07:15:54.141 D/SurfaceUtils(28422): set up nativeWindow 0xdad87808 for 360x184, color 0x30d, rotation 0, usage 0x20002900
04-20 07:15:54.141 D/HISI_OMXVDEC(840): set_parameter: invalid buffer count 8, should not be larger than max count 4
04-20 07:15:54.141 E/OMXNodeInstance(840): setParameter(0xec3b1f60:hisi.decoder.avc, ParamPortDefinition(0x2000001)) ERROR: Undefined(0x80001001)
04-20 07:15:54.142 W/ACodec  (28422): [OMX.hisi.video.decoder.avc] setting nBufferCountActual to 8 failed: -2147483648
04-20 07:15:54.142 D/HISI_OMXVDEC(840): set_parameter: invalid buffer count 7, should not be larger than max count 4
04-20 07:15:54.142 E/OMXNodeInstance(840): setParameter(0xec3b1f60:hisi.decoder.avc, ParamPortDefinition(0x2000001)) ERROR: Undefined(0x80001001)
04-20 07:15:54.142 W/ACodec  (28422): [OMX.hisi.video.decoder.avc] setting nBufferCountActual to 7 failed: -2147483648
04-20 07:15:54.143 D/HISI_OMXVDEC(840): set_parameter: invalid buffer count 6, should not be larger than max count 4
04-20 07:15:54.143 E/OMXNodeInstance(840): setParameter(0xec3b1f60:hisi.decoder.avc, ParamPortDefinition(0x2000001)) ERROR: Undefined(0x80001001)
04-20 07:15:54.143 W/ACodec  (28422): [OMX.hisi.video.decoder.avc] setting nBufferCountActual to 6 failed: -2147483648
04-20 07:15:54.143 D/HISI_OMXVDEC(840): set_parameter: invalid buffer count 5, should not be larger than max count 4
04-20 07:15:54.143 E/OMXNodeInstance(840): setParameter(0xec3b1f60:hisi.decoder.avc, ParamPortDefinition(0x2000001)) ERROR: Undefined(0x80001001)
04-20 07:15:54.143 W/ACodec  (28422): [OMX.hisi.video.decoder.avc] setting nBufferCountActual to 5 failed: -2147483648
04-20 07:15:54.143 E/ACodec  (28422): Failed to allocate buffers after transitioning to IDLE state (error 0x80000000)
04-20 07:15:54.143 E/ACodec  (28422): signalError(omxError 0x80001001, internalError -2147483648)
04-20 07:15:54.143 E/MediaCodec(28422): Codec reported err 0x80001001, actionCode 0, while in state 5
04-20 07:15:54.144 D/HISI_OMXVDEC(840): [OmxState] ERROR: Loaded --> Loaded
04-20 07:15:54.144 E/HISI_OMXVDEC(840): send_command_proxy failed
04-20 07:15:54.147 E/ACodec  (28422): [OMX.hisi.video.decoder.avc] ERROR(0x80001012)
04-20 07:15:54.147 E/ACodec  (28422): signalError(omxError 0x80001012, internalError -2147483648)
04-20 07:15:54.147 E/ACodec  (28422): [OMX.hisi.video.decoder.avc] ERROR(0x80001012)
04-20 07:15:54.147 E/ACodec  (28422): signalError(omxError 0x80001012, internalError -2147483648)
04-20 07:15:54.147 D/SurfaceUtils(28422): disconnecting from surface 0xdad87808, reason disconnectFromSurface
04-20 07:15:54.147 E/MediaCodec(28422): Codec reported err 0x80001012, actionCode 0, while in state 0
04-20 07:15:54.147 E/MediaCodec(28422): Codec reported err 0x80001012, actionCode 0, while in state 0
04-20 07:15:54.155 E/cr_MediaCodecBridge(28422): Cannot start the media codec
04-20 07:15:54.155 E/cr_MediaCodecBridge(28422): android.media.MediaCodec$CodecException: start failed
04-20 07:15:54.155 E/cr_MediaCodecBridge(28422): 	at android.media.MediaCodec.native_start(Native Method)
04-20 07:15:54.155 E/cr_MediaCodecBridge(28422): 	at android.media.MediaCodec.start(MediaCodec.java:2132)
04-20 07:15:54.155 E/cr_MediaCodecBridge(28422): 	at org.chromium.media.MediaCodecBridge.c(PG:8)
04-20 07:15:54.155 E/cr_MediaCodecBridge(28422): 	at org.chromium.media.MediaCodecBridgeBuilder.createVideoDecoder(PG:65)
04-20 07:15:54.156 W/cr_MediaCodecBridge(28422): Releasing: OMX.hisi.video.decoder.avc

**Comment by fourofspades** [comment]
The buffercount max of 4 looks interesting, as the XML has this set to 5..

   <Setting name="max-video-encoder-input-buffers" value="5" />

**Comment by fourofspades** [comment]
The stock OS has this set the same. I pulled a bunch of files from the stock image 

https://mega.nz/folder/vd4ghSjC#EAhiXmYHQ0MGNPm7Uy1E4g

If someone has any ideas of things to try for a hi3660 device, keen to get this fixed.

**Comment by whaletb** [comment]
I'm also facing this online video play issue for all social media app. Something I don't understand dho. After installing the ROM at first, it wasn't working, so  I was playing around the ROM and decided to flash magisk canary for no reason. After a reboot, I could actually play video on social media app but then, my dialer developed and issue. I couldn't call out. Weird. I didn't even think it was related to magisk, so I kept on trying all I could but still the dialer issue won't go away. Someone then tipped me to remove magisk completely.. 

I removed magisk and everything was back to normal, except that video won't play again on social media apps.

I went ahead and flash magisk canary again and this time, it bootlooped.

**Comment by fourofspades** [comment]
Disabling hardware acceleration works around the problem at the expense of poor battery life and frame rate.

chrome://flags/#disable-accelerated-video-decode.  Set to disabled


Keen to help get this fixed.  How can I help?

**Comment by Frimium** [comment]
- Now everything works, but twitches a little, sometimes the android crashes (very rarely). In Instagram, some videos are still low resolution. But all this is not critical. Thank you, @phhusson .
--------------------------
- Umidigi F1
- AOSP 10.0 v221
- Chrome v84

**Comment by fourofspades** [comment]
The original bug is still an issue and has NOT been fixed (the bug was hijacked by an unrelated issue).

Android 10 v222

render_id: 37
player_id: 0
origin_url: https://mobile.twitter.com/
kFrameUrl: https://mobile.twitter.com/brewdogjames/status/1316011887432134660?s=21
kFrameTitle: James Watt on Twitter: "A number of pups featured on our StreetDog, our @rickygervais collaboration, have found new homes! Thanks to everyone who purchased #streetdog along with @dotslondon &amp; @AllDogsMatter for their support on this great partnership. Keep sharing your snaps. https://t.co/tI6ZeOKjMj" / Twitter
url: https://video.twimg.com/tweet_video/EkNpdPAUcAEQ_RX.mp4
kTotalBytes: 660843
kIsStreaming: false
kIsSingleOrigin: true
kIsRangeHeaderSupported: true
pipeline_state: kStopped
info: Failed to initialize VpxVideoDecoder
kAudioTracks: 
kVideoTracks: [object Object]
kMaxDuration: 10
kStartTime: 0
kBitrate: 528674
event: kWebMediaPlayerDestroyed
kIsVideoDecryptingDemuxerStream: false
kVideoDecoderName: MojoVideoDecoder
kIsPlatformVideoDecoder: true
warning: video fallback to new decoder after initial decode error.
error: video decoder reinitialization failed
pipeline_error: PIPELINE_ERROR_DECODE
duration: 10

**Comment by fourofspades** [comment]
@darkestDark any chance of advising how I can help get this fixed?

**Comment by darkestDark** [comment]
Sure its GSI related?

Looks like your gpu cant handle the vp8/vp9 codec.
https://chromium.googlesource.com/chromium/src/+/master/media/filters/vpx_video_decoder.cc#66

What about other (older!) videos?

**Comment by fourofspades** [comment]
What's weird is there is no problem running Huawei OS, the same videos play fine.  So it seems it's the hardware is capable, but perhaps not configured? 

Using this GSI, most web content doesn't play.

**Comment by darkestDark** [comment]
https://www.cpu-monkey.com/en/igpu-arm_mali_g71_mp8-177

This is your gpu... no vp9 codec support.

So "disable-accelerated-video-decode" seems as only way. i think huawei redirect the decoding on emui automatic to software.

**Comment by fourofspades** [comment]
Ok, thanks that's really good information (but bad news I guess).  The problem with disabling hardware acceleration is it's app-wide, and then other sites break.  For example when using software decoding, BBC news no longer functions.

https://www.bbc.com/news/av/world-asia-54529960

Can't find a codec to play the video.

Is it possible to work out what's missing and install codecs on rooted devices?

**Comment by darkestDark** [comment]
You are not the only one:
https://club.hihonor.com/in/topic/162596/detail.htm

But i see no way for this...

**Comment by fourofspades** [comment]
Disabling hardware decoding makes other things break.  Other sites that
work, suddenly stop working  (for example, videos on BBC news).  The
behaviour of video is VERY different to the stock OS.   I have done a codec
comparison between GSI and stock, and the look very different (what are the
c2 codecs that duplicate functionality?)

**Comment by fourofspades** [comment]
Forgot link to compare PDF:   https://drive.google.com/file/d/1WEAHy0PgtZ_OHSbhV4U8ylOYch-7swsd/view?usp=sharing

**Comment by darkestDark** [comment]
A logcat while trying to play would help...

**Comment by fourofspades** [comment]
Logcat:   https://pastebin.com/c76ZUs46

**Comment by darkestDark** [comment]
10-14 10:56:30.184   847  3353 D HIOMX_CORE: OMX_GetHandle :: component name:OMX.hisi.video.decoder.avc
10-14 10:56:30.184   847  3353 E HIOMX_CORE: opening file: No such file or directory


Look here (without gurantee, i dont have a huawei device)...:
https://git.aicp-rom.com/device_huawei_kirin970-common.git/tree/releasetools/releasetools.kirin970.sh?id=97168bfedd5bd21896a5829b5dfa4c8e18797672#n119

**Comment by fourofspades** [comment]
This bit?

# Copy over vendor media_codecs.xml and disable unwanted HW codecs
    cp /vendor/etc/media_codecs.xml /system/etc/media_codecs.xml
    sed -i "s/<MediaCodec name=\"OMX.hisi.video.decoder.avc\" type=\"video\/avc\" >/<MediaCodec name=\"OMX.hisi.video.decoder.avc\" type=\"video\/no-avc\" >/g" /system/etc/media_codecs.xml

Is this part of a build step, or can it be done on a flashed system from a root terminal?

**Comment by darkestDark** [comment]
if you mount system rw before you can run it from root terminal...

**Comment by fourofspades** [comment]
Didn't work sadly.  I confirmed it made the change ok (change the mime type from avc to no-avc).    I then started major hacking of that file, I removed big chunks of codec support, and it still tried to load the codec, even if it's not a registered codec.  The effect was always the same, the logcat error always the same.

It's as if editing that file makes no difference whatsoever...

**Comment by darkestDark** [comment]
hum... i dont know if this aicp patch works in aosp... only phhusson could tell you if system read the file system inline and skip the vendor file or uses the vendor file...

to be clear... have you tried writing the changes to vendor?

**Comment by fourofspades** [comment]
I thought vendor was read-only. But I can try...  It's not something I have tried yet.

**Comment by AlleSchonWeg** [comment]
Hi. Somebody found a solution. I have a Honor 9 and can't play videos. 

Cannot start the media codec
java.lang.IllegalArgumentException: start failed
	at android.media.MediaCodec.native_start(Native Method)
	at android.media.MediaCodec.start(MediaCodec.java:2284)
	at org.chromium.media.MediaCodecBridge.e(chromium-TrichromeChromeGoogle6432.aab-stable-616716433:48)
> 	at org.chromium.media.MediaCodecBridgeBuilder.createVideoDecoder(chromium-TrichromeChromeGoogle6432.aab-stable-616716433:100)
