### ISSUE TITLE
[Xiaomi MIX 2S] Wifi hotspot not working due to selinux

### ISSUE THREAD

**Issue by notsyncing** [phhusson/treble_experimentations#131]
Hello, recently I found the wifi hotspot stopped working on my mix2s, and after I copied two missing libraries (already in PR#1 in `phhusson/vendor_vndk`), I found this line in logcat:

```
07-31 21:40:46.046   566   566 E SELinux : avc:  denied  { add } for interface=android.hardware.tetheroffload.control::IOffloadControl pid=15220 scontext=u:r:ipacm:s0 tcontext=u:object_r:hal_tetheroffload_hwservice:s0 tclass=hwservice_manager permissive=0
```

And wifi hotspot is connectable but not able to open any website. If I turn off selinux with `setenforce 0` and restart `ipacm` with `stop ipacm && start ipacm`, I'm able to access internet.

I guess this is due to some missing selinux policies, but I know nothing about selinux policies. Would you mind adding the policy, or tell me how to add them? Thanks very much!

**Comment by phhusson** [comment]
Hum that's weird, tethering should be working without offloading... that's what offloading means /o\
Anyway, try that:
https://gist.github.com/phhusson/7a2c83ed06c8a229d27909eff1d54ea3

**Comment by notsyncing** [comment]
I encountered a crash when enabling wifi hotspot if I disable the hardware offloading in developer settings... tomorrow I'll be able to try this, now leave my machine compiling and go to bed :)

**Comment by notsyncing** [comment]
This policy worked. I can access the internet with or without hardware offloading. Thanks very much!

But if the two .so libraries (https://github.com/phhusson/vendor_vndk/pull/1) are missing, the system will crash when hardware offloading is enabled in developer settings. Logcat shows:

```
08-02 19:09:08.053  1391  1426 W zygote64: Waited one second for android.hardware.tetheroffload.config@1.0::IOffloadConfig/default. Waiting another...
08-02 19:09:08.627   971  1113 I ThermalEngine: vs_get_temperature: read[0] xo_therm 40232 mC, weight[0] 2
08-02 19:09:08.628   971  1113 I ThermalEngine: vs_get_temperature: read[1] quiet_therm 37604 mC, weight[1] 1
08-02 19:09:09.053  1391  1426 W zygote64: Waited one second for android.hardware.tetheroffload.config@1.0::IOffloadConfig/default. Waiting another...
08-02 19:09:09.356  1391  1974 W Watchdog: *** WATCHDOG KILLING SYSTEM PROCESS: Blocked in handler on i/o thread (android.io)
08-02 19:09:09.356  1391  1974 W Watchdog: i/o thread stack trace:
08-02 19:09:09.356  1391  1974 W Watchdog:     at com.android.server.connectivity.tethering.OffloadHardwareInterface.configOffload(Native Method)
08-02 19:09:09.356  1391  1974 W Watchdog:     at com.android.server.connectivity.tethering.OffloadHardwareInterface.initOffloadConfig(OffloadHardwareInterface.java:99)
08-02 19:09:09.356  1391  1974 W Watchdog:     at com.android.server.connectivity.tethering.OffloadController.start(OffloadController.java:140)
08-02 19:09:09.356  1391  1974 W Watchdog:     at com.android.server.connectivity.Tethering$TetherMasterSM$OffloadWrapper.start(Tethering.java:1715)
08-02 19:09:09.356  1391  1974 W Watchdog:     at com.android.server.connectivity.Tethering$TetherMasterSM$TetherModeAliveState.enter(Tethering.java:1512)
08-02 19:09:09.356  1391  1974 W Watchdog:     at com.android.internal.util.StateMachine$SmHandler.invokeEnterMethods(StateMachine.java:1037)
08-02 19:09:09.356  1391  1974 W Watchdog:     at com.android.internal.util.StateMachine$SmHandler.performTransitions(StateMachine.java:879)
08-02 19:09:09.356  1391  1974 W Watchdog:     at com.android.internal.util.StateMachine$SmHandler.handleMessage(StateMachine.java:819)
08-02 19:09:09.356  1391  1974 W Watchdog:     at android.os.Handler.dispatchMessage(Handler.java:106)
08-02 19:09:09.356  1391  1974 W Watchdog:     at android.os.Looper.loop(Looper.java:164)
08-02 19:09:09.356  1391  1974 W Watchdog:     at android.os.HandlerThread.run(HandlerThread.java:65)
08-02 19:09:09.356  1391  1974 W Watchdog:     at com.android.server.ServiceThread.run(ServiceThread.java:46)
08-02 19:09:09.356  1391  1974 W Watchdog: *** GOODBYE!
08-02 19:09:09.356  1391  1974 I Process : Sending signal. PID: 1391 SIG: 9
```

Then all system services died and a soft reboot occured.

**Comment by notsyncing** [comment]
Verified tethering working on v23. Thanks very much!
