### ISSUE TITLE
**QUALCOMM** vndk **26**

### ISSUE THREAD

**Issue by dmitriyvt** [phhusson/treble_experimentations#1508]
Device: **Honor-7C** (AUM-L41)
 http://4pda.ru/devdb/honor_7c 
 Structure / Architecture: **Arm64-Aonly**
 Processor: **Snapdragon 430**
 Base: **Android 8 Oreo**
 Software version: **AUM-L41 8.0.0.155 (C461)**

Firmware: **AOSP 11.0 v300.b**
 Does not work:
 Camera.
 Ringtone, notification and alarm sounds.
 NFC.
 WiFi hotspot.
 Lantern.

**Comment by dmitriyvt** [comment]
**Camera**

<<< log_count = 58 >>>
[10-01 01:38:26.918 1546:2394 I/ActivityTaskManager]
START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 pkg=com.android.camera2 cmp=com.android.camera2/com.android.camera.CameraLauncher bnds=[28,1198][161,1376]} from uid 10110

[10-01 01:38:27.072 1546:1740 I/ActivityManager]
Start proc 4380:com.android.camera2/u0a102 for pre-top-activity {com.android.camera2/com.android.camera.CameraLauncher}

[10-01 01:38:27.344 4380:4380 I/android.camera]
The ClassLoaderContext is a special shared library.

[10-01 01:38:27.352 4380:4380 I/android.camera]
The ClassLoaderContext is a special shared library.

[10-01 01:38:27.587 4380:4380 I/CAM_Profiler]
[ 57,572ms][ui] GUARD: CameraApp onCreate() - [57,572ms] initializeTimeOfFirstRun

[10-01 01:38:27.594 4380:4380 I/CAM_Profiler]
[ 63,110ms][ui] GUARD: CameraApp onCreate() - STOP

[10-01 01:38:28.388 4380:4380 I/CAM_Profiler]
[656,603ms][ui] GUARD: CameraActivity.onCreateTasks - [18,817ms] Glide.setup

[10-01 01:38:28.390 4380:4380 I/CameraManagerGlobal]
Connecting to camera service

[10-01 01:38:28.407 1111:1111 W/ServiceManager]
Permission failure: android.permission.CAMERA_OPEN_CLOSE_LISTENER from uid=10102 pid=4380

[10-01 01:38:28.413 4380:4380 W/CAM_Camera2OneCamMgr]
No back-facing camera found.

[10-01 01:38:28.414 4380:4380 W/CAM_Camera2OneCamMgr]
No external camera found.

[10-01 01:38:28.416 4380:4380 W/CAM_Camera2OneCamMgr]
No front-facing camera found.

[10-01 01:38:28.417 4380:4380 W/CAM_Camera2OneCamMgr]
No external camera found.

[10-01 01:38:28.421 4380:4380 I/CAM_Profiler]
[687,185ms][ui] GUARD: CameraActivity.onCreateTasks - [30,582ms] OneCameraManager.get

[10-01 01:38:28.480 4380:4380 W/android.camera2]
type=1400 audit(0.0:221): avc: denied { read } for name="u:object_r:exported_camera_prop:s0" dev="tmpfs" ino=969 scontext=u:r:untrusted_app_27:s0:c102,c256,c512,c768 tcontext=u:object_r:exported_camera_prop:s0 tclass=file permissive=0 app=com.android.camera2

[10-01 01:38:28.484 4380:4380 E/libc]
Access denied finding property "config.disable_cameraservice"

[10-01 01:38:28.487 1111:1111 W/ServiceManager]
Permission failure: android.permission.SYSTEM_CAMERA from uid=10102 pid=4380

[10-01 01:38:28.489 1111:2256 W/ServiceManager]
Permission failure: android.permission.SYSTEM_CAMERA from uid=10102 pid=4380

[10-01 01:38:28.494 1111:2256 I/chatty]
uid=1047(cameraserver) Binder:1111_3 identical 1 line

[10-01 01:38:28.496 1111:2256 W/ServiceManager]
Permission failure: android.permission.SYSTEM_CAMERA from uid=10102 pid=4380

[10-01 01:38:28.496 4380:4380 W/SoundDecoder_1]
type=1400 audit(0.0:222): avc: granted { open } for path="/dev/ashmem" dev="tmpfs" ino=15755 scontext=u:r:untrusted_app_27:s0:c102,c256,c512,c768 tcontext=u:object_r:ashmem_device:s0 tclass=chr_file app=com.android.camera2

[10-01 01:38:28.502 1111:2256 W/ServiceManager]
Permission failure: android.permission.SYSTEM_CAMERA from uid=10102 pid=4380

[10-01 01:38:28.507 1111:1111 W/ServiceManager]
Permission failure: android.permission.SYSTEM_CAMERA from uid=10102 pid=4380

[10-01 01:38:28.508 1111:1111 W/ServiceManager]
Permission failure: android.permission.SYSTEM_CAMERA from uid=10102 pid=4380

[10-01 01:38:28.520 4380:4380 W/SoundDecoder_1]
type=1400 audit(0.0:223): avc: granted { open } for path="/dev/ashmem" dev="tmpfs" ino=15755 scontext=u:r:untrusted_app_27:s0:c102,c256,c512,c768 tcontext=u:object_r:ashmem_device:s0 tclass=chr_file app=com.android.camera2

[10-01 01:38:28.530 1111:1111 W/ServiceManager]
Permission failure: android.permission.SYSTEM_CAMERA from uid=10102 pid=4380

[10-01 01:38:28.540 1111:1111 W/ServiceManager]
Permission failure: android.permission.SYSTEM_CAMERA from uid=10102 pid=4380

[10-01 01:38:28.551 1111:2256 W/ServiceManager]
Permission failure: android.permission.SYSTEM_CAMERA from uid=10102 pid=4380

[10-01 01:38:28.565 1111:2256 I/chatty]
uid=1047(cameraserver) Binder:1111_3 identical 4 lines

[10-01 01:38:28.573 1111:2256 W/ServiceManager]
Permission failure: android.permission.SYSTEM_CAMERA from uid=10102 pid=4380

[10-01 01:38:28.574 1111:2256 I/CameraService]
CameraService::connect call (PID -1 "com.android.camera2", camera ID 0) for HAL version default and Camera API version 1

[10-01 01:38:28.577 1111:2256 E/CameraService]
CameraService::connect X (PID 4380) rejected (camera 0 is not connected)

[10-01 01:38:28.583 4380:4380 W/CameraBase]
An error occurred while connecting to camera 0: Status(-8, EX_SERVICE_SPECIFIC): '4: validateConnectLocked:1119: No camera device with ID "0" currently available'

[10-01 01:38:28.585 1111:1111 W/ServiceManager]
Permission failure: android.permission.SYSTEM_CAMERA from uid=10102 pid=4380

[10-01 01:38:28.585 1111:1111 I/CameraService]
CameraService::connect call (PID -1 "com.android.camera2", camera ID 1) for HAL version default and Camera API version 1

[10-01 01:38:28.589 1111:1111 E/CameraService]
CameraService::connect X (PID 4380) rejected (camera 1 is not connected)

[10-01 01:38:28.597 4380:4380 W/CameraBase]
An error occurred while connecting to camera 1: Status(-8, EX_SERVICE_SPECIFIC): '4: validateConnectLocked:1119: No camera device with ID "1" currently available'

[10-01 01:38:28.617 4380:4380 I/CAM_Profiler]
[881,664ms][ui] GUARD: CameraActivity.onCreateTasks - [86,309ms] computePictureSizes

[10-01 01:38:28.807 4380:4380 I/CAM_Profiler]
[1075,776ms][ui] GUARD: CameraActivity.onCreateTasks - [178,560ms] setContentView()

[10-01 01:38:28.829 4380:4380 I/CAM_Profiler]
[1098,003ms][ui] GUARD: CameraActivity.onCreateTasks - [22,226ms] Configure Camera UI

[10-01 01:38:28.840 4380:4380 I/TetheringManager]
registerTetheringEventCallback:com.android.camera2

[10-01 01:38:28.868 4380:4411 W/CAM2PORT_AndCamAgntImp]
Releasing camera without any camera opened.

[10-01 01:38:28.914 4380:4380 W/CAM_Camera2OneCamMgr]
No back-facing camera found.

[10-01 01:38:28.914 4380:4380 W/CAM_Camera2OneCamMgr]
No external camera found.

[10-01 01:38:28.917 4380:4380 W/CAM_Camera2OneCamMgr]
No front-facing camera found.

[10-01 01:38:28.919 4380:4380 W/CAM_Camera2OneCamMgr]
No external camera found.

[10-01 01:38:28.953 4380:4380 W/CAM_Camera2OneCamMgr]
No back-facing camera found.

[10-01 01:38:28.957 4380:4380 W/CAM_Camera2OneCamMgr]
No external camera found.

[10-01 01:38:28.965 4380:4380 E/CAM_FatalErrorHandler]
Handling Camera Access Failure:
java.lang.Exception
	at com.android.camera.FatalErrorHandlerImpl.onGenericCameraAccessFailure(FatalErrorHandlerImpl.java:84)
	at com.android.camera.CaptureModule.updateCameraCharacteristics(CaptureModule.java:396)
	at com.android.camera.CaptureModule.init(CaptureModule.java:417)
	at com.android.camera.CameraActivity.onCreateTasks(CameraActivity.java:1629)
	at com.android.camera.util.QuickActivity.onCreate(QuickActivity.java:114)
	at android.app.Activity.performCreate(Activity.java:8000)
	at android.app.Activity.performCreate(Activity.java:7984)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3422)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7656)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

[10-01 01:38:28.971 4380:4380 E/CAM_CameraUtil]
Show fatal error dialog

[10-01 01:38:29.068 4380:4380 I/CAM_Profiler]
[1336,335ms][ui] GUARD: CameraActivity.onCreateTasks - [175,139ms] Init CurrentModule

[10-01 01:38:29.159 4380:4380 I/CAM_Profiler]
[1426,370ms][ui] GUARD: CameraActivity.onCreateTasks - STOP

[10-01 01:38:29.217 4380:4380 I/CAM_Profiler]
[ 29,731ms][ui] GUARD: CameraActivity.resume - STOP

[10-01 01:38:29.666 1546:1738 D/ArtManagerInternalImpl]
/data/misc/iorapd/com.android.camera2/20002100/com.android.camera.CameraLauncher/compiled_traces/compiled_trace.pb doesn't exist

[10-01 01:38:29.677 1546:1738 I/ActivityTaskManager]
Displayed com.android.camera2/com.android.camera.CameraLauncher: +2s709ms

[10-01 01:38:32.090 4380:4411 W/CAM2PORT_AndCamAgntImp]
Releasing camera without any camera opened.

[10-01 01:38:32.106 4380:4380 I/CAM_Profiler]
[ 74,486ms][ui] GUARD: CameraActivity.onPause - STOP

[10-01 01:38:33.078 4380:4411 W/CAM2PORT_AndCamAgntImp]
Releasing camera without any camera opened.

**Comment by dmitriyvt** [comment]
**Sound**

<<< log_count = 40 >>>
[10-01 21:03:49.765 1546:7576 E/SoundPool::Sound]
doLoad: unable to load sound

[10-01 21:03:49.766 1546:1909 W/AS.SfxHelper]
onLoadSoundEffects(), Error -2147483648 while loading sample /product/media/audio/ui/Effect_Tick.ogg

[10-01 21:03:49.766 1546:1909 W/AS.SfxHelper]
onLoadSoundEffects(), Error while loading samples

[10-01 21:03:49.791 1546:7575 E/SoundPool::Sound]
doLoad: unable to load sound

[10-01 21:03:50.916 1546:1738 D/ArtManagerInternalImpl]
/data/misc/iorapd/com.android.soundpicker/30/com.android.soundpicker.RingtonePickerActivity/compiled_traces/compiled_trace.pb doesn't exist

[10-01 21:03:54.249 1546:7576 E/SoundPool::Sound]
doLoad: unable to load sound

[10-01 21:03:54.296 1546:1909 W/AS.SfxHelper]
onLoadSoundEffects(), Error while loading samples

[10-01 21:03:58.514 1546:1872 I/WindowManager]
Input event dispatching timed out sending to com.android.soundpicker/com.android.soundpicker.RingtonePickerActivity.  Reason: 77c4869 com.android.soundpicker/com.android.soundpicker.RingtonePickerActivity (server) is not responding. Waited 5003ms for MotionEvent(deviceId=4, source=0x00001002, displayId=0, action=DOWN, actionButton=0x00000000, flags=0x00000000, metaState=0x00000000, buttonState=0x00000000, classification=NONE, edgeFlags=0x00000000, xPrecision=1.0, yPrecision=1.0, xCursorPosition=nan, yCursorPosition=nan, pointers=[0: (587.0, 1332.0)]), policyFlags=0x62000000

[10-01 21:03:58.729 1546:1872 W/InputDispatcher]
Canceling events for 77c4869 com.android.soundpicker/com.android.soundpicker.RingtonePickerActivity (server) because it is unresponsive

[10-01 21:03:58.907 1546:1872 W/InputDispatcher]
Unresponsive window Window{77c4869 u0 com.android.soundpicker/com.android.soundpicker.RingtonePickerActivity} will not get the new gesture at 1407058615000

[10-01 21:03:59.313 1546:1872 I/InputDispatcher]
77c4869 com.android.soundpicker/com.android.soundpicker.RingtonePickerActivity (server) spent 5820ms processing MotionEvent(deviceId=4, source=0x00001002, displayId=0, action=DOWN, actionButton=0x00000000, flags=0x00000000, metaState=0x00000000, buttonState=0x00000000, classification=NONE, edgeFlags=0x00000000, xPrecision=1.0, yPrecision=1.0, xCursorPosition=nan, yCursorPosition=nan, pointers=[0: (587.0, 1332.0)]), policyFlags=0x62000000

[10-01 21:03:59.314 1546:1872 I/InputDispatcher]
77c4869 com.android.soundpicker/com.android.soundpicker.RingtonePickerActivity (server) spent 5812ms processing MotionEvent(deviceId=4, source=0x00001002, displayId=0, action=MOVE, actionButton=0x00000000, flags=0x00000000, metaState=0x00000000, buttonState=0x00000000, classification=NONE, edgeFlags=0x00000000, xPrecision=1.0, yPrecision=1.0, xCursorPosition=nan, yCursorPosition=nan, pointers=[0: (587.0, 1332.0)]), policyFlags=0x62000000

[10-01 21:03:59.317 1546:1872 I/InputDispatcher]
77c4869 com.android.soundpicker/com.android.soundpicker.RingtonePickerActivity (server) spent 5804ms processing MotionEvent(deviceId=4, source=0x00001002, displayId=0, action=MOVE, actionButton=0x00000000, flags=0x00000000, metaState=0x00000000, buttonState=0x00000000, classification=NONE, edgeFlags=0x00000000, xPrecision=1.0, yPrecision=1.0, xCursorPosition=nan, yCursorPosition=nan, pointers=[0: (587.0, 1332.0)]), policyFlags=0x62000000

[10-01 21:03:59.321 1546:1872 I/InputDispatcher]
77c4869 com.android.soundpicker/com.android.soundpicker.RingtonePickerActivity (server) spent 5795ms processing MotionEvent(deviceId=4, source=0x00001002, displayId=0, action=MOVE, actionButton=0x00000000, flags=0x00000000, metaState=0x00000000, buttonState=0x00000000, classification=NONE, edgeFlags=0x00000000, xPrecision=1.0, yPrecision=1.0, xCursorPosition=nan, yCursorPosition=nan, pointers=[0: (587.0, 1332.0)]), policyFlags=0x62000000

[10-01 21:03:59.322 1546:1872 I/InputDispatcher]
77c4869 com.android.soundpicker/com.android.soundpicker.RingtonePickerActivity (server) spent 5787ms processing MotionEvent(deviceId=4, source=0x00001002, displayId=0, action=MOVE, actionButton=0x00000000, flags=0x00000000, metaState=0x00000000, buttonState=0x00000000, classification=NONE, edgeFlags=0x00000000, xPrecision=1.0, yPrecision=1.0, xCursorPosition=nan, yCursorPosition=nan, pointers=[0: (587.0, 1332.0)]), policyFlags=0x62000000

[10-01 21:03:59.324 1546:1872 I/InputDispatcher]
77c4869 com.android.soundpicker/com.android.soundpicker.RingtonePickerActivity (server) spent 5778ms processing MotionEvent(deviceId=4, source=0x00001002, displayId=0, action=MOVE, actionButton=0x00000000, flags=0x00000000, metaState=0x00000000, buttonState=0x00000000, classification=NONE, edgeFlags=0x00000000, xPrecision=1.0, yPrecision=1.0, xCursorPosition=nan, yCursorPosition=nan, pointers=[0: (587.0, 1332.0)]), policyFlags=0x62000000

[10-01 21:03:59.326 1546:1872 I/InputDispatcher]
77c4869 com.android.soundpicker/com.android.soundpicker.RingtonePickerActivity (server) spent 5766ms processing MotionEvent(deviceId=4, source=0x00001002, displayId=0, action=MOVE, actionButton=0x00000000, flags=0x00000000, metaState=0x00000000, buttonState=0x00000000, classification=NONE, edgeFlags=0x00000000, xPrecision=1.0, yPrecision=1.0, xCursorPosition=nan, yCursorPosition=nan, pointers=[0: (587.0, 1332.0)]), policyFlags=0x62000000

[10-01 21:03:59.327 1546:1872 I/InputDispatcher]
77c4869 com.android.soundpicker/com.android.soundpicker.RingtonePickerActivity (server) spent 5757ms processing MotionEvent(deviceId=4, source=0x00001002, displayId=0, action=MOVE, actionButton=0x00000000, flags=0x00000000, metaState=0x00000000, buttonState=0x00000000, classification=NONE, edgeFlags=0x00000000, xPrecision=1.0, yPrecision=1.0, xCursorPosition=nan, yCursorPosition=nan, pointers=[0: (587.0, 1332.0)]), policyFlags=0x62000000

[10-01 21:03:59.332 1546:1872 I/InputDispatcher]
77c4869 com.android.soundpicker/com.android.soundpicker.RingtonePickerActivity (server) spent 5752ms processing MotionEvent(deviceId=4, source=0x00001002, displayId=0, action=MOVE, actionButton=0x00000000, flags=0x00000000, metaState=0x00000000, buttonState=0x00000000, classification=NONE, edgeFlags=0x00000000, xPrecision=1.0, yPrecision=1.0, xCursorPosition=nan, yCursorPosition=nan, pointers=[0: (587.0, 1332.0)]), policyFlags=0x62000000

[10-01 21:03:59.335 1546:1872 I/InputDispatcher]
77c4869 com.android.soundpicker/com.android.soundpicker.RingtonePickerActivity (server) spent 5743ms processing MotionEvent(deviceId=4, source=0x00001002, displayId=0, action=MOVE, actionButton=0x00000000, flags=0x00000000, metaState=0x00000000, buttonState=0x00000000, classification=NONE, edgeFlags=0x00000000, xPrecision=1.0, yPrecision=1.0, xCursorPosition=nan, yCursorPosition=nan, pointers=[0: (587.0, 1332.0)]), policyFlags=0x62000000

[10-01 21:03:59.335 1546:1872 I/InputDispatcher]
77c4869 com.android.soundpicker/com.android.soundpicker.RingtonePickerActivity (server) spent 5734ms processing MotionEvent(deviceId=4, source=0x00001002, displayId=0, action=MOVE, actionButton=0x00000000, flags=0x00000000, metaState=0x00000000, buttonState=0x00000000, classification=NONE, edgeFlags=0x00000000, xPrecision=1.0, yPrecision=1.0, xCursorPosition=nan, yCursorPosition=nan, pointers=[0: (587.0, 1332.0)]), policyFlags=0x62000000

[10-01 21:03:59.338 1546:1872 I/InputDispatcher]
77c4869 com.android.soundpicker/com.android.soundpicker.RingtonePickerActivity (server) spent 5748ms processing MotionEvent(deviceId=4, source=0x00001002, displayId=0, action=UP, actionButton=0x00000000, flags=0x00000000, metaState=0x00000000, buttonState=0x00000000, classification=NONE, edgeFlags=0x00000000, xPrecision=1.0, yPrecision=1.0, xCursorPosition=nan, yCursorPosition=nan, pointers=[0: (587.0, 1332.0)]), policyFlags=0x62000000

[10-01 21:03:59.378 7482:7491 I/oid.soundpicke]
Thread[5,tid=7491,WaitingInMainSignalCatcherLoop,Thread*=0x704f4c7be0,peer=0x12d401b0,"Signal Catcher"]: reacting to signal 3

[10-01 21:03:59.379 7482:7491 I/oid.soundpicke]


[10-01 21:03:59.415 1546:1909 W/AS.SfxHelper]
onLoadSoundEffects(), Error while loading samples

[10-01 21:03:59.453 7482:7493 E/oid.soundpicke]
failed to connect to jdwp control socket: Interrupted system call

[10-01 21:03:59.609 7482:7491 I/oid.soundpicke]
Wrote stack traces to tombstoned

[10-01 21:04:05.257 1546:7654 E/SoundPool::Sound]
doLoad: unable to load sound

[10-01 21:04:07.527 1546:7645 E/ActivityManager]
ANR in com.android.soundpicker (com.android.soundpicker/.RingtonePickerActivity)
PID: 7482
Reason: Input dispatching timed out (77c4869 com.android.soundpicker/com.android.soundpicker.RingtonePickerActivity (server) is not responding. Waited 5003ms for MotionEvent(deviceId=4, source=0x00001002, displayId=0, action=DOWN, actionButton=0x00000000, flags=0x00000000, metaState=0x00000000, buttonState=0x00000000, classification=NONE, edgeFlags=0x00000000, xPrecision=1.0, yPrecision=1.0, xCursorPosition=nan, yCursorPosition=nan, pointers=[0: (587.0, 1332.0)]), policyFlags=0x62000000)
Parent: com.android.soundpicker/.RingtonePickerActivity
Load: 19.09 / 18.97 / 14.25
CPU usage from 0ms to 8755ms later (2020-10-01 21:03:58.735 to 2020-10-01 21:04:07.489):
  98% 2594/adbd: 16% user + 82% kernel
  48% 1546/system_server: 24% user + 23% kernel / faults: 19515 minor
  42% 4010/com.dp.logcatapp: 23% user + 18% kernel / faults: 6032 minor 2 major
  29% 2054/com.android.systemui: 16% user + 12% kernel / faults: 6393 minor
  26% 2044/com.android.bluetooth: 15% user + 11% kernel / faults: 24268 minor
  20% 2339/com.android.launcher3: 9.2% user + 10% kernel / faults: 537 minor
  18% 3047/com.android.inputmethod.latin: 3.6% user + 14% kernel / faults: 3937 minor
  17% 970/surfaceflinger: 11% user + 5.9% kernel / faults: 926 minor
  16% 3340/com.android.providers.media.module: 3.2% user + 13% kernel / faults: 1705 minor
  16% 7226/com.android.settings: 5.9% user + 10% kernel / faults: 380 minor
  15% 3278/com.android.permissioncontroller: 1.1% user + 14% kernel
  15% 5151/com.android.calendar: 1.2% user + 14% kernel
  15% 7482/com.android.soundpicker: 5% user + 9.9% kernel / faults: 5645 minor 1 major
  14% 1//init: 11% user + 3.5% kernel / faults: 171 minor
  14% 2995/com.android.smspush: 1.7% user + 12% kernel
  13% 2191/com.android.networkstack.process: 2.2% user + 11% kernel / faults: 1324 minor
  13% 2253/com.android.phone: 3% user + 10% kernel / faults: 1616 minor
  12% 2725/com.android.ims.rcsservice: 2.4% user + 10% kernel / faults: 1221 minor
  12% 3302/com.android.providers.calendar: 2.4% user + 10% kernel / faults: 2300 minor
  12% 2295/android.ext.services: 2% user + 10% kernel / faults: 2344 minor
  12% 2863/android.process.media: 1.1% user + 11% kernel
  12% 2224/com.android.se: 2.2% user + 9.7% kernel / faults: 1235 minor
  11% 3573/com.android.externalstorage: 1.9% user + 9.7% kernel
  11% 7264/com.android.settings.intelligence: 2.1% user + 9.5% kernel / faults: 1 minor
  11% 5927/me.phh.superuser:superuser: 1.6% user + 9.9% kernel
  11% 3259/com.android.packageinstaller: 1.7% user + 9.7% kernel
  11% 7419/system:ui: 1.6% user + 9.8% kernel
  11% 3450/me.phh.superuser: 1.3% user + 9.9% kernel
  11% 3478/me.phh.treble.app: 2% user + 9.1% kernel
  11% 5195/com.android.deskclock: 1.7% user + 9.5% kernel
  11% 2499/com.android.cellbroadcastreceiver.module: 1.3% user + 9.7% kernel
  11% 5769/com.android.gallery3d: 1.2% user + 9.8% kernel
  5.3% 917/android.hardware.graphics.composer@2.1-service: 3.7% user + 1.6% kernel / faults: 2 minor
  4% 1103/thermal-engine: 2.9% user + 1% kernel
  3.2% 456/logd: 1.9% user + 1.2% kernel
  1.3% 21/rcuop/1: 0% user + 1.3% kernel
  1.3% 1129/media.swcodec: 0.4% user + 0.9% kernel / faults: 2507 minor
  1.3% 1134/mediaserver: 0.6% user + 0.6% kernel / faults: 234 minor
  1% 331/ts_thread:0: 0% user + 1% kernel
  1% 3998/mdss_fb0: 0% user + 1% kernel
  0.9% 29/rcuop/2: 0% user + 0.9% kernel
  0.9% 935/vendor.huawei.hardware.sensors@1.0-service: 0.4% user + 0.4% kernel
  0.9% 1671/audioserver: 0.4% user + 0.4% kernel / faults: 115 minor
  0.9% 7557/logcat: 0.4% user + 0.4% kernel
  0.8% 37/rcuop/3: 0% user + 0.8% kernel
  0.8% 45/rcuop/4: 0% user + 0.8% kernel
  0.8% 255/kgsl_worker_thr: 0% user + 0.8% kernel
  0.6% 53/rcuop/5: 0% user + 0.6% kernel
  0.6% 61/rcuop/6: 0% user + 0.6% kernel
  0.6% 69/rcuop/7: 0% user + 0.6% kernel
  0.5% 10/rcuop/0: 0% user + 0.5% kernel
  0.4% 7/rcu_preempt: 0% user + 0.4% kernel

[10-01 21:04:07.528 1546:7645 E/ActivityManager]
  0.4% 115/system: 0% user + 0.4% kernel
  0.4% 4043/kworker/u16:3: 0% user + 0.4% kernel
  0.4% 6903/kworker/u16:5: 0% user + 0.4% kernel
  0.3% 338/kworker/u16:6: 0% user + 0.3% kernel
  0.3% 457/servicemanager: 0.2% user + 0.1% kernel
  0% 803/tombstoned: 0% user + 0% kernel
  0.2% 313/cfinteractive: 0% user + 0.2% kernel
  0.2% 2598/adbd: 0.1% user + 0.1% kernel
  0.2% 5023/kworker/u16:4: 0% user + 0.2% kernel
  0.1% 8/rcu_sched: 0% user + 0.1% kernel
  0.1% 42/ksoftirqd/4: 0% user + 0.1% kernel
  0% 46/rcuos/4: 0% user + 0% kernel
  0.1% 56/migration/6: 0% user + 0.1% kernel
  0.1% 322/mmc-cmdqd/0: 0% user + 0.1% kernel
  0.1% 395/ueventd: 0% user + 0.1% kernel
  0.1% 458/hwservicemanager: 0.1% user + 0% kernel
  0.1% 784/vold: 0% user + 0.1% kernel / faults: 45 minor
  0.1% 806/netd: 0% user + 0.1% kernel / faults: 77 minor
  0.1% 946/healthd: 0% user + 0.1% kernel
  0% 1091/rcc: 0% user + 0% kernel
  0.1% 1111/cameraserver: 0% user + 0.1% kernel / faults: 47 minor
  0.1% 1133/media.metrics: 0% user + 0.1% kernel / faults: 16 minor
  0% 1211/msm_thermal:fre: 0% user + 0% kernel
  0.1% 1282/rild: 0.1% user + 0% kernel / faults: 5 minor
  0% 1636/kworker/2:2: 0% user + 0% kernel
  0.1% 1887/VosMCThread: 0% user + 0.1% kernel
  0.1% 4093/kworker/6:2: 0% user + 0.1% kernel
  0.1% 5047/kworker/0:1: 0% user + 0.1% kernel
 +0% 7646/media.codec: 0% user + 0% kernel
81% TOTAL: 26% user + 55% kernel + 0% iowait + 0% softirq
CPU usage from 93ms to 558ms later (2020-10-01 21:03:58.827 to 2020-10-01 21:03:59.293):
  96% 1//init: 75% user + 21% kernel / faults: 35 minor
  96% 2594/adbd: 12% user + 83% kernel
    96% 2594/adbd: 12% user + 83% kernel
  66% 1546/system_server: 31% user + 34% kernel / faults: 405 minor
    34% 7645/AnrConsumer: 11% user + 23% kernel
    11% 1553/ADB-JDWP Connec: 5.7% user + 5.7% kernel
    11% 1554/HeapTaskDaemon: 11% user + 0% kernel
    2.8% 1560/ReferenceQueueD: 0% user + 2.8% kernel
  20% 4010/com.dp.logcatapp: 6.6% user + 13% kernel / faults: 6 minor
    20% 4021/ADB-JDWP Connec: 3.3% user + 16% kernel
    3.3% 7561/logcat-stdout: 3.3% user + 0% kernel
  16% 3302/com.android.providers.calendar: 3.2% user + 13% kernel
    16% 3313/ADB-JDWP Connec: 3.2% user + 13% kernel
  16% 3340/com.android.providers.media.module: 0% user + 16% kernel
    19% 3351/ADB-JDWP Connec: 0% user + 19% kernel
  17% 7482/com.android.soundpicker: 7.1% user + 10% kernel / faults: 100 minor
    10% 7493/ADB-JDWP Connec: 0% user + 10% kernel
    7.1% 7503/RenderThread: 3.5% user + 3.5% kernel
    3.5% 7482/oid.soundpicker: 3.5% user + 0% kernel
  12% 2044/com.android.bluetooth: 3% user + 9% kernel
    12% 2066/ADB-JDWP Connec: 3% user + 9% kernel
  12% 2224/com.android.se: 0% user + 12% kernel
    9.5% 2237/ADB-JDWP Connec: 0% user + 9.5% kernel
  12% 2253/com.android.phone: 0% user + 12% kernel
    9.5% 2272/ADB-JDWP Connec: 0% user + 9.5% kernel
  12% 2295/android.ext.services: 3.2% user + 9.6% kernel
    9.6% 2307/ADB-JDWP Connec: 0% user + 9.6% kernel
  12% 2863/android.process.media: 3.2% user + 9.7% kernel
    12% 2880/ADB-JDWP Connec: 3.2% user + 9.7% kernel
  12% 3047/com.android.inputmethod.latin: 0% user + 12% kernel
    16% 3059/ADB-JDWP Connec: 3.2% user + 12% kernel
  12% 3259/com.android.packageinstaller: 3.2% user + 9.7% kernel
    12% 3270/ADB-JDWP Connec: 3.2% user + 9.7% kernel
  12% 3278/com.android.permissioncontroller: 0% user + 12% kernel
    16% 3289/ADB-JDWP Connec: 3.2% user + 12% kernel
  13% 3390/com.android.shell: 0% user + 13% kernel
    13% 3406/ADB-JDWP Connec: 0% user + 13% kernel
  13% 3573/com.android.externalstorage: 3.3% user + 9.9% kernel
    13% 3584/ADB-JDWP Connec: 3.3% user + 9.9% kernel
  13% 5151/com.android.calendar: 0% user + 13% kernel
    17% 5163/ADB-JDWP Connec: 3.4% user + 13% kernel
  13% 5769/com.android.gallery3d: 3.4% user + 10% kernel
    10% 5781/ADB-JDWP Connec: 3.4% user + 6.9% kernel
  9.2% 2054/com.android.systemui: 3% user + 6.1% kernel

[10-01 21:04:07.531 1546:7645 I/ActivityManager]
Killing 7482:com.android.soundpicker/u0a48 (adj 905): bg anr

[10-01 21:04:07.532 1546:7645 D/ActivityManager]
Completed ANR of com.android.soundpicker in 8798ms, latency 5ms

[10-01 21:04:09.299 1546:1909 W/AS.SfxHelper]
onLoadSoundEffects(), Error while loading samples

[10-01 21:04:10.591 1546:7734 E/SoundPool::Sound]
doLoad: unable to load sound

[10-01 21:04:10.594 1546:7735 E/SoundPool::Sound]
doLoad: unable to load sound

[10-01 21:05:12.150 1546:7787 E/SoundPool::Sound]
doLoad: unable to load sound

[10-01 21:05:12.157 1546:1909 W/AS.SfxHelper]
onLoadSoundEffects(), Error -2147483648 while loading sample /product/media/audio/ui/Effect_Tick.ogg

[10-01 21:05:12.157 1546:1909 W/AS.SfxHelper]
onLoadSoundEffects(), Error while loading samples

[10-01 21:05:12.679 1546:7787 E/SoundPool::Sound]
doLoad: unable to load sound

[10-01 21:05:12.683 1546:7786 E/SoundPool::Sound]
doLoad: unable to load sound

**Comment by Pey-crypto** [comment]
Permission failure: android.permission.CAMERA_OPEN_CLOSE_LISTENER from uid=10102 pid=4380
Could you try resetting the Camera app by clearing its data?
Maybe try downloading another camera app to check.

**Comment by dmitriyvt** [comment]
I tried all these ways

**Comment by Pey-crypto** [comment]
First Try running this app on the phone:
https://play.google.com/store/apps/details?id=com.camera2.test

Try Installing another camera app and try getting the log for that if it crashes
Also, grant all permissions for the stock camera app

**Comment by dmitriyvt** [comment]
I understand, I will do it, thanks
