### ISSUE TITLE
[AOSP 11.0 v300.f] Several bugs

### ISSUE THREAD

**Issue by 0x15f2d** [phhusson/treble_experimentations#1530]
What I did:
- Changing prop.default to get the ROM display phone model and ROM name correctly (Won't effect anything)
- Applying or editing custom overlay
- E adbd : cannot open control endpoint /dev/usb-ffs/adb/ep0: Device or resource busy
- Deleted unnecessary overlays in /product/overlay/treble-overlay-*.apk (Except criticals like webview, devinputjack (this isn't working at all), mtk-ims, etc...) (Since those overlays doesn't affect with my barebone phone so it doesn't matter)
- Codec playback error (When opening Screen Recording file to Gallery Go/Chromium (except Files go), Playback web content in Chromium, Illustration for Android Navigation in gesture settings).
- Can't scrcpy it.
"INFO: scrcpy 1.16 <https://github.com/Genymobile/scrcpy>
C:\Program Files\Genymobile\scrcpy\scrcpy-server: 1 file pushed, 0 skipped. 2.3 MB/s (33622 bytes in 0.014s)
[server] INFO: Device: Revoview S41 (Android 11)
INFO: Renderer: direct3d
INFO: Initial texture: 480x848
WARN: Device disconnected
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.IllegalStateException
        at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
        at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:3452)
        at com.genymobile.scrcpy.ScreenEncoder.encode(ScreenEncoder.java:108)
        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:89)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:55)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:76)
        at com.genymobile.scrcpy.Server.main(Server.java:225)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:399)
Press any key to continue...
"
- 

Multi-user:
- Whether you're a Guest or a New user. Apps like Quickstep, Messages and some others will crashes immediately except Settings. I can't even record the screen.
- The only usable user is the user 0 (Default user)

What happened if I apply overlays:
- Tons of apps will not have storage access.
- Applying custom overlay targeting to package "android" will make system unbootable if you reset the phone. 
- Without reset userdata it still "kind of" working fine.
- The overlay applied as expected but causes unwanted bugs like you can't install selective apps like Chromium or GSF (Targeting R+ (version 30 and above) requires the resources.arsc of installed APKs to be stored uncompressed and aligned on a 4-byte boundary).
- If my test-key signed overlay boot up with system and having Chromium or similar apps installed. It will be uninstalled.
Note that I haven't tested other "custom signed" overlay to other target packages yet.

**Comment by TheNextGamer21** [comment]
there is a reason why it says not meant for daily use

**Comment by 0x15f2d** [comment]
well. this one doesnt and I expect all of them to be buggy.

and you need to report too.

my phone cant display anything since that build until this one. but he doesnt said that he fixed it.

**Comment by phhusson** [comment]
So far the only issue I see in there that I care about is that your hardware video decoder seem broken.
For that, I'll  need you to give me logcat at early boot, and the result of getprop
