### ISSUE TITLE
[Nokia 6.1] NfcService crashes on start

### ISSUE THREAD

**Issue by MarcBook** [phhusson/treble_experimentations#158]
Hi,
I just bought a Nokia 6.1 and build my own Android.
Everything works fine except NFC.
I did some research in the Code and found the crash point.

The NfcService crashes in the method `applyRouting(boolean force)` in `packages/apps/Nfc/src/com/android/nfc/NfcService.java`
The following line causes the crash:
`mDeviceHost.enableDiscovery(newParams, shouldRestart);`

In the logcat log i found the following interesting lines:

```
08-29 00:32:47.507  3601  3617 D NfcService: checking on firmware download
08-29 00:32:47.508  3601  3617 D NfcService: NFC is on. Doing normal stuff
08-29 00:32:47.508  3601  3617 I NfcService: Enabling NFC
08-29 00:32:47.510  3601  3617 E NfcService: Start watchDog enableInternal
08-29 00:32:47.516  3601  3620 E libnfc_nci: [ERROR:gki_ulinux.cc(98)] gki_task task_id=0 terminating
08-29 00:32:47.517  3601  3617 E libnfc_nci: [ERROR:NativeNfcManager.cpp(1030)] 
08-29 00:32:47.518   859   859 D         : ro.boot.device = PL2
08-29 00:32:47.518   859   859 E         : devmodel: msg[0]= P
08-29 00:32:47.518   859   859 E         : devmodel: msg[1]= L
08-29 00:32:47.518   859   859 E         : devmodel: msg[2]= 2
08-29 00:32:47.518   859   859 E         : DUT is not C1N
08-29 00:32:47.518   859   859 I         : default config file exists = /vendor/etc/libnfc-nxp.conf, disables dynamic selection
08-29 00:32:47.518   859   859 D         : readConfig Opened base config /vendor/etc/libnfc-nxp.conf
08-29 00:32:47.533   859   859 D         : phNxpLog_InitializeLogLevel: global =1, Fwdnld =1, extns =1,                 hal =1, tml =1, ncir =1,          
```

and

```
08-29 00:33:04.633  3666  3684 E libnfc_nci: [ERROR:NativeNfcManager.cpp(1039)] 
08-29 00:33:04.633  3666  3688 E libnfc_nci: [ERROR:HciEventManager.cpp(151)] Incorrect Pipe Id
08-29 00:33:04.642  3666  3684 E NfcService: Cancel watchDog enableInternal
08-29 00:33:04.642  3666  3684 D NfcService: NCI_Version: 16
08-29 00:33:04.643  3666  3684 D NdefPushServer: start, thread = null
08-29 00:33:04.643  3666  3684 D NdefPushServer: starting new server thread
08-29 00:33:04.644  3666  3697 D NdefPushServer: about create LLCP service socket
08-29 00:33:04.644  3666  3697 D NdefPushServer: created LLCP service socket
08-29 00:33:04.644  3666  3697 D NdefPushServer: about to accept
08-29 00:33:04.648  2226  2226 E NFC     : NFC service dead - attempting to recover
08-29 00:33:04.648  2226  2226 E NFC     : android.os.DeadObjectException
08-29 00:33:04.648  2226  2226 E NFC     : 	at android.os.BinderProxy.transactNative(Native Method)
08-29 00:33:04.648  2226  2226 E NFC     : 	at android.os.BinderProxy.transact(Binder.java:1127)
08-29 00:33:04.648  2226  2226 E NFC     : 	at android.nfc.INfcAdapter$Stub$Proxy.isNdefPushEnabled(INfcAdapter.java:497)
08-29 00:33:04.648  2226  2226 E NFC     : 	at android.nfc.NfcAdapter.isNdefPushEnabled(NfcAdapter.java:1670)
08-29 00:33:04.648  2226  2226 E NFC     : 	at com.android.settings.nfc.AndroidBeamEnabler.handleNfcStateChanged(AndroidBeamEnabler.java:65)
08-29 00:33:04.648  2226  2226 E NFC     : 	at com.android.settings.nfc.BaseNfcEnabler$1.onReceive(BaseNfcEnabler.java:40)
08-29 00:33:04.648  2226  2226 E NFC     : 	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1391)
08-29 00:33:04.648  2226  2226 E NFC     : 	at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(Unknown Source:2)
08-29 00:33:04.648  2226  2226 E NFC     : 	at android.os.Handler.handleCallback(Handler.java:873)
08-29 00:33:04.648  2226  2226 E NFC     : 	at android.os.Handler.dispatchMessage(Handler.java:99)
08-29 00:33:04.648  2226  2226 E NFC     : 	at android.os.Looper.loop(Looper.java:193)
08-29 00:33:04.648  2226  2226 E NFC     : 	at android.app.ActivityThread.main(ActivityThread.java:6669)
08-29 00:33:04.648  2226  2226 E NFC     : 	at java.lang.reflect.Method.invoke(Native Method)
08-29 00:33:04.648  2226  2226 E NFC     : 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
08-29 00:33:04.648  2226  2226 E NFC     : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

[logcat.txt](https://github.com/phhusson/treble_experimentations/files/2333331/logcat.txt)
[libnfc-nxp.conf](https://github.com/phhusson/treble_experimentations/files/2333337/libnfc-nxp.conf.txt)

I hope someone can help me to solve this issue. I'm not a pro and just started with android.
Thanks for your help.

**Comment by phhusson** [comment]
That's on O or P?

**Comment by MarcBook** [comment]
Just updated to P. I think NFC is also not working on O.

**Comment by phhusson** [comment]
NFC not working on Pie is for all devices, so you'll need to check on O.

I guess you applied what's in https://github.com/phhusson/treble_experimentations/issues/110
Could you check the various values of call numbers? (and reply to that issue)

**Comment by MarcBook** [comment]
Thanks a lot with Android O it works fine.
