### ISSUE TITLE
Camera failure

### ISSUE THREAD

**Issue by numen62** [phhusson/treble_experimentations#1663]
note7p  ulefone 

spoiled rear camera

**Comment by phhusson** [comment]
front camera works?
logs?
On which GSI?
What's the SoC?
What's stock ROM's Android version?

**Comment by numen62** [comment]
hello 
thank you very much
android stock version 9 - pie
front camera = good
rear camera = spoiled
rear camera video = good
cpu mediatek 6761 arm64 v8a

**Comment by smartbab** [comment]
Arm64 ab

**Comment by smartbab** [comment]
Hello 
Please support mediatek 6761 
Mount point ---->     /
System as ----->      yes

**Comment by RocketJannis** [comment]
Same here for Samsung A8 (2018). Worked on phh 10 gsi
Vendor: 10
System: 11 (Lineage OS 18.1 GSI)

Torch via shortcuts displays: "Camera in use"
Open Camera displays: "Failed to open camera. Camera may be in use by another application? ID:0"

If you need any additional information, please ask me :)

Logs when I open Open Camera:

```
01-09 14:57:46.904 I/ActivityTaskManager(4209): Displayed net.sourceforge.opencamera/.MainActivity: +527ms
01-09 14:57:46.928 W/MediaProvider(5404): Recovered abusive '3' from 'content://media/external/images/media?limit=3'
01-09 14:57:46.968 W/MediaProvider(5404): Recovered abusive '3' from 'content://media/external/video/media?limit=3'
01-09 14:57:47.007 W/MediaProvider(5404): Recovered abusive '3' from 'content://media/external/video/media?limit=3'
01-09 14:57:47.030 W/ServiceManager(4070): Permission failure: android.permission.SYSTEM_CAMERA from uid=10189 pid=7434
01-09 14:57:47.031 E/CameraService(4070): cameraIdIntToStrLocked: input id 0 invalid: valid range  (0, 0)
01-09 14:57:47.031 I/CameraService(4070): CameraService::connect call (PID -1 "net.sourceforge.opencamera", camera ID ) for HAL version default and Camera API version 1
01-09 14:57:47.031 E/CameraService(4070): shouldRejectSystemCameraConnection: Invalid camera id , 
01-09 14:57:47.031 W/CameraService(4070): Attempting to connect to system-only camera id , connection rejected
01-09 14:57:47.032 W/CameraBase(7434): An error occurred while connecting to camera 0: Status(-8, EX_SERVICE_SPECIFIC): '4: validateClientPermissionsLocked:1171: No camera device with ID "" isavailable'
01-09 14:57:47.032 W/System.err(7434): java.lang.RuntimeException: Fail to connect to camera service
01-09 14:57:47.033 W/System.err(7434): 	at android.hardware.Camera.<init>(Camera.java:587)
01-09 14:57:47.034 W/System.err(7434): 	at android.hardware.Camera.open(Camera.java:428)
01-09 14:57:47.034 W/System.err(7434): 	at net.sourceforge.opencamera.cameracontroller.CameraController1.<init>(CameraController1.java:62)
01-09 14:57:47.034 W/System.err(7434): 	at net.sourceforge.opencamera.preview.Preview.openCameraCore(Preview.java:1633)
01-09 14:57:47.034 W/System.err(7434): 	at net.sourceforge.opencamera.preview.Preview.access$1000(Preview.java:106)
01-09 14:57:47.034 W/System.err(7434): 	at net.sourceforge.opencamera.preview.Preview$1.doInBackground(Preview.java:1531)
01-09 14:57:47.034 W/System.err(7434): 	at net.sourceforge.opencamera.preview.Preview$1.doInBackground(Preview.java:1524)
01-09 14:57:47.034 W/System.err(7434): 	at android.os.AsyncTask$3.call(AsyncTask.java:394)
01-09 14:57:47.034 W/System.err(7434): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
01-09 14:57:47.034 W/System.err(7434): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
01-09 14:57:47.034 W/System.err(7434): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
01-09 14:57:47.034 W/System.err(7434): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
01-09 14:57:47.034 W/System.err(7434): 	at java.lang.Thread.run(Thread.java:923)
01-09 14:57:47.034 W/System.err(7434): net.sourceforge.opencamera.cameracontroller.CameraControllerException
01-09 14:57:47.035 W/System.err(7434): 	at net.sourceforge.opencamera.cameracontroller.CameraController1.<init>(CameraController1.java:68)
01-09 14:57:47.035 W/System.err(7434): 	at net.sourceforge.opencamera.preview.Preview.openCameraCore(Preview.java:1633)
01-09 14:57:47.035 W/System.err(7434): 	at net.sourceforge.opencamera.preview.Preview.access$1000(Preview.java:106)
01-09 14:57:47.035 W/System.err(7434): 	at net.sourceforge.opencamera.preview.Preview$1.doInBackground(Preview.java:1531)
01-09 14:57:47.035 W/System.err(7434): 	at net.sourceforge.opencamera.preview.Preview$1.doInBackground(Preview.java:1524)
01-09 14:57:47.035 W/System.err(7434): 	at android.os.AsyncTask$3.call(AsyncTask.java:394)
01-09 14:57:47.035 W/System.err(7434): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
01-09 14:57:47.035 W/System.err(7434): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
01-09 14:57:47.035 W/System.err(7434): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
01-09 14:57:47.036 W/System.err(7434): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
01-09 14:57:47.036 W/System.err(7434): 	at java.lang.Thread.run(Thread.java:923)
```

Two things that are weird about the logs:

- camera ID seems to be an empty string (cannot find the cameras?)
- camera permission denied (to non-existing camere makes sense somehow)

**Comment by RocketJannis** [comment]
Okay, I installed the lineageos "vndklite" (whatever that means xD) version today and all camera apps I use show a camera preview for 0.5 sec and then freeze. OpenCamera shows a toast "Serious camera error" if camera2 api is used. Original camera API just freezes. Flashlight via shortcuts works.
 
Tried with phh settings "Enable access to all cameras" and "Force enable camera2api HAL3" on and off but no difference

Logs: [2021-01-30-13-57-24.txt](https://github.com/phhusson/treble_experimentations/files/5897967/2021-01-30-13-57-24.txt)

Thanks for your work!!

**Comment by openStove** [comment]
I'm experiencing a similar problem on bv9900 wtih Android GSI 10 QQ3A.200805.001 eng.crossg.20201215.1701.20
- with camera App from lineage, it's working, but croping the image 
- wich camera App from lineage, and opening it from whatsapp or other messaging tool, its freezing after taking the picture

On opencamera,:
- it freezing after taking the picture
