### ISSUE TITLE
[v301] NewPipe video playback issue (and everything else using exoplayer)

### ISSUE THREAD

**Issue by assoc** [phhusson/treble_experimentations#1753]
System image: system-roar-arm32_binder64-ab-vndklite-vanilla

After upgrading from February build (v300.m) NewPipe video player stopped working ("Unrecoverable player error occurred"), but it doesn't crash (relevant logcat below).
Same thing with Slide (reddit app): it doesn't play video, but there is no error messages; logcat error is almost identical.

VLC and TotalCommander play video and audio just fine.

```
<<< log_count = 45 >>>
[03-06 17:24:52.977 13873:13873 D/ApplicationLoaders]
Returning zygote-cached class loader: /system/framework/android.test.base.jar

[03-06 17:24:52.980 13873:13873 W/.schabi.newpip]
Insufficient pre-allocated space to mmap vdex.

[03-06 17:24:52.999 13873:13873 I/MultiDex]
VM with version 2.1.0 has multidex support

[03-06 17:24:52.999 13873:13873 I/MultiDex]
Installing application

[03-06 17:24:52.999 13873:13873 I/MultiDex]
VM has multidex support, MultiDex support library is disabled.

[03-06 17:24:53.016 13873:13873 I/ACRA]
ACRA is enabled for org.schabi.newpipe, initializing...

[03-06 17:24:53.176 13873:13873 W/.schabi.newpip]
Accessing hidden field Ljava/util/Collections$SynchronizedCollection;->mutex:Ljava/lang/Object; (greylist-max-o, reflection, denied)

[03-06 17:24:53.177 13873:13873 W/.schabi.newpip]
Accessing hidden method Ljava/util/Collections$SynchronizedSet;-><init>(Ljava/util/Set;Ljava/lang/Object;)V (greylist-max-o, reflection, denied)

[03-06 17:24:53.177 13873:13873 W/.schabi.newpip]
Accessing hidden method Ljava/util/Collections$SynchronizedCollection;-><init>(Ljava/util/Collection;Ljava/lang/Object;)V (greylist-max-o, reflection, denied)

[03-06 17:24:53.735 13873:13873 E/libEGL]
call to OpenGL ES API with no current context (logged once per thread)

[03-06 17:24:59.641 13873:13873 W/BottomSheetBehavior]
BottomSheetBehavior now supports multiple callbacks. `setBottomSheetCallback()` removes all existing callbacks, including ones set internally by library authors, which may result in unintended behavior. This may change in the future. Please use `addBottomSheetCallback()` and `removeBottomSheetCallback()` instead to set your own callbacks.

[03-06 17:25:01.385 13873:13873 I/TetheringManager]
registerTetheringEventCallback:org.schabi.newpipe

[03-06 17:25:01.410 13873:13873 I/ExoPlayerImpl]
Init 95b86e8 [ExoPlayerLib/2.11.8] [phhgsi_a64_ab, Phh-Treble vanilla, unknown, 30]

[03-06 17:25:01.427 13873:13873 W/Player]
Broadcast receiver already unregistered: Receiver not registered: org.schabi.newpipe.player.Player$3@6d62994

[03-06 17:25:01.595 13873:13873 I/ExoPlayerImpl]
Release 95b86e8 [ExoPlayerLib/2.11.8] [phhgsi_a64_ab, Phh-Treble vanilla, unknown, 30] [goog.exo.core, goog.exo.mediasession]

[03-06 17:25:01.601 13873:13873 I/ExoPlayerImpl]
Init 345176b [ExoPlayerLib/2.11.8] [phhgsi_a64_ab, Phh-Treble vanilla, unknown, 30]

[03-06 17:25:02.455 13873:13873 W/System.err]
com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.google.aac.decoder, Format(2, null, null, audio/mp4a-latm, null, -1, en, [-1, -1, -1.0], [2, 44100])

[03-06 17:25:02.456 13873:13873 W/System.err]
	at com.google.android.exoplayer2.BaseRenderer.createRendererException(BaseRenderer.java:359)

[03-06 17:25:02.456 13873:13873 W/System.err]
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:563)

[03-06 17:25:02.456 13873:13873 W/System.err]
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1254)

[03-06 17:25:02.456 13873:13873 W/System.err]
	at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.onInputFormatChanged(MediaCodecAudioRenderer.java:556)

[03-06 17:25:02.459 13873:13873 W/System.err]
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readToFlagsOnlyBuffer(MediaCodecRenderer.java:814)

[03-06 17:25:02.459 13873:13873 W/System.err]
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:712)

[03-06 17:25:02.459 13873:13873 W/System.err]
	at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:599)

[03-06 17:25:02.459 13873:13873 W/System.err]
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:329)

[03-06 17:25:02.459 13873:13873 W/System.err]
	at android.os.Handler.dispatchMessage(Handler.java:102)

[03-06 17:25:02.459 13873:13873 W/System.err]
	at android.os.Looper.loop(Looper.java:223)

[03-06 17:25:02.459 13873:13873 W/System.err]
	at android.os.HandlerThread.run(HandlerThread.java:67)

[03-06 17:25:02.459 13873:13873 W/System.err]
Caused by: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.google.aac.decoder, Format(2, null, null, audio/mp4a-latm, null, -1, en, [-1, -1, -1.0], [2, 44100])

[03-06 17:25:02.459 13873:13873 W/System.err]
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:867)

[03-06 17:25:02.459 13873:13873 W/System.err]
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:561)

[03-06 17:25:02.459 13873:13873 W/System.err]
	... 9 more

[03-06 17:25:02.460 13873:13873 W/System.err]
Caused by: android.media.MediaCodec$CodecException: Error 0xfffffc0e

[03-06 17:25:02.460 13873:13873 W/System.err]
	at android.media.MediaCodec.native_configure(Native Method)

[03-06 17:25:02.460 13873:13873 W/System.err]
	at android.media.MediaCodec.configure(MediaCodec.java:2127)

[03-06 17:25:02.460 13873:13873 W/System.err]
	at android.media.MediaCodec.configure(MediaCodec.java:2043)

[03-06 17:25:02.460 13873:13873 W/System.err]
	at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.configureCodec(MediaCodecAudioRenderer.java:471)

[03-06 17:25:02.460 13873:13873 W/System.err]
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:928)

[03-06 17:25:02.460 13873:13873 W/System.err]
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:860)

[03-06 17:25:02.460 13873:13873 W/System.err]
	... 10 more

[03-06 17:25:02.461 13873:13873 D/CompatibilityChangeReporter]
Compat change id reported: 147798919; UID 10159; state: DISABLED

[03-06 17:25:02.502 13873:13873 I/ExoPlayerImpl]
Release 345176b [ExoPlayerLib/2.11.8] [phhgsi_a64_ab, Phh-Treble vanilla, unknown, 30] [goog.exo.core, goog.exo.mediasession]

[03-06 17:25:02.546 13873:13873 W/MessageQueue]
Handler (android.os.Handler) {17f8ad6} sending message to a Handler on a dead thread
java.lang.IllegalStateException: Handler (android.os.Handler) {17f8ad6} sending message to a Handler on a dead thread
	at android.os.MessageQueue.enqueueMessage(MessageQueue.java:560)
	at android.os.Handler.enqueueMessage(Handler.java:778)
	at android.os.Handler.sendMessageAtTime(Handler.java:727)
	at android.os.Handler.sendMessageDelayed(Handler.java:697)
	at android.os.Handler.sendMessage(Handler.java:635)
	at android.os.Message.sendToTarget(Message.java:468)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.stop(ExoPlayerImplInternal.java:210)
	at com.google.android.exoplayer2.ExoPlayerImpl.stop(ExoPlayerImpl.java:425)
	at com.google.android.exoplayer2.SimpleExoPlayer.stop(SimpleExoPlayer.java:1283)
	at com.google.android.exoplayer2.BasePlayer.stop(BasePlayer.java:80)
	at org.schabi.newpipe.player.Player.destroyPlayer(Player.java:757)
	at org.schabi.newpipe.player.Player.destroy(Player.java:786)
	at org.schabi.newpipe.player.MainPlayer.onDestroy(MainPlayer.java:193)
	at android.app.ActivityThread.handleStopService(ActivityThread.java:4349)
	at android.app.ActivityThread.access$1900(ActivityThread.java:237)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1956)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7660)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

[03-06 17:25:02.546 13873:13873 I/ExoPlayerImpl]
Release 345176b [ExoPlayerLib/2.11.8] [phhgsi_a64_ab, Phh-Treble vanilla, unknown, 30] [goog.exo.core, goog.exo.mediasession]

[03-06 17:25:02.549 13873:13873 W/Player]
Broadcast receiver already unregistered: Receiver not registered: org.schabi.newpipe.player.Player$3@6d62994


```

**Comment by assoc** [comment]
#1746, #1747 and #1749 are likely related to the same issue

**Comment by phhusson** [comment]
What device? vndk?

**Comment by assoc** [comment]
Motorola Moto G7 Play, "ro.vndk.version"=29
Flashed from latest vendor Android 10 image to v300.l, v300.m and then v301.

**Comment by phhusson** [comment]
k problem found, https://github.com/phhusson/platform_frameworks_av/commit/624cfc90b8bedb024f289772960f3cd7072fa940
There should be a new release tomorrow with this fix.

**Comment by assoc** [comment]
NewPipe, Slide and TotalCommander m4a playback (was broken too) are fixed in v302.
