### ISSUE TITLE
On AOSP 11.0 v303 uncertified device > AOSP 11.0 v302 works fine

### ISSUE THREAD

**Issue by mschabhuettl** [phhusson/treble_experimentations#1784]
When I flash AOSP 11.0 v303 and want to setup my phone, the system is detected as an uncertified device. Using AOSP 11.0 v302 everyting works fine on inital setup.

**Comment by haruki-taka8** [comment]
I had the same problem and [this XDA tutorial](https://www.xda-developers.com/how-to-fix-device-not-certified-by-google-error/) fixed it.

In short:
- Visit [Google's Device Registration Page](https://www.google.com/android/uncertified/)
- Get your device's Google Service Framework Android ID by:
```
adb root
adb shell 'sqlite3 /data/data/com.google.android.gsf/databases/gservices.db \ 
    "select * from main where name = "android_id";"'
```
- Enter the ID into the site and register
- Wait for a few minutes (5 is enough)

**Comment by KatoTempest** [comment]
I registered it, from device id and it didn't work, but when I use adb sae error message
`
C:\Users\Licht\Desktop\ahaha\platform-tools_r30.0.5-windows\platform-tools>adb shell 'sqlite3 /data/data/com.google.android.gsf/databases/gservices.db \
    "select * from main where name = "android_id";"'/system/bin/sh: no closing quote`

**Comment by haruki-taka8** [comment]
@KatoTempest Glad it worked for you in the end.

Anyways, this is a clearer and easier way to access the ID while avoiding most syntax errors. Only enter the bolded text.

<pre>
> <b>adb root</b>
> <b>adb shell</b>

:/# <b>sqlite3 /data/data/com.google.android.gsf/databases/gservices.db</b>
...
sqlite> <b>select * from main where name = "android_id";</b>
android_id|xxx
</pre>

**Comment by lss4** [comment]
It seems I can't even sign in via microG. Got this logcat similar to many issues found on microG's issue tracker (links redacted as it might contain sensitive info).

```
04-11 09:17:35.827 18182 20755 D GmsHttpFormClient: -- Request --
04-11 09:17:35.827 18182 20755 D GmsHttpFormClient:
04-11 09:17:36.696 18182 20755 W GmsAuthLoginBrowser: onException
04-11 09:17:36.696 18182 20755 W GmsAuthLoginBrowser: java.io.IOException: Error=ServerError
04-11 09:17:36.696 18182 20755 W GmsAuthLoginBrowser: 	at org.microg.gms.common.HttpFormClient.request(HttpFormClient.java:95)
04-11 09:17:36.696 18182 20755 W GmsAuthLoginBrowser: 	at org.microg.gms.common.HttpFormClient$1.run(HttpFormClient.java:198)
04-11 09:17:36.696 18182 20755 W GmsAuthLoginBrowser: 	at java.lang.Thread.run(Thread.java:923)
```

Should say that I also attempted to sign in on my Galaxy Tab S7+ with vanilla gapps, and I got the same Uncertified Device error like you, and it still doesn't work even after registering my device. Not sure if [this](https://github.com/microg/GmsCore/issues/1278) might be related.

**Comment by mschabhuettl** [comment]
The fix described by @phhusson in the [FAQ](https://github.com/phhusson/treble_experimentations/wiki/Frequently-Asked-Questions-%28FAQ%29#how-to-bypass-certified-device-after-first-boot) works fine for me, but it's still annoying. I flashed the image to system, booted my phone and followed the wizard as far as I could. Then I used the adb method to get my android_id and registered it with Google. After a reboot i finished the installer wizard, logged into Google and everything works for me.
