### ISSUE TITLE
[Sony XZ2] aosp camera does not work

### ISSUE THREAD

**Issue by jamuir** [phhusson/treble_experimentations#181]
**phh-image:**  v25
**aosp-tag:** android-8.1.0_r46

the aosp camera app does not work.  It opens but then just shows a black screen with a camera icon in the middle (see screen-shot).

Pictures can be taken using the Open Camera app, but there is no preview (i.e. you can take pictures, but you just cannot preview what you are taking a picture of).

Logcat excerpt (see file attached below for complete logcat):

```text
09-07 16:44:01.214 D/Camera3-Device( 1138): Set real time priority for request queue thread (tid 4664)
09-07 16:44:01.220 V/CAM_SettingsManager( 4585): listeners: [com.android.camera.app.CameraAppUI@eb9acb3, com.android.camera.ButtonManager@60e159c, com.android.camera.widget.IndicatorIconController@d5acb7a, com.android.camera.settings.SettingObserver$Listener@8d25e89]
09-07 16:44:01.220 V/CAM_SettingsManager( 4585): listeners: [com.android.camera.app.CameraAppUI@eb9acb3, com.android.camera.ButtonManager@60e159c, com.android.camera.widget.IndicatorIconController@d5acb7a, com.android.camera.settings.SettingObserver$Listener@8d25e89, com.android.camera.settings.SettingObserver$Listener@3b546af]
09-07 16:44:01.222 D/CAM_CommandExecutor( 4585): Executing command: com.android.camera.one.v2.commands.ZslPreviewCommand@a304df2 START
09-07 16:44:01.222 D/CAM_CaptureModule( 4585): Ready for capture.
09-07 16:44:01.222 V/CAM_CameraAppUI( 4585): onPreviewStarted
09-07 16:44:01.222 E/camera-hal(  960): camera_device.cpp(3260):makeTemplateMetadata: Unsupported template 5.
09-07 16:44:01.222 I/VendorSomcCamDevSession@3.2-impl(  960): constructDefaultRequestSettings: template 5 is not supported on this camera device
09-07 16:44:01.222 I/Camera3-Device( 1138): createDefaultRequest: template 5 is not supported on this camera device
09-07 16:44:01.223 E/CAM_CommandExecutor( 4585): Exception when executing command: com.android.camera.one.v2.commands.ZslPreviewCommand@a304df2
09-07 16:44:01.223 E/CAM_CommandExecutor( 4585): java.lang.IllegalArgumentException: createDefaultRequest:970: Camera 0: Template ID 5 is invalid or not supported: Invalid argument (-22)
09-07 16:44:01.223 E/CAM_CommandExecutor( 4585):        at android.hardware.camera2.CameraManager.throwAsPublicException(CameraManager.java:650)
09-07 16:44:01.223 E/CAM_CommandExecutor( 4585):        at android.hardware.camera2.impl.ICameraDeviceUserWrapper.createDefaultRequest(ICameraDeviceUserWrapper.java:159)
09-07 16:44:01.223 E/CAM_CommandExecutor( 4585):        at android.hardware.camera2.impl.CameraDeviceImpl.createCaptureRequest(CameraDeviceImpl.java:696)
09-07 16:44:01.223 E/CAM_CommandExecutor( 4585):        at com.android.camera.one.v2.camera2proxy.AndroidCameraDeviceProxy.createCaptureRequest(AndroidCameraDeviceProxy.java:90)
09-07 16:44:01.223 E/CAM_CommandExecutor( 4585):        at com.android.camera.one.v2.camera2proxy.CameraDeviceRequestBuilderFactory.create(CameraDeviceRequestBuilderFactory.java:38)
09-07 16:44:01.223 E/CAM_CommandExecutor( 4585):        at com.android.camera.one.v2.core.RequestTemplate.create(RequestTemplate.java:101)
09-07 16:44:01.223 E/CAM_CommandExecutor( 4585):        at com.android.camera.one.v2.core.RequestTemplate.create(RequestTemplate.java:101)
09-07 16:44:01.223 E/CAM_CommandExecutor( 4585):        at com.android.camera.one.v2.commands.ZslPreviewCommand.createWarmupBurst(ZslPreviewCommand.java:106)
09-07 16:44:01.223 E/CAM_CommandExecutor( 4585):        at com.android.camera.one.v2.commands.ZslPreviewCommand.run(ZslPreviewCommand.java:90)
09-07 16:44:01.223 E/CAM_CommandExecutor( 4585):        at com.android.camera.one.v2.commands.CameraCommandExecutor$CommandRunnable.run(CameraCommandExecutor.java:52)
09-07 16:44:01.223 E/CAM_CommandExecutor( 4585):        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
09-07 16:44:01.223 E/CAM_CommandExecutor( 4585):        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
09-07 16:44:01.223 E/CAM_CommandExecutor( 4585):        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
09-07 16:44:01.223 E/CAM_CommandExecutor( 4585):        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
09-07 16:44:01.223 E/CAM_CommandExecutor( 4585):        at java.lang.Thread.run(Thread.java:764)
09-07 16:44:01.223 E/CAM_CommandExecutor( 4585): Caused by: android.os.ServiceSpecificException: createDefaultRequest:970: Camera 0: Template ID 5 is invalid or not supported: Invalid argument (-22) (code 3)
09-07 16:44:01.223 E/CAM_CommandExecutor( 4585):        at android.os.Parcel.readException(Parcel.java:2019)
09-07 16:44:01.223 E/CAM_CommandExecutor( 4585):        at android.os.Parcel.readException(Parcel.java:1951)
09-07 16:44:01.223 E/CAM_CommandExecutor( 4585):        at android.hardware.camera2.ICameraDeviceUser$Stub$Proxy.createDefaultRequest(ICameraDeviceUser.java:521)
09-07 16:44:01.223 E/CAM_CommandExecutor( 4585):        at android.hardware.camera2.impl.ICameraDeviceUserWrapper.createDefaultRequest(ICameraDeviceUserWrapper.java:157)
09-07 16:44:01.223 E/CAM_CommandExecutor( 4585):        ... 13 more
```

![sc-8034](https://user-images.githubusercontent.com/5332385/45231739-0e09d300-b29b-11e8-8787-813ce947483f.png)

[logcat-aosp-camera.txt](https://github.com/phhusson/treble_experimentations/files/2361834/logcat-aosp-camera.txt)

**Comment by jamuir** [comment]
the same defect is present on the xz1:

```text
09-12 21:49:06.060 D/Camera3-Device( 1295): Set real time priority for request queue thread (tid 8118)
09-12 21:49:06.066 V/CAM_SettingsManager( 8055): listeners: [com.android.camera.app.CameraAppUI@36d08c0, com.android.camera.ButtonManager@9dbacb5, com.android.camera.widget.IndicatorIconController@964cebb, com.android.camera.settings.SettingObserver$Listener@a54316a]
09-12 21:49:06.066 V/CAM_SettingsManager( 8055): listeners: [com.android.camera.app.CameraAppUI@36d08c0, com.android.camera.ButtonManager@9dbacb5, com.android.camera.widget.IndicatorIconController@964cebb, com.android.camera.settings.SettingObserver$Listener@a54316a, com.android.camera.settings.SettingObserver$Listener@f321ef8]
09-12 21:49:06.068 D/CAM_CommandExecutor( 8055): Executing command: com.android.camera.one.v2.commands.ZslPreviewCommand@88b8c2f START
09-12 21:49:06.068 D/CAM_CaptureModule( 8055): Ready for capture.
09-12 21:49:06.068 V/CAM_CameraAppUI( 8055): onPreviewStarted
09-12 21:49:06.068 E/camera-hal( 1060): camera_device.cpp(3088):makeTemplateMetadata: Unsupported template 5.
09-12 21:49:06.068 I/VendorSomcCamDevSession@3.2-impl( 1060): constructDefaultRequestSettings: template 5 is not supported on this camera device
09-12 21:49:06.068 I/Camera3-Device( 1295): createDefaultRequest: template 5 is not supported on this camera device
09-12 21:49:06.069 E/CAM_CommandExecutor( 8055): Exception when executing command: com.android.camera.one.v2.commands.ZslPreviewCommand@88b8c2f
09-12 21:49:06.069 E/CAM_CommandExecutor( 8055): java.lang.IllegalArgumentException: createDefaultRequest:970: Camera 0: Template ID 5 is invalid or not supported: Invalid argument (-22)
09-12 21:49:06.069 E/CAM_CommandExecutor( 8055):        at android.hardware.camera2.CameraManager.throwAsPublicException(CameraManager.java:650)
09-12 21:49:06.069 E/CAM_CommandExecutor( 8055):        at android.hardware.camera2.impl.ICameraDeviceUserWrapper.createDefaultRequest(ICameraDeviceUserWrapper.java:159)
09-12 21:49:06.069 E/CAM_CommandExecutor( 8055):        at android.hardware.camera2.impl.CameraDeviceImpl.createCaptureRequest(CameraDeviceImpl.java:696)
09-12 21:49:06.069 E/CAM_CommandExecutor( 8055):        at com.android.camera.one.v2.camera2proxy.AndroidCameraDeviceProxy.createCaptureRequest(AndroidCameraDeviceProxy.java:90)
09-12 21:49:06.069 E/CAM_CommandExecutor( 8055):        at com.android.camera.one.v2.camera2proxy.CameraDeviceRequestBuilderFactory.create(CameraDeviceRequestBuilderFactory.java:38)
09-12 21:49:06.069 E/CAM_CommandExecutor( 8055):        at com.android.camera.one.v2.core.RequestTemplate.create(RequestTemplate.java:101)
09-12 21:49:06.069 E/CAM_CommandExecutor( 8055):        at com.android.camera.one.v2.core.RequestTemplate.create(RequestTemplate.java:101)
09-12 21:49:06.069 E/CAM_CommandExecutor( 8055):        at com.android.camera.one.v2.commands.ZslPreviewCommand.createWarmupBurst(ZslPreviewCommand.java:106)
09-12 21:49:06.069 E/CAM_CommandExecutor( 8055):        at com.android.camera.one.v2.commands.ZslPreviewCommand.run(ZslPreviewCommand.java:90)
09-12 21:49:06.069 E/CAM_CommandExecutor( 8055):        at com.android.camera.one.v2.commands.CameraCommandExecutor$CommandRunnable.run(CameraCommandExecutor.java:52)
09-12 21:49:06.069 E/CAM_CommandExecutor( 8055):        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
09-12 21:49:06.069 E/CAM_CommandExecutor( 8055):        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
09-12 21:49:06.069 E/CAM_CommandExecutor( 8055):        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
09-12 21:49:06.069 E/CAM_CommandExecutor( 8055):        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
09-12 21:49:06.069 E/CAM_CommandExecutor( 8055):        at java.lang.Thread.run(Thread.java:764)
09-12 21:49:06.069 E/CAM_CommandExecutor( 8055): Caused by: android.os.ServiceSpecificException: createDefaultRequest:970: Camera 0: Template ID 5 is invalid or not supported: Invalid argument (-22) (code 3)
09-12 21:49:06.069 E/CAM_CommandExecutor( 8055):        at android.os.Parcel.readException(Parcel.java:2019)
09-12 21:49:06.069 E/CAM_CommandExecutor( 8055):        at android.os.Parcel.readException(Parcel.java:1951)
09-12 21:49:06.069 E/CAM_CommandExecutor( 8055):        at android.hardware.camera2.ICameraDeviceUser$Stub$Proxy.createDefaultRequest(ICameraDeviceUser.java:521)
09-12 21:49:06.069 E/CAM_CommandExecutor( 8055):        at android.hardware.camera2.impl.ICameraDeviceUserWrapper.createDefaultRequest(ICameraDeviceUserWrapper.java:157)
09-12 21:49:06.069 E/CAM_CommandExecutor( 8055):        ... 13 more
```
Even though Sony does deliberately break stock camera functionality during bootloader unlock (because of their DRM), the aosp camera app does work correctly in non gsi builds (i.e. in full images built using the sony open devices tree).

**Comment by jamuir** [comment]
> Sony open device tree has their own drivers, which don't use DRM-ed part at all, so the comparaison doesn't make much sense

Fair enough.  But I am curious how the stock image is able to pass VTS camera tests.

> BTW did you look at the "drm fix"? I think there has been some for XZ1 and XZ2 now

Unfortunately, there is not much to look at :-)  The drm-fix changes are closed source (they are binary kernel patches).  You can pay a small amount get access to an application that will apply the patches, but I would need access to the patches themselves.

**Comment by phhusson** [comment]
Pie Sony vendors no longer have that stupid Camera DRM lock
