### ISSUE TITLE
[pstar] VoLTE not configurable even after installing IMS APK.

### ISSUE THREAD

**Issue by lss4** [phhusson/treble_experimentations#2031]
GSI: DotOS 5.1.3 (August)
Device: Motorola Edge S/20 Pro (pstar)

My data plan supports 5G. On my previous phone VoLTE can be enabled after installing IMS APK, but not here.

Even after installing IMS APK, VoLTE does not show up in Mobile Networks configuration and the Phone Information secret menu shows VoLTE not provisioned, IMS status unregistered. In this state, the phone still needs to downgrade to 3G signal to make/receive phone calls.

Logcat shows the following messages regarding IMS, which looks like some kind of mismatch.

```
10-08 13:24:26.135  1953  2653 E QMI_FW  : qmi_cci_get_ref: ref count increased 2
10-08 13:24:26.140  1953  2153 E RIL-MOTEXT: qcrilUpdRegRAT, called , rat =7
10-08 13:24:26.149  3554  3742 W hw-Parcel: **** enforceInterface() expected 'vendor.qti.hardware.radio.ims@1.3::IImsRadioIndication' but read 'vendor.qti.hardware.radio.ims@1.2::IImsRadioIndication'
10-08 13:24:26.150  1953  2153 E QMI_FW  : qmi_cci_get_ref: ref count increased 2
10-08 13:24:26.151  3554  3742 W System.err: java.lang.SecurityException: HWBinder invocation to an incorrect interface
10-08 13:24:26.151  3554  3742 W System.err: 	at android.os.HwParcel.enforceInterface(Native Method)
10-08 13:24:26.151  3554  3742 W System.err: 	at vendor.qti.hardware.radio.ims.V1_4.IImsRadioIndication$Stub.onTransact(IImsRadioIndication.java:1327)
10-08 13:24:26.151  3554  3742 E android_os_HwBinder: Uncaught exception!
10-08 13:24:26.152  3554  3742 W hw-Parcel: **** enforceInterface() expected 'vendor.qti.hardware.radio.ims@1.1::IImsRadioIndication' but read 'vendor.qti.hardware.radio.ims@1.0::IImsRadioIndication'
10-08 13:24:26.152  3554  3742 W System.err: java.lang.SecurityException: HWBinder invocation to an incorrect interface
10-08 13:24:26.152  3554  3742 W System.err: 	at android.os.HwParcel.enforceInterface(Native Method)
10-08 13:24:26.152  3554  3742 W System.err: 	at vendor.qti.hardware.radio.ims.V1_4.IImsRadioIndication$Stub.onTransact(IImsRadioIndication.java:1241)
10-08 13:24:26.152  3554  3742 E android_os_HwBinder: Uncaught exception!
```

**Comment by Lesking72** [comment]
Jumping in to say I found the same messages in the logs on my Z4, although I'm having a different issue.
```
10-09 16:14:47.022  3199  3335 W hw-Parcel: **** enforceInterface() expected 'vendor.qti.hardware.radio.ims@1.3::IImsRadioIndication' but read 'vendor.qti.hardware.radio.ims@1.2::IImsRadioIndication'
10-09 16:14:47.023  3199  3335 W System.err:    at vendor.qti.hardware.radio.ims.V1_4.IImsRadioIndication$Stub.onTransact(IImsRadioIndication.java:1327)
10-09 16:14:47.023  3199  3335 W hw-Parcel: **** enforceInterface() expected 'vendor.qti.hardware.radio.ims@1.1::IImsRadioIndication' but read 'vendor.qti.hardware.radio.ims@1.0::IImsRadioIndication'
10-09 16:14:47.023  3199  3335 W System.err:    at vendor.qti.hardware.radio.ims.V1_4.IImsRadioIndication$Stub.onTransact(IImsRadioIndication.java:1241)
```

**Comment by lss4** [comment]
Okay... I think I've found my answer.

Turned out I need to toggle "Phh Treble Settings -> IMS features -> Force the password of 4G Calling setting" to force the VoLTE option appear. After that I just need to do the thing I always need to do whenever I boot the system (toggle VoLTE off then on). After that I get the VoLTE icon and IMS status showing everything's working.

I'm not closing the issue yet, as I suspect something needs to be fixed for the IMS APK as normally the VoLTE option should be visible on its own after installing it and that the environment allows such. Right now it's obviously not the case, as I need to force the option to be visible.

**Comment by lss4** [comment]
Actually I did not have this issue with Razer Phone 2 using Android 11 GSI (Android 10 GSI also works, but a bit more complicated).

VoLTE works well after installing IMS APK and a manual toggle upon boot (a manual toggle is also needed upon losing and regaining the LTE signal, such as Airplane Mode).

The issue I'm having with my Edge S Pro reminds me of a similar situation I had with Razer Phone 2 using Android 9 GSI. At that time, I was able to make VoLTE calls, but it got stuck when hanging up.

With my current phone, looks like receiving SMS is still fine for now, just that the phone still needs to downgrade to 3G signal when making calls and the issue is relatively minor.

PS: The issue persists with the recently released DotOS 5.2 GSI (October build). I'm using the non-vndklite build.

**Comment by lss4** [comment]
Very late bump. The issue is still present on phh-AOSP 12.1 v411 with my device.

IMS doesn't work, and I still can't make calls after forcing the option out. Similar error messages like this exist in the logcat.

```
03-26 22:06:26.017  1875  2010 W hw-Parcel: **** enforceInterface() expected 'vendor.qti.hardware.radio.ims@1.3::IImsRadio' but read 'vendor.qti.hardware.radio.ims@1.4::IImsRadio'
...
03-26 22:07:44.365  1875  1875 W hw-Parcel: **** enforceInterface() expected 'vendor.qti.hardware.radio.ims@1.2::IImsRadio' but read 'vendor.qti.hardware.radio.ims@1.3::IImsRadio'
```

Currently I'm not going to test too much about this as I just clean-flashed the device with this new GSI and I'm still in the middle of putting back my old files and apps.
