### ISSUE TITLE
build repo failing "None: remote origin does not have refs/heads/master"

### ISSUE THREAD

**Issue by xloem** [phhusson/treble_experimentations#2129]
hey i'm new to building
after `repo init` i'm getting this when following the readme (ran with bash -vx to show commands):
```
$ bash -vx ../treble_experimentations/build-rom.sh android-8.1 lineage
module () {  eval `/usr/bin/modulecmd bash $*`
}
#!/bin/bash

rom_fp="$(date +%y%m%d)"
++ date +%y%m%d
+ rom_fp=211228
originFolder="$(dirname "$0")"
++ dirname ../treble_experimentations/build-rom.sh
+ originFolder=../treble_experimentations
mkdir -p release/$rom_fp/
+ mkdir -p release/211228/
set -e
+ set -e

if [ "$#" -le 1 ];then
	echo "Usage: $0 <android-8.1> <carbon|lineage|rr> '# of jobs'"
	exit 0
fi
+ '[' 2 -le 1 ']'
localManifestBranch=$1
+ localManifestBranch=android-8.1
rom=$2
+ rom=lineage

if [ "$release" == true ];then
    [ -z "$version" ] && exit 1
    [ ! -f "$originFolder/release/config.ini" ] && exit 1
fi
+ '[' '' == true ']'

if [ -z "$USER" ];then
	export USER="$(id -un)"
fi
+ '[' -z user ']'
export LC_ALL=C
+ export LC_ALL=C
+ LC_ALL=C

if [[ -n "$3" ]];then
	jobs=$3
else
    if [[ $(uname -s) = "Darwin" ]];then
        jobs=$(sysctl -n hw.ncpu)
    elif [[ $(uname -s) = "Linux" ]];then
        jobs=$(nproc)
    fi
fi
+ [[ -n '' ]]
++ uname -s
+ [[ Linux = \D\a\r\w\i\n ]]
++ uname -s
+ [[ Linux = \L\i\n\u\x ]]
++ nproc
+ jobs=4

#We don't want to replace from AOSP since we'll be applying patches by hand
rm -f .repo/local_manifests/replace.xml
+ rm -f .repo/local_manifests/replace.xml
if [ "$rom" == "carbon" ];then
	repo init -u https://github.com/CarbonROM/android -b cr-6.1
elif [ "$rom" == "lineage15" ];then
	repo init -u https://github.com/LineageOS/android.git -b lineage-15.1
elif [ "$rom" == "lineage16" ];then
	repo init -u https://github.com/LineageOS/android.git -b lineage-16.0
elif [ "$rom" == "rr" ];then
	repo init -u https://github.com/ResurrectionRemix/platform_manifest.git -b pie
fi
+ '[' lineage == carbon ']'
+ '[' lineage == lineage15 ']'
+ '[' lineage == lineage16 ']'
+ '[' lineage == rr ']'

if [ -d .repo/local_manifests ] ;then
	( cd .repo/local_manifests; git fetch; git reset --hard; git checkout origin/$localManifestBranch)
else
	git clone https://github.com/phhusson/treble_manifest .repo/local_manifests -b $localManifestBranch
fi
+ '[' -d .repo/local_manifests ']'
+ cd .repo/local_manifests
+ git fetch
+ git reset --hard
HEAD is now at e13235c Merge pull request #10 from Loggus66/android-8.1
+ git checkout origin/android-8.1
HEAD is now at e13235c Merge pull request #10 from Loggus66/android-8.1

if [ -z "$local_patches" ];then
    if [ -d patches ];then
        ( cd patches; git fetch; git reset --hard; git checkout origin/$localManifestBranch)
    else
        git clone https://github.com/phhusson/treble_patches patches -b $localManifestBranch
    fi
else
    rm -Rf patches
    mkdir patches
    unzip  "$local_patches" -d patches
fi
+ '[' -z '' ']'
+ '[' -d patches ']'
+ cd patches
+ git fetch
+ git reset --hard
HEAD is now at 0d88141 Update to AOSP v23
+ git checkout origin/android-8.1
HEAD is now at 0d88141 Update to AOSP v23

#We don't want to replace from AOSP since we'll be applying patches by hand
rm -f .repo/local_manifests/replace.xml
+ rm -f .repo/local_manifests/replace.xml

repo sync -c -j$jobs --force-sync
+ repo sync -c -j4 --force-sync
Traceback (most recent call last):
  File "/media/3/unihertztitan/treble_experimentations-build/.repo/repo/main.py", line 651, in <module>
    _Main(sys.argv[1:])
  File "/media/3/unihertztitan/treble_experimentations-build/.repo/repo/main.py", line 627, in _Main
    result = run()
  File "/media/3/unihertztitan/treble_experimentations-build/.repo/repo/main.py", line 620, in <lambda>
    run = lambda: repo._Run(name, gopts, argv) or 0
  File "/media/3/unihertztitan/treble_experimentations-build/.repo/repo/main.py", line 286, in _Run
    result = cmd.Execute(copts, cargs)
  File "/media/3/unihertztitan/treble_experimentations-build/.repo/repo/subcmds/sync.py", line 985, in Execute
    self._UpdateManifestProject(opt, mp, manifest_name)
  File "/media/3/unihertztitan/treble_experimentations-build/.repo/repo/subcmds/sync.py", line 896, in _UpdateManifestProject
    partial_clone_exclude=self.manifest.PartialCloneExclude)
  File "/media/3/unihertztitan/treble_experimentations-build/.repo/repo/project.py", line 1170, in Sync_NetworkHalf
    clone_filter=clone_filter, retry_fetches=retry_fetches):
  File "/media/3/unihertztitan/treble_experimentations-build/.repo/repo/project.py", line 2177, in _RemoteFetch
    spec.append(str((u'+%s:' % branch) + remote.ToLocal(branch)))
  File "/media/3/unihertztitan/treble_experimentations-build/.repo/repo/git_config.py", line 657, in ToLocal
    (self.projectname, self.name, rev))
error.GitError: None: remote origin does not have refs/heads/master
```

**Comment by xloem** [comment]
I found different instructions and get this different error:
```

```

**Comment by ponces** [comment]
Did you sync after repo init before anything else??
