### ISSUE TITLE
[Samsung Galaxy XCover5] Error during OTA

### ISSUE THREAD

**Issue by febeslmeisl** [phhusson/treble_experimentations#2289]
When trying to do OTA update on my XCover5 (not sure if specific to this device) after clicking "Download and Install" an error occurs. First analysis from my side follows:

Following selinux errors can be seen in log:
```
04-11 15:45:42.027  4211  4211 E phh-ota : Backing image system_otaphh_a is not mapped
04-11 15:45:44.476  4211  4211 W phh-ota : type=1400 audit(0.0:45754): avc: denied { ioctl } for path="/dev/block/mmcblk0p38" dev="tmpfs" ino=1161 ioctlcmd=0x127a scontext=u:r:phhsu_daemon:s0 tcontext=u:object_r:userdata_block_device:s0 tclass=blk_file permissive=0
04-11 15:45:44.477  4211  4211 E phh-ota : [liblp]bool android::fs_mgr::(anonymous namespace)::GetBlockDeviceInfo(const std::string &, android::fs_mgr::BlockDeviceInfo *)BLKALIGNOFF failed on /dev/block/by-name/userdata: Permission denied
04-11 15:45:44.477  4211  4211 E phh-ota : Could not read partition: /dev/block/by-name/userdata

04-11 16:04:24.297  4574  4574 E phh-ota : [liblp]bool android::fs_mgr::(anonymous namespace)::GetBlockDeviceInfo(const std::string &, android::fs_mgr::BlockDeviceInfo *)BLKALIGNOFF failed on /dev/block/by-name/userdata: Permission denied
04-11 16:04:24.292  4574  4574 W phh-ota : type=1400 audit(0.0:46421): avc: denied { ioctl } for path="/dev/block/mmcblk0p38" dev="tmpfs" ino=1161 ioctlcmd=0x127a scontext=u:r:phhsu_daemon:s0 tcontext=u:object_r:userdata_block_device:s0 tclass=blk_file permissive=0
04-11 16:04:24.292  4574  4574 W phh-ota : type=1300 audit(0.0:46421): arch=c00000b7 syscall=29 success=no exit=-13 a0=6 a1=127a a2=7fff9142fc a3=0 items=0 ppid=2757 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=pts1 ses=4294967295 exe="/system/bin/phh-ota" subj=u:r:phhsu_daemon:s0 key=(null)
```
When booting kernel with selinux permissive `androidboot.selinux=permissive` it goes one step further  but then logcat gives following error:
```
04-23 12:24:38.042  2688  3030 D PHH     : Current value of phh-ota-make svc is running
04-23 12:24:38.056  3036  3036 I phh-ota : type=1400 audit(0.0:566): avc: denied { ioctl } for path="/dev/block/mmcblk0p38" dev="tmpfs" ino=13430 ioctlcmd=0x127a scontext=u:r:phhsu_daemon:s0 tcontext=u:object_r:userdata_block_device:s0 tclass=blk_file permissive=1
04-23 12:24:38.056  3036  3036 W phh-ota : type=1300 audit(0.0:566): arch=c00000b7 syscall=29 success=yes exit=0 a0=6 a1=127a a2=7fc45a11cc a3=0 items=0 ppid=1 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 exe="/system/bin/phh-ota" subj=u:r:phhsu_daemon:s0 key=(null)
04-23 12:24:38.056   305   305 W auditd  : type=1327 audit(0.0:566): proctitle=2F73797374656D2F62696E2F7068682D6F7461006E65772D736C6F74
04-23 12:24:38.056   305   305 W auditd  : type=1320 audit(0.0:566): 
04-23 12:24:38.064    60    60 I kdevtmpfs: type=1400 audit(0.0:567): avc: denied { create } for name="dm-4" scontext=u:r:kernel:s0 tcontext=u:object_r:device:s0 tclass=blk_file permissive=1
04-23 12:24:38.071  3036  3036 I phh-ota : [libfs_mgr]Created logical partition system_otaphh_a on device /dev/block/dm-4
04-23 12:24:38.072   300   315 D vold    : Disk at 253:4 changed
04-23 12:24:38.077     0     0 W [0:      kdevtmpfs:   60] audit: audit_lost=817 audit_rate_limit=5 audit_backlog_limit=64
04-23 12:24:38.077     0     0 E [0:      kdevtmpfs:   60] audit: rate limit exceeded
04-23 12:24:38.089     0     0 I [2:           init:    1] init: Service 'phh-ota-make' (pid 3036) exited with status 255 oneshot service took 2.049000 seconds in background
04-23 12:24:38.089     0     0 I [2:           init:    1] init: Sending signal 9 to service 'phh-ota-make' (pid 3036) process group...
04-23 12:24:38.089     0     0 I [2:           init:    1] libprocessgroup: Successfully killed process cgroup uid 0 pid 3036 in 0ms
04-23 12:24:38.142  2688  3030 E PHH     : New slot created
04-23 12:24:38.143  2688  3030 E PHH     : OTA image extracting
04-23 12:24:38.155  2688  3030 E PHH     : Failed applying OTA image. Error: java.io.FileNotFoundException: /dev/phh-ota: open failed: EACCES (Permission denied)
04-23 12:24:38.155  2688  3030 E PHH     : java.io.FileNotFoundException: /dev/phh-ota: open failed: EACCES (Permission denied)
04-23 12:24:38.155  2688  3030 E PHH     : 	at libcore.io.IoBridge.open(IoBridge.java:575)
04-23 12:24:38.155  2688  3030 E PHH     : 	at java.io.FileOutputStream.<init>(FileOutputStream.java:236)
04-23 12:24:38.155  2688  3030 E PHH     : 	at java.io.FileOutputStream.<init>(FileOutputStream.java:125)
04-23 12:24:38.155  2688  3030 E PHH     : 	at me.phh.treble.app.UpdaterActivity.extractUpdate(UpdaterActivity.kt:455)
04-23 12:24:38.155  2688  3030 E PHH     : 	at me.phh.treble.app.UpdaterActivity.access$extractUpdate(UpdaterActivity.kt:32)
04-23 12:24:38.155  2688  3030 E PHH     : 	at me.phh.treble.app.UpdaterActivity$downloadUpdate$2.invoke(UpdaterActivity.kt:324)
04-23 12:24:38.155  2688  3030 E PHH     : 	at me.phh.treble.app.UpdaterActivity$downloadUpdate$2.invoke(UpdaterActivity.kt:32)
04-23 12:24:38.155  2688  3030 E PHH     : 	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
04-23 12:24:38.155  2688  3030 E PHH     : Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
04-23 12:24:38.155  2688  3030 E PHH     : 	at libcore.io.Linux.open(Native Method)
04-23 12:24:38.155  2688  3030 E PHH     : 	at libcore.io.ForwardingOs.open(ForwardingOs.java:567)
04-23 12:24:38.155  2688  3030 E PHH     : 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:273)
04-23 12:24:38.155  2688  3030 E PHH     : 	at libcore.io.ForwardingOs.open(ForwardingOs.java:567)
04-23 12:24:38.155  2688  3030 E PHH     : 	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7756)
04-23 12:24:38.155  2688  3030 E PHH     : 	at libcore.io.IoBridge.open(IoBridge.java:561)
04-23 12:24:38.155  2688  3030 E PHH     : 	... 7 more
04-23 12:24:38.196  2688  2688 E PHH     : Device variant is: lineage_arm64_bvS
04-23 12:24:38.196  2688  2688 E PHH     : Security patch date: 2022-03-05
```

Trying to debug with starting phh-ota-make service manually gives following output:
```
:/system/etc/init # /system/bin/phh-ota new-slot
Unmapping backing image returned true
Deleting backing image returned true
Creating system image succeeded
Mapping backing image returned true
blockdev is /dev/block/dm-4
/dev/block/dm-4
blockDev wasn't block dev
```
I guess there are at least two issues:
- selinux policies have to be updated to allow acces to blockdevices (phhsu_daemon, kernel)
- phh-ota-make fails with mounting block device dm-4, unclear why to me yet

**Comment by phhusson** [comment]
What does `ls -lZ /dev/block/dm-4` say after `phh-ota new-slot`?

**Comment by febeslmeisl** [comment]
```
1|:/data/data # ls -lZ /dev/block/dm-4
brw------- 1 root root u:object_r:dm_device:s0  253,   4 2022-04-23 16:57 /dev/block/dm-4
```

**Comment by phhusson** [comment]
k do `strace -f -o /data/local/tmp/str.txt phh-ota new-slot`; then do `adb pull /data/local/tmp/str.txt` and attach str.txt here

**Comment by febeslmeisl** [comment]
Here ist comes: [str.txt](https://github.com/phhusson/treble_experimentations/files/8547509/str.txt)

**Comment by phhusson** [comment]
Okay, so probably a timing issue, I'll add retries. Thanks.

**Comment by febeslmeisl** [comment]
I will test again, once fix is available. BTW: I couldn't find the source for phh-ota, from which repo is this?

**Comment by phhusson** [comment]
https://github.com/phhusson/device_phh_treble/blob/android-12.0/ota/phh-ota.cpp

**Comment by febeslmeisl** [comment]
Just tested with latest version (derived lineage image) but getting:
```
05-12 16:34:17.832  2750  3594 D PHH     : Current value of phh-ota-make svc is running
05-12 16:34:17.842     0     0 I [0:           init:    1] init: Service 'phh-ota-make' (pid 3597) exited with status 0 oneshot service took 3.519000 seconds in background
05-12 16:34:17.842     0     0 I [0:           init:    1] init: Sending signal 9 to service 'phh-ota-make' (pid 3597) process group...
05-12 16:34:17.842     0     0 I [0:           init:    1] libprocessgroup: Successfully killed process cgroup uid 0 pid 3597 in 0ms
05-12 16:34:17.878   818  1090 W libc    : Access denied finding property "hwc.exynos.vsync_mode"
05-12 16:34:17.878   818  1090 W libc    : Access denied finding property "hwc.exynos.vsync_mode"
05-12 16:34:17.893  1052  1054 D vendor.samsung.hardware.thermal@1.0-service: timer callback!
05-12 16:34:17.893   818  1090 W libc    : Access denied finding property "hwc.exynos.vsync_mode"
05-12 16:34:17.894   818  1090 W libc    : Access denied finding property "hwc.exynos.vsync_mode"
05-12 16:34:17.904     0     0 I [1:  POSIX timer 0: 1054] s2mu106_get_temperature: temperature (370)
05-12 16:34:17.910   818  1090 W libc    : Access denied finding property "hwc.exynos.vsync_mode"
05-12 16:34:17.910   818  1090 W libc    : Access denied finding property "hwc.exynos.vsync_mode"
05-12 16:34:17.933  2750  3594 E PHH     : New slot created
05-12 16:34:17.933  2750  3594 E PHH     : OTA image extracting
05-12 16:34:17.938  2750  3594 E PHH     : Failed applying OTA image. Error: java.io.FileNotFoundException: /dev/phh-ota: open failed: EACCES (Permission denied)
05-12 16:34:17.938  2750  3594 E PHH     : java.io.FileNotFoundException: /dev/phh-ota: open failed: EACCES (Permission denied)
05-12 16:34:17.938  2750  3594 E PHH     :      at libcore.io.IoBridge.open(IoBridge.java:575)
05-12 16:34:17.938  2750  3594 E PHH     :      at java.io.FileOutputStream.<init>(FileOutputStream.java:236)
05-12 16:34:17.938  2750  3594 E PHH     :      at java.io.FileOutputStream.<init>(FileOutputStream.java:125)
05-12 16:34:17.938  2750  3594 E PHH     :      at me.phh.treble.app.UpdaterActivity.extractUpdate(UpdaterActivity.kt:455)
05-12 16:34:17.938  2750  3594 E PHH     :      at me.phh.treble.app.UpdaterActivity.access$extractUpdate(UpdaterActivity.kt:32)
05-12 16:34:17.938  2750  3594 E PHH     :      at me.phh.treble.app.UpdaterActivity$downloadUpdate$2.invoke(UpdaterActivity.kt:324)
05-12 16:34:17.938  2750  3594 E PHH     :      at me.phh.treble.app.UpdaterActivity$downloadUpdate$2.invoke(UpdaterActivity.kt:307)
05-12 16:34:17.938  2750  3594 E PHH     :      at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
05-12 16:34:17.938  2750  3594 E PHH     : Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
05-12 16:34:17.938  2750  3594 E PHH     :      at libcore.io.Linux.open(Native Method)
05-12 16:34:17.938  2750  3594 E PHH     :      at libcore.io.ForwardingOs.open(ForwardingOs.java:567)
05-12 16:34:17.938  2750  3594 E PHH     :      at libcore.io.BlockGuardOs.open(BlockGuardOs.java:273)
05-12 16:34:17.938  2750  3594 E PHH     :      at libcore.io.ForwardingOs.open(ForwardingOs.java:567)
05-12 16:34:17.938  2750  3594 E PHH     :      at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7756)
05-12 16:34:17.938  2750  3594 E PHH     :      at libcore.io.IoBridge.open(IoBridge.java:561)
05-12 16:34:17.938  2750  3594 E PHH     :      ... 7 more
05-12 16:34:17.974  2750  2750 E PHH     : Device variant is: lineage_arm64_bvS
05-12 16:34:17.975  2750  2750 E PHH     : Security patch date: 2022-05-05
```

but /dev/phh-ota is now there:
```
130|phhgsi_arm64_ab:/dev $ ls -al phh-ota
brw------- 1 root root 253,   4 2022-05-12 16:34 phh-ota
```
Still some timing/permissions issue left?

**Comment by febeslmeisl** [comment]
Did some further test with new update, and found probably found the root cause of the EACCES issue: there are another two permission issues with selinux, see below:

```
07-23 12:50:43.367   297   297 W auditd  : type=1327 audit(0.0:61133): proctitle="system_server"
07-23 12:50:43.367   297   297 W auditd  : type=1320 audit(0.0:61133): 
07-23 12:50:43.371    60    60 W kdevtmpfs: type=1400 audit(0.0:61134): avc: denied { create } for name="dm-4" scontext=u:r:kernel:s0 tcontext=u:object_r:device:s0 tclass=blk_file permissive=0
07-23 12:50:43.378   300   313 D vold    : Disk at 253:4 changed
07-23 12:50:43.378  6327  6327 I phh-ota : [libfs_mgr]Created logical partition system_otaphh_a on device /dev/block/dm-4
```
and

```
07-23 12:50:44.383  6327  6327 W phh-ota : type=1400 audit(0.0:61166): avc: denied { setattr } for name="phh-ota" dev="tmpfs" ino=61734 scontext=u:r:phhsu_daemon:s0 tcontext=u:object_r:device:s0 tclass=blk_file permissive=0
07-23 12:50:44.383  6327  6327 W phh-ota : type=1300 audit(0.0:61166): arch=c00000b7 syscall=53 success=no exit=-13 a0=ffffff9c a1=5cdbf72c80 a2=1b4 a3=0 items=1 ppid=1 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 exe="/system/bin/phh-ota" subj=u:r:phhsu_daemon:s0 key=(null)
07-23 12:50:44.383   297   297 W auditd  : type=1302 audit(0.0:61166): item=0 name="/dev/phh-ota" inode=61734 dev=00:10 mode=060600 ouid=0 ogid=0 rdev=fd:04 obj=u:object_r:device:s0 nametype=NORMAL cap_fp=0000000000000000 cap_fi=0000000000000000 cap_fe=0 cap_fver=0
07-23 12:50:44.383   297   297 W auditd  : type=1327 audit(0.0:61166): proctitle=2F73797374656D2F62696E2F7068682D6F7461006E65772D736C6F74
07-23 12:50:44.383   297   297 W auditd  : type=1320 audit(0.0:61166): 
07-23 12:50:44.468  2938  6323 E PHH     : New slot created
07-23 12:50:44.468  2938  6323 E PHH     : OTA image extracting
07-23 12:50:44.477  2938  6323 E PHH     : Failed applying OTA image. Error: java.io.FileNotFoundException: /dev/phh-ota: open failed: EACCES (Permission denied)
07-23 12:50:44.477  2938  6323 E PHH     : java.io.FileNotFoundException: /dev/phh-ota: open failed: EACCES (Permission denied)
07-23 12:50:44.477  2938  6323 E PHH     : 	at libcore.io.IoBridge.open(IoBridge.java:575)
07-23 12:50:44.477  2938  6323 E PHH     : 	at java.io.FileOutputStream.<init>(FileOutputStream.java:236)
07-23 12:50:44.477  2938  6323 E PHH     : 	at java.io.FileOutputStream.<init>(FileOutputStream.java:125)
```
Probably that why new block device /dev/phh-ota can't be written to?

**Comment by febeslmeisl** [comment]
Short update on this, I patched the selinux Policy (see attached patch below) and rebuild/flashed image with my own controlled ota.json-URL for testing. Now trying an ota update then "avc: denied" messages disappeared and /dev/phh-ota is now writeable for system group (this seemed to have worked):

```
phhgsi_arm64_ab:/ $ ls -lZ /dev/phh-ota
brw-rw-r-- 1 root system u:object_r:device:s0  253,   4 2022-08-02 09:44 /dev/phh-ota
phhgsi_arm64_ab:/ $ ls -lZ /dev/block/dm-4
brw------- 1 root root u:object_r:dm_device:s0  253,   4 2022-08-02 09:44 /dev/block/dm-4
```
while line 85/86 of https://github.com/phhusson/device_phh_treble/blob/android-12.0/ota/phh-ota.cpp seem to had no effect:

```
const char *dstContext = "u:object_r:phhota_dev:s0";
setxattr("/dev/phh-ota", "security.selinux", dstContext, strlen(dstContext), 0); 
```

[0007-Fixed-OTA-permissions-for-XCover5.zip](https://github.com/phhusson/treble_experimentations/files/9240215/0007-Fixed-OTA-permissions-for-XCover5.zip)  -> (Feel free to add as PullRequest, if you don't see any security issues with this)

Still there is `open failed: EACCES (Permission denied)` error:

```
08-02 09:40:31.223  2880  4378 D PHH     : Current value of phh-ota-make svc is running
08-02 09:40:31.235   301   316 D vold    : Disk at 253:4 changed
08-02 09:40:31.236  4382  4382 I phh-ota : [libfs_mgr]Created logical partition system_otaphh_a on device /dev/block/dm-4
08-02 09:40:31.324  2880  4378 E PHH     : New slot created
08-02 09:40:31.324  2880  4378 E PHH     : OTA image extracting
08-02 09:40:31.328  2880  4378 E PHH     : Failed applying OTA image. Error: java.io.FileNotFoundException: /dev/phh-ota: open failed: EACCES (Permission denied)
08-02 09:40:31.328  2880  4378 E PHH     : java.io.FileNotFoundException: /dev/phh-ota: open failed: EACCES (Permission denied)
08-02 09:40:31.328  2880  4378 E PHH     : 	at libcore.io.IoBridge.open(IoBridge.java:575)
08-02 09:40:31.328  2880  4378 E PHH     : 	at java.io.FileOutputStream.<init>(FileOutputStream.java:236)
08-02 09:40:31.328  2880  4378 E PHH     : 	at java.io.FileOutputStream.<init>(FileOutputStream.java:125)
08-02 09:40:31.328  2880  4378 E PHH     : 	at me.phh.treble.app.UpdaterActivity.extractUpdate(UpdaterActivity.kt:455)
08-02 09:40:31.328  2880  4378 E PHH     : 	at me.phh.treble.app.UpdaterActivity.access$extractUpdate(UpdaterActivity.kt:32)
08-02 09:40:31.328  2880  4378 E PHH     : 	at me.phh.treble.app.UpdaterActivity$downloadUpdate$2.invoke(UpdaterActivity.kt:324)
08-02 09:40:31.328  2880  4378 E PHH     : 	at me.phh.treble.app.UpdaterActivity$downloadUpdate$2.invoke(UpdaterActivity.kt:307)
08-02 09:40:31.328  2880  4378 E PHH     : 	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
08-02 09:40:31.328  2880  4378 E PHH     : Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
08-02 09:40:31.328  2880  4378 E PHH     : 	at libcore.io.Linux.open(Native Method)
08-02 09:40:31.328  2880  4378 E PHH     : 	at libcore.io.ForwardingOs.open(ForwardingOs.java:567)
08-02 09:40:31.328  2880  4378 E PHH     : 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:273)
08-02 09:40:31.328  2880  4378 E PHH     : 	at libcore.io.ForwardingOs.open(ForwardingOs.java:567)
08-02 09:40:31.328  2880  4378 E PHH     : 	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7756)
08-02 09:40:31.328  2880  4378 E PHH     : 	at libcore.io.IoBridge.open(IoBridge.java:561)
08-02 09:40:31.328  2880  4378 E PHH     : 	... 7 more
```
Still not clear to me what's is causing this, but also a simple block read is not possible
```
phhgsi_arm64_ab:/ $ blockdev --getsize64 /dev/phh-ota
blockdev: /dev/phh-ota: Permission denied
```

**Comment by febeslmeisl** [comment]
And finally got it working with another selinux patch, see below. :)

But this seems more a workaround to a conceptional issue to be discussed: 
The root cause for needing this patch is, that  [phh-ota.cpp](https://github.com/phhusson/device_phh_treble/blob/android-12.0/ota/phh-ota.cpp)'s line
`setxattr("/dev/phh-ota", "security.selinux", dstContext, strlen(dstContext), 0);` (already mention in previous post)
is blocked by kernel. I did some deep dive to samsung (XCover5) kernel sources (Kernel\security\commoncap.c -> `int cap_inode_setxattr(...)`) a saw that for setting xattr starting with "security" prefix capability CAP_SYS_ADMIN is required (maybe for good reason, because this lets the app in question change security attributes at runtime). But granting CAP_SYS_ADMIN to phhsu_daemon seems perhaps overkill and even more dangerous than granting access for system_app on genenic `device:blk_file` instead of just special `phhota_dev:blk_file`. Not sure on this, **any comments welcome**... Maybe there also a chance of directly setting/inheriting security.selinux attribute during node creation with less permissions? 

I think this is not XCover5 specific, but can affect all kernels that have this security restriction on extended attributes prefixed with "security".

Here the patch mention above that fixed OTA on XCover 5 (in combination with [patch ](https://github.com/phhusson/treble_experimentations/files/9240215/0007-Fixed-OTA-permissions-for-XCover5.zip) of previous post):
```
diff --git a/sepolicy/phh.te b/sepolicy/phh.te
index 009b1a6..2b24339 100644
--- a/sepolicy/phh.te
+++ b/sepolicy/phh.te
@@ -2,7 +2,11 @@ type phhota_dev, dev_type, bdev_type;
 typeattribute phhota_dev mlstrustedobject;
 
 allow phhsu_daemon phhota_dev:blk_file rw_file_perms;
+allow phhsu_daemon device:blk_file rw_file_perms;
+
 allow system_app phhota_dev:blk_file rw_file_perms;
+allow system_app device:blk_file rw_file_perms;
+
 allow kernel phhsu_daemon:fd use;
 
 allow phhsu_daemon gsi_data_file:file ioctl;
-- 
```
It's not tested yet if line for phhsu_daemon is also required or just adding it for system_app would be sufficient (phhota_dev lines might be not used in this case).

**Disclaimer**: This whole analysis in not completely confirmed yet, since 
- the most current samsung kernel that is installed as binary on my device is not available to me in source code (yet)
- the AVC denial for setxattr seems not to be logged explicitly, so this is just a guess that the discussed branch in kernel code is actually hit, and not something different preventing `security.selinux` to be set to` u:object_r:phhota_dev:s0`

But overall it seem to make sense now, because, when running `phh-ota new-slot` manually as super user within strace (see [this post ](https://github.com/phhusson/treble_experimentations/issues/2289#issuecomment-1107521132)above) xattribute has probably been set correctly and so it went through in this case, but not when running as phhsu_deamon (started from updater app).

Please let me know your opinion on the raised question regarding device security for the system update process...
