### ISSUE TITLE
Unable to set screen lock

### ISSUE THREAD

**Issue by n07w3n** [phhusson/treble_experimentations#2321]
Hello,
I'm can't set pattern, pin, password or fingerprint as a lock screen.
The settings app crashes after set any lock screen (except swipe)

**To Reproduce**
1. Go to 'Settings'
2. Click on 'Security', after 'Screen Lock'
3. Try set a screen lock
4. Settings crash and close

I really like this GSI, it's awesome and i hope solve this issue.

 - Device: Samsumg A10S (a107m)
 - Build Flavor: system-squeak-arm32_binder64-ab-gapps.img.xz]
 - Version: V413

I followed these instructions (forum.xda-developers.com/t/guide-a107m-bl-unlock-twrp-roms-and-magisk.4360391) to unlock bootloader and flash the GSI using TWRP (no magisk).
I already tried flash vanilla version and LineageOS too

**Logcat error**

```
--------- beginning of crash
05-13 12:06:31.574  5538  5589 E AndroidRuntime: FATAL EXCEPTION: AsyncTask #3
05-13 12:06:31.574  5538  5589 E AndroidRuntime: Process: com.android.settings, PID: 5538
05-13 12:06:31.574  5538  5589 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
05-13 12:06:31.574  5538  5589 E AndroidRuntime: 	at android.os.AsyncTask$4.done(AsyncTask.java:415)
05-13 12:06:31.574  5538  5589 E AndroidRuntime: 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
05-13 12:06:31.574  5538  5589 E AndroidRuntime: 	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
05-13 12:06:31.574  5538  5589 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
05-13 12:06:31.574  5538  5589 E AndroidRuntime: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
05-13 12:06:31.574  5538  5589 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
05-13 12:06:31.574  5538  5589 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
05-13 12:06:31.574  5538  5589 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:920)
05-13 12:06:31.574  5538  5589 E AndroidRuntime: Caused by: java.lang.IllegalStateException: Fail to enroll user password when creating SP for user 0
05-13 12:06:31.574  5538  5589 E AndroidRuntime: 	at android.os.Parcel.createExceptionOrNull(Parcel.java:2433)
05-13 12:06:31.574  5538  5589 E AndroidRuntime: 	at android.os.Parcel.createException(Parcel.java:2409)
05-13 12:06:31.574  5538  5589 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:2392)
05-13 12:06:31.574  5538  5589 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:2334)
05-13 12:06:31.574  5538  5589 E AndroidRuntime: 	at com.android.internal.widget.ILockSettings$Stub$Proxy.setLockCredential(ILockSettings.java:1237)
05-13 12:06:31.574  5538  5589 E AndroidRuntime: 	at com.android.internal.widget.LockPatternUtils.setLockCredential(LockPatternUtils.java:695)
05-13 12:06:31.574  5538  5589 E AndroidRuntime: 	at com.android.settings.password.ChooseLockPassword$SaveAndFinishWorker.saveAndVerifyInBackground(ChooseLockPassword.java:1015)
05-13 12:06:31.574  5538  5589 E AndroidRuntime: 	at com.android.settings.password.SaveChosenLockWorkerBase$Task.doInBackground(SaveChosenLockWorkerBase.java:135)
05-13 12:06:31.574  5538  5589 E AndroidRuntime: 	at com.android.settings.password.SaveChosenLockWorkerBase$Task.doInBackground(SaveChosenLockWorkerBase.java:131)
05-13 12:06:31.574  5538  5589 E AndroidRuntime: 	at android.os.AsyncTask$3.call(AsyncTask.java:394)
05-13 12:06:31.574  5538  5589 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
05-13 12:06:31.574  5538  5589 E AndroidRuntime: 	... 4 more
05-13 12:06:31.574  5538  5589 E AndroidRuntime: Caused by: android.os.RemoteException: Remote stack trace:
05-13 12:06:31.574  5538  5589 E AndroidRuntime: 	at com.android.server.locksettings.SyntheticPasswordManager.createPasswordBasedSyntheticPassword(SyntheticPasswordManager.java:781)
05-13 12:06:31.574  5538  5589 E AndroidRuntime: 	at com.android.server.locksettings.LockSettingsService.initializeSyntheticPasswordLocked(LockSettingsService.java:2840)
05-13 12:06:31.574  5538  5589 E AndroidRuntime: 	at com.android.server.locksettings.LockSettingsService.setLockCredentialInternal(LockSettingsService.java:1726)
05-13 12:06:31.574  5538  5589 E AndroidRuntime: 	at com.android.server.locksettings.LockSettingsService.setLockCredential(LockSettingsService.java:1644)
05-13 12:06:31.574  5538  5589 E AndroidRuntime: 	at com.android.internal.widget.ILockSettings$Stub.onTransact(ILockSettings.java:537)
```

**Comment by n07w3n** [comment]
No magisk

**Comment by phhusson** [comment]
k, get me the result of `getprop |grep keymaster` and the result of `mount`

**Comment by n07w3n** [comment]
```
[init.svc.vendor.keymaster-3-0-trustonic]: [running]
[init.svc.wait_for_keymaster]: [stopped]
[ro.keymaster.brn]: [Android]
[ro.keymaster.mod]: [AOSP on ARM32]
[ro.keymaster.xxx.release]: [11.0.0]
[ro.keymaster.xxx.security_patch]: [2022-02-01]
```

and

```
tmpfs on /dev type tmpfs (rw,seclabel,nosuid,relatime,size=916332k,nr_inodes=229083,mode=755)
devpts on /dev/pts type devpts (rw,seclabel,relatime,mode=600,ptmxmode=000)
proc on /proc type proc (rw,relatime,gid=3009,hidepid=2)
sysfs on /sys type sysfs (rw,seclabel,relatime)
selinuxfs on /sys/fs/selinux type selinuxfs (rw,relatime)
tmpfs on /mnt type tmpfs (rw,seclabel,nosuid,nodev,noexec,relatime,size=916332k,nr_inodes=229083,mode=755,gid=1000)
/dev/block/mmcblk0p35 on / type ext4 (ro,seclabel,nodev,relatime)
/dev/block/mmcblk0p33 on /vendor type ext4 (ro,seclabel,relatime)
tmpfs on /apex type tmpfs (rw,seclabel,nosuid,nodev,noexec,relatime,size=916332k,nr_inodes=229083,mode=755)
tmpfs on /linkerconfig type tmpfs (rw,seclabel,nosuid,nodev,noexec,relatime,size=916332k,nr_inodes=229083,mode=755)
tmpfs on /mnt/installer type tmpfs (rw,seclabel,nosuid,nodev,noexec,relatime,size=916332k,nr_inodes=229083,mode=755,gid=1000)
tmpfs on /mnt/androidwritable type tmpfs (rw,seclabel,nosuid,nodev,noexec,relatime,size=916332k,nr_inodes=229083,mode=755,gid=1000)
/dev/block/mmcblk0p35 on /apex/com.android.adbd type ext4 (ro,seclabel,relatime)
/dev/block/mmcblk0p35 on /apex/com.android.apex.cts.shim type ext4 (ro,seclabel,relatime)
/dev/block/mmcblk0p35 on /apex/com.android.appsearch type ext4 (ro,seclabel,relatime)
/dev/block/mmcblk0p35 on /apex/com.android.art type ext4 (ro,seclabel,relatime)
/dev/block/mmcblk0p35 on /apex/com.android.cellbroadcast type ext4 (ro,seclabel,relatime)
/dev/block/mmcblk0p35 on /apex/com.android.conscrypt type ext4 (ro,seclabel,relatime)
/dev/block/mmcblk0p35 on /apex/com.android.extservices type ext4 (ro,seclabel,relatime)
/dev/block/mmcblk0p35 on /apex/com.android.i18n type ext4 (ro,seclabel,relatime)
/dev/block/mmcblk0p35 on /apex/com.android.ipsec type ext4 (ro,seclabel,relatime)
/dev/block/mmcblk0p35 on /apex/com.android.media type ext4 (ro,seclabel,relatime)
/dev/block/mmcblk0p35 on /apex/com.android.media.swcodec type ext4 (ro,seclabel,relatime)
/dev/block/mmcblk0p35 on /apex/com.android.mediaprovider type ext4 (ro,seclabel,relatime)
/dev/block/mmcblk0p35 on /apex/com.android.neuralnetworks type ext4 (ro,seclabel,relatime)
/dev/block/mmcblk0p35 on /apex/com.android.os.statsd type ext4 (ro,seclabel,relatime)
/dev/block/mmcblk0p35 on /apex/com.android.permission type ext4 (ro,seclabel,relatime)
/dev/block/mmcblk0p35 on /apex/com.android.resolv type ext4 (ro,seclabel,relatime)
/dev/block/mmcblk0p35 on /apex/com.android.runtime type ext4 (ro,seclabel,relatime)
/dev/block/mmcblk0p35 on /apex/com.android.scheduling type ext4 (ro,seclabel,relatime)
/dev/block/mmcblk0p35 on /apex/com.android.sdkext type ext4 (ro,seclabel,relatime)
/dev/block/mmcblk0p35 on /apex/com.android.tethering type ext4 (ro,seclabel,relatime)
/dev/block/mmcblk0p35 on /apex/com.android.tzdata type ext4 (ro,seclabel,relatime)
/dev/block/mmcblk0p35 on /apex/com.android.vndk.v32 type ext4 (ro,seclabel,relatime)
/dev/block/mmcblk0p35 on /apex/com.android.vndk.v28 type ext4 (ro,seclabel,relatime)
/dev/block/mmcblk0p35 on /apex/com.android.vndk.v29 type ext4 (ro,seclabel,relatime)
/dev/block/mmcblk0p35 on /apex/com.android.vndk.v30 type ext4 (ro,seclabel,relatime)
/dev/block/mmcblk0p35 on /apex/com.android.vndk.v31 type ext4 (ro,seclabel,relatime)
/dev/block/mmcblk0p35 on /apex/com.android.wifi type ext4 (ro,seclabel,relatime)
none on /dev/blkio type cgroup (rw,nosuid,nodev,noexec,relatime,blkio)
none on /sys/fs/cgroup type cgroup2 (rw,nosuid,nodev,noexec,relatime)
none on /dev/cpuctl type cgroup (rw,nosuid,nodev,noexec,relatime,cpu)
none on /dev/cpuset type cgroup (rw,nosuid,nodev,noexec,relatime,cpuset,noprefix,release_agent=/sbin/cpuset_release_agent)
none on /dev/memcg type cgroup (rw,nosuid,nodev,noexec,relatime,memory)
none on /dev/stune type cgroup (rw,nosuid,nodev,noexec,relatime,schedtune)
tmpfs on /linkerconfig type tmpfs (rw,seclabel,nosuid,nodev,noexec,relatime,size=916332k,nr_inodes=229083,mode=755)
tracefs on /sys/kernel/tracing type tracefs (rw,seclabel,relatime,gid=3012)
none on /config type configfs (rw,nosuid,nodev,noexec,relatime)
binder on /dev/binderfs type binder (rw,relatime,max=1048576,stats=global)
none on /sys/fs/fuse/connections type fusectl (rw,relatime)
bpf on /sys/fs/bpf type bpf (rw,nosuid,nodev,noexec,relatime)
pstore on /sys/fs/pstore type pstore (rw,seclabel,nosuid,nodev,noexec,relatime)
/dev/block/mmcblk0p39 on /data type ext4 (rw,seclabel,nosuid,nodev,noatime,discard,journal_checksum,noauto_da_alloc,resuid=10010,resgid=1065,errors=panic,data=ordered)
/dev/block/mmcblk0p37 on /cache type ext4 (rw,seclabel,nosuid,nodev,noatime,discard,journal_checksum,noauto_da_alloc,errors=panic,data=ordered)
/dev/block/mmcblk0p15 on /mnt/vendor/protect_f type ext4 (rw,seclabel,nosuid,nodev,noatime,discard,journal_checksum,noauto_da_alloc,errors=panic,data=ordered)
/dev/block/mmcblk0p16 on /mnt/vendor/protect_s type ext4 (rw,seclabel,nosuid,nodev,noatime,discard,journal_checksum,noauto_da_alloc,errors=panic,data=ordered)
/dev/block/mmcblk0p13 on /mnt/vendor/nvdata type ext4 (rw,seclabel,nosuid,nodev,noatime,journal_checksum,noauto_da_alloc)
/dev/block/mmcblk0p12 on /mnt/vendor/nvcfg type ext4 (rw,seclabel,nosuid,nodev,noatime,discard,journal_checksum,noauto_da_alloc,errors=panic,data=ordered)
/dev/block/mmcblk0p18 on /mnt/vendor/persist type ext4 (rw,seclabel,nosuid,nodev,noatime,discard,journal_checksum,noauto_da_alloc,errors=panic,data=ordered)
/dev/block/mmcblk0p5 on /mnt/vendor/efs type ext4 (rw,seclabel,nosuid,nodev,noatime,journal_checksum,noauto_da_alloc)
/dev/block/mmcblk0p6 on /efs type ext4 (rw,seclabel,nosuid,nodev,noatime,discard,journal_checksum,noauto_da_alloc,errors=panic,data=ordered)
tmpfs on /storage type tmpfs (rw,seclabel,nosuid,nodev,noexec,relatime,size=916332k,nr_inodes=229083,mode=755,gid=1000)
adb on /dev/usb-ffs/adb type functionfs (rw,relatime)
none on /mnt/phh type tmpfs (rw,seclabel,nodev,relatime,size=916332k,nr_inodes=229083,mode=755)
none on /system/usr/keylayout type tmpfs (rw,seclabel,nodev,relatime,size=916332k,nr_inodes=229083,mode=755)
none on /vendor/lib/libmtk-ril.so type tmpfs (rw,seclabel,nodev,relatime,size=916332k,nr_inodes=229083,mode=755)
none on /system/xbin type tmpfs (rw,seclabel,nodev,relatime,size=916332k,nr_inodes=229083,mode=755)
/dev/block/mmcblk0p18 on /persist type ext4 (rw,seclabel,nosuid,nodev,noatime,discard,journal_checksum,noauto_da_alloc,errors=panic,data=ordered)
/dev/block/mmcblk0p35 on /vendor/etc/usb_audio_policy_configuration.xml type ext4 (ro,seclabel,nodev,relatime)
/dev/block/mmcblk0p39 on /data/user/0 type ext4 (rw,seclabel,nosuid,nodev,noatime,discard,journal_checksum,noauto_da_alloc,resuid=10010,resgid=1065,errors=panic,data=ordered)
tmpfs on /data_mirror type tmpfs (rw,seclabel,nosuid,nodev,noexec,relatime,size=916332k,nr_inodes=229083,mode=700,gid=1000)
/dev/block/mmcblk0p39 on /data_mirror/data_ce/null type ext4 (rw,seclabel,nosuid,nodev,noatime,discard,journal_checksum,noauto_da_alloc,resuid=10010,resgid=1065,errors=panic,data=ordered)
/dev/block/mmcblk0p39 on /data_mirror/data_ce/null/0 type ext4 (rw,seclabel,nosuid,nodev,noatime,discard,journal_checksum,noauto_da_alloc,resuid=10010,resgid=1065,errors=panic,data=ordered)
/dev/block/mmcblk0p39 on /data_mirror/data_de/null type ext4 (rw,seclabel,nosuid,nodev,noatime,discard,journal_checksum,noauto_da_alloc,resuid=10010,resgid=1065,errors=panic,data=ordered)
/dev/block/mmcblk0p39 on /data_mirror/cur_profiles type ext4 (rw,seclabel,nosuid,nodev,noatime,discard,journal_checksum,noauto_da_alloc,resuid=10010,resgid=1065,errors=panic,data=ordered)
/dev/block/mmcblk0p39 on /data_mirror/ref_profiles type ext4 (rw,seclabel,nosuid,nodev,noatime,discard,journal_checksum,noauto_da_alloc,resuid=10010,resgid=1065,errors=panic,data=ordered)
tmpfs on /system/xbin/su type tmpfs (rw,seclabel,nosuid,relatime,size=916332k,nr_inodes=229083,mode=755)
tmpfs on /mnt/phh/xbin/su type tmpfs (rw,seclabel,nosuid,relatime,size=916332k,nr_inodes=229083,mode=755)
/data/media on /mnt/runtime/default/emulated type sdcardfs (rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=1015,multiuser,mask=6,derive_gid,default_normal,unshared_obb)
/data/media on /mnt/runtime/read/emulated type sdcardfs (rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=9997,multiuser,mask=23,derive_gid,default_normal,unshared_obb)
/data/media on /mnt/runtime/write/emulated type sdcardfs (rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=9997,multiuser,mask=7,derive_gid,default_normal,unshared_obb)
/data/media on /mnt/runtime/full/emulated type sdcardfs (rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=9997,multiuser,mask=7,derive_gid,default_normal,unshared_obb)
/dev/fuse on /mnt/user/0/emulated type fuse (rw,lazytime,nosuid,nodev,noexec,noatime,user_id=0,group_id=0,allow_other)
/dev/fuse on /mnt/installer/0/emulated type fuse (rw,lazytime,nosuid,nodev,noexec,noatime,user_id=0,group_id=0,allow_other)
/dev/fuse on /mnt/androidwritable/0/emulated type fuse (rw,lazytime,nosuid,nodev,noexec,noatime,user_id=0,group_id=0,allow_other)
/dev/fuse on /storage/emulated type fuse (rw,lazytime,nosuid,nodev,noexec,noatime,user_id=0,group_id=0,allow_other)
/data/media on /mnt/pass_through/0/emulated type sdcardfs (rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=9997,multiuser,mask=7,derive_gid,default_normal,unshared_obb)
/data/media on /mnt/user/0/emulated/0/Android/data type sdcardfs (rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=1015,multiuser,mask=6,derive_gid,default_normal,unshared_obb)
/data/media on /storage/emulated/0/Android/data type sdcardfs (rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=1015,multiuser,mask=6,derive_gid,default_normal,unshared_obb)
/data/media on /mnt/androidwritable/0/emulated/0/Android/data type sdcardfs (rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=1015,multiuser,mask=6,derive_gid,default_normal,unshared_obb)
/data/media on /mnt/installer/0/emulated/0/Android/data type sdcardfs (rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=1015,multiuser,mask=6,derive_gid,default_normal,unshared_obb)
/data/media on /mnt/user/0/emulated/0/Android/obb type sdcardfs (rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=1015,multiuser,mask=6,derive_gid,default_normal,unshared_obb)
/data/media on /storage/emulated/0/Android/obb type sdcardfs (rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=1015,multiuser,mask=6,derive_gid,default_normal,unshared_obb)
/data/media on /mnt/androidwritable/0/emulated/0/Android/obb type sdcardfs (rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=1015,multiuser,mask=6,derive_gid,default_normal,unshared_obb)
/data/media on /mnt/installer/0/emulated/0/Android/obb type sdcardfs (rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=9997,multiuser,mask=7,derive_gid,default_normal,unshared_obb)
/dev/block/vold/public:179,97 on /mnt/media_rw/E4F3-D63C type vfat (rw,dirsync,nosuid,nodev,noexec,noatime,gid=1023,fmask=0007,dmask=0007,allow_utime=0020,codepage=437,iocharset=iso8859-1,shortname=mixed,utf8,errors=remount-ro)
/mnt/media_rw/E4F3-D63C on /mnt/runtime/default/E4F3-D63C type sdcardfs (rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=1015,mask=6)
/mnt/media_rw/E4F3-D63C on /mnt/runtime/read/E4F3-D63C type sdcardfs (rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=9997,mask=18)
/mnt/media_rw/E4F3-D63C on /mnt/runtime/write/E4F3-D63C type sdcardfs (rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=9997,mask=18)
/mnt/media_rw/E4F3-D63C on /mnt/runtime/full/E4F3-D63C type sdcardfs (rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=9997,mask=7)
/dev/fuse on /mnt/user/0/E4F3-D63C type fuse (rw,lazytime,nosuid,nodev,noexec,noatime,user_id=0,group_id=0,allow_other)
/dev/fuse on /mnt/installer/0/E4F3-D63C type fuse (rw,lazytime,nosuid,nodev,noexec,noatime,user_id=0,group_id=0,allow_other)
/dev/fuse on /mnt/androidwritable/0/E4F3-D63C type fuse (rw,lazytime,nosuid,nodev,noexec,noatime,user_id=0,group_id=0,allow_other)
/dev/fuse on /storage/E4F3-D63C type fuse (rw,lazytime,nosuid,nodev,noexec,noatime,user_id=0,group_id=0,allow_other)
/mnt/media_rw/E4F3-D63C on /mnt/pass_through/0/E4F3-D63C type sdcardfs (rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=9997,mask=7)
```

**Comment by phhusson** [comment]
k, i see nothing wrong. Reboot and grab full logs `adb logcat -b all -d > log.txt`

**Comment by n07w3n** [comment]
[log.txt](https://github.com/phhusson/treble_experimentations/files/8689090/log.txt)

**Comment by n07w3n** [comment]
Any ideia @phhusson ?

**Comment by n07w3n** [comment]
Any idea @phhusson ?

**Comment by n07w3n** [comment]
UPDATE:
I flash the TWRP without the A10s-encryption-disabler.zip file and now the screen lock works good.
