### ISSUE TITLE
[Galaxy A51] FingerprintEnrollIntroduction java.lang.IllegalStateException: There is no saved default color for button

### ISSUE THREAD

**Issue by imMilanxdddd** [phhusson/treble_experimentations#2332]
### Current Behavior:
When enrolling fingerprint on Galaxy A51, the activity crashes.
  
### Describe the bug
FingerprintEnrollIntroduction crashes with exception There is no saved default color for button

Logcat:

```
05-22 13:07:17.456 19550 19550 D AndroidRuntime: Shutting down VM
05-22 13:07:17.457 19550 19550 E AndroidRuntime: FATAL EXCEPTION: main
05-22 13:07:17.457 19550 19550 E AndroidRuntime: Process: com.android.settings, PID: 19550
05-22 13:07:17.457 19550 19550 E AndroidRuntime: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=4, result=-1, data=Intent { (has extras) }} to activity {com.android.settings/com.android.settings.biometrics.fingerprint.FingerprintEnrollIntroduction}: java.lang.IllegalStateException: There is no saved default color for button
05-22 13:07:17.457 19550 19550 E AndroidRuntime:        at android.app.ActivityThread.deliverResults(ActivityThread.java:5368)
05-22 13:07:17.457 19550 19550 E AndroidRuntime:        at android.app.ActivityThread.handleSendResult(ActivityThread.java:5407)
05-22 13:07:17.457 19550 19550 E AndroidRuntime:        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:67)
05-22 13:07:17.457 19550 19550 E AndroidRuntime:        at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
05-22 13:07:17.457 19550 19550 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
05-22 13:07:17.457 19550 19550 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
05-22 13:07:17.457 19550 19550 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2253)
05-22 13:07:17.457 19550 19550 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
05-22 13:07:17.457 19550 19550 E AndroidRuntime:        at android.os.Looper.loopOnce(Looper.java:201)
05-22 13:07:17.457 19550 19550 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:288)
05-22 13:07:17.457 19550 19550 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7870)
05-22 13:07:17.457 19550 19550 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
05-22 13:07:17.457 19550 19550 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
05-22 13:07:17.457 19550 19550 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
05-22 13:07:17.457 19550 19550 E AndroidRuntime: Caused by: java.lang.IllegalStateException: There is no saved default color for button
05-22 13:07:17.457 19550 19550 E AndroidRuntime:        at com.google.android.setupcompat.template.FooterButtonStyleUtils.getButtonDefaultTextCorlor(FooterButtonStyleUtils.java:423)
05-22 13:07:17.457 19550 19550 E AndroidRuntime:        at com.google.android.setupcompat.template.FooterButtonStyleUtils.updateButtonTextDisabledColorWithPartnerConfig(FooterButtonStyleUtils.java:189)
05-22 13:07:17.457 19550 19550 E AndroidRuntime:        at com.google.android.setupcompat.template.FooterBarMixin.updateButtonTextColorWithStates(FooterBarMixin.java:749)
05-22 13:07:17.457 19550 19550 E AndroidRuntime:        at com.google.android.setupcompat.template.FooterBarMixin.access$200(FooterBarMixin.java:66)
05-22 13:07:17.457 19550 19550 E AndroidRuntime:        at com.google.android.setupcompat.template.FooterBarMixin$1.onEnabledChanged(FooterBarMixin.java:110)
05-22 13:07:17.457 19550 19550 E AndroidRuntime:        at com.google.android.setupcompat.template.FooterButton.setEnabled(FooterButton.java:143)
05-22 13:07:17.457 19550 19550 E AndroidRuntime:        at com.android.settings.biometrics.BiometricEnrollIntroduction.onActivityResult(BiometricEnrollIntroduction.java:335)
05-22 13:07:17.457 19550 19550 E AndroidRuntime:        at com.android.settings.biometrics.fingerprint.FingerprintEnrollIntroduction.onActivityResult(FingerprintEnrollIntroduction.java:107)
05-22 13:07:17.457 19550 19550 E AndroidRuntime:        at android.app.Activity.dispatchActivityResult(Activity.java:8385)
05-22 13:07:17.457 19550 19550 E AndroidRuntime:        at android.app.ActivityThread.deliverResults(ActivityThread.java:5361)
05-22 13:07:17.457 19550 19550 E AndroidRuntime:        ... 13 more
05-22 13:07:17.463  5089 19152 W ActivityTaskManager:   Force finishing activity com.android.settings/.biometrics.fingerprint.FingerprintEnrollIntroduction
```

### To Reproduce 
1. Attempt to enroll a fingerprint

### Expected behavior
The fingerprint enrollment should start

### Smartphone (please complete the following information):
 - Device: Samsung Galaxy A51 4G (A515F)
 - Build Flavor: system-squeak-arm64-ab-gapps.img
 - Version V413

**Comment by phhusson** [comment]
https://github.com/phhusson/treble_experimentations/issues/2256#issuecomment-1117898664

**Comment by Iceows** [comment]
I have the same problem on a Huawei P20 lite (ANE-LX1)
