### ISSUE TITLE
[Huawei Mate 10 Pro] Can't connect to the camera

### ISSUE THREAD

**Issue by mrrfv** [phhusson/treble_experimentations#2373]
### Current Behavior:
The camera app fails to show the camera preview (both front and back) after showing the first frame, crashing with the message "Can't connect to the camera". Other apps also show the first frame from the camera and then either crash or freeze.

### To Reproduce
 
1. Install the GSI on a Huawei Mate 10 Pro (BLA-L29)
2. Open the camera app

### Expected behavior
 
The camera preview works, and the app itself lets me take photos and videos.

### Photos
 
**Camera app**
![image](https://user-images.githubusercontent.com/92185687/175782707-a19a13d4-3221-4f5c-a765-d3d04134cbff.png)

**Footej Camera's verbose error message**
![image](https://user-images.githubusercontent.com/92185687/175782712-8e7e2a16-2f5a-44e1-86ef-1eb10261411c.png)

### Smartphone:
 - Device: Huawei Mate 10 Pro
 - Build Flavor: arm64, A/B, vndklite, converted from phh's Superuser to Magisk
 - Version: Android 12, EMUI 9.1.0 (Android 9) vendor

### Additional context

[Stock ROM link](http://update.dbankcdn.com/download/data/pub_13/HWHOTA_hotaMigrate_900_9/ea/v3/ec4b5df145ec4e6991f78a364c364fa9/full/update_full_base.zip) - extract the .zip file and use [Huawei Update Extractor](https://forum.xda-developers.com/t/tool-huawei-update-extractor-updated-v0-9-9-5-open-source-library.2433454/) to unpack system.img and vendor.img from UPDATE.APP.

**Output of `adb shell dumpsys media.camera`:** [dumpsys.txt](https://github.com/phhusson/treble_experimentations/files/8985218/dumpsys.txt)

**Comment by mrrfv** [comment]
A couple of interesting things I've found from the logs:

```
06-26 20:43:10.999  1300  1300 I auditd  : type=1400 audit(0.0:5757): avc: denied { read } for comm="CameraDaemon" name="u:object_r:default_prop:s0" dev="tmpfs" ino=4772 scontext=u:r:hal_camera_default:s0 tcontext=u:object_r:default_prop:s0 tclass=file permissive=0
06-26 20:43:10.999  1300  1300 I auditd  : type=1400 audit(0.0:5758): avc: denied { read } for comm="CameraDaemon" name="u:object_r:default_prop:s0" dev="tmpfs" ino=4772 scontext=u:r:hal_camera_default:s0 tcontext=u:object_r:default_prop:s0 tclass=file permissive=0
06-26 20:43:10.999  1300  1300 I auditd  : type=1400 audit(0.0:5759): avc: denied { read } for comm="CameraDaemon" name="u:object_r:default_prop:s0" dev="tmpfs" ino=4772 scontext=u:r:hal_camera_default:s0 tcontext=u:object_r:default_prop:s0 tclass=file permissive=0
06-26 20:43:10.999  1300  1300 I auditd  : type=1400 audit(0.0:5760): avc: denied { read } for comm="CameraDaemon" name="u:object_r:default_prop:s0" dev="tmpfs" ino=4772 scontext=u:r:hal_camera_default:s0 tcontext=u:object_r:default_prop:s0 tclass=file permissive=0
06-26 20:43:11.003  1300  1300 I auditd  : type=1400 audit(0.0:5761): avc: denied { read } for comm="CameraDaemon" name="u:object_r:default_prop:s0" dev="tmpfs" ino=4772 scontext=u:r:hal_camera_default:s0 tcontext=u:object_r:default_prop:s0 tclass=file permissive=0
06-26 20:43:11.035  1776  1776 D SystemServerTiming: InitBeforeStartServices
06-26 20:43:11.038  1776  1776 I system_server_start: [1,34895,34895]
06-26 20:43:11.038  1776  1776 I SystemServer: Entered the Android system server!



....



06-26 21:33:28.873 19480 19480 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
06-26 21:33:28.873 19480 19480 F DEBUG   : Build fingerprint: 'kirin970/kirin970/kirin970:9/PPR1.180610.011/root201912261806:user/release-keys'
06-26 21:33:28.873 19480 19480 F DEBUG   : Revision: '0'
06-26 21:33:28.873 19480 19480 F DEBUG   : ABI: 'arm64'
06-26 21:33:28.873 19480 19480 F DEBUG   : Timestamp: 2022-06-26 21:33:28.775676347+0200
06-26 21:33:28.873 19480 19480 F DEBUG   : Process uptime: 0s
06-26 21:33:28.873 19480 19480 F DEBUG   : Cmdline: /vendor/bin/CameraDaemon kirin970 BLANC
06-26 21:33:28.873 19480 19480 F DEBUG   : pid: 16141, tid: 19470, name: ispout#2#  >>> /vendor/bin/CameraDaemon <<<
06-26 21:33:28.873 19480 19480 F DEBUG   : uid: 1013
06-26 21:33:28.873 19480 19480 F DEBUG   : signal 11 (SIGSEGV), code 2 (SEGV_ACCERR), fault addr 0x71e9600000
06-26 21:33:28.873 19480 19480 F DEBUG   :     x0  00000000ffffffff  x1  0000000000000000  x2  0000000000000050  x3  000000000000001e
06-26 21:33:28.873 19480 19480 F DEBUG   :     x4  00000071e95cadc8  x5  0000000000000004  x6  0000000000000007  x7  0000000000000055
06-26 21:33:28.873 19480 19480 F DEBUG   :     x8  000000000000002c  x9  000000000000002a  x10 0000000000000019  x11 0000000000005a10
06-26 21:33:28.873 19480 19480 F DEBUG   :     x12 0000000000000001  x13 0000000000000011  x14 0000000000000015  x15 0000000000000034
06-26 21:33:28.873 19480 19480 F DEBUG   :     x16 0000007180b9eea0  x17 000000749cf7bbe0  x18 00000000ffffffba  x19 00000071e95cb600
06-26 21:33:28.873 19480 19480 F DEBUG   :     x20 00000071e95ff600  x21 00000071e9588600  x22 00000071e95ca600  x23 00000071864a3148
06-26 21:33:28.873 19480 19480 F DEBUG   :     x24 00000071864a5010  x25 00000072dc848cf0  x26 0000007180ad91b0  x27 00000071864a5010
06-26 21:33:28.873 19480 19480 F DEBUG   :     x28 00000071864a5010  x29 00000071864a2f70
06-26 21:33:28.873 19480 19480 F DEBUG   :     lr  0000007180b6d5dc  sp  00000071864a2f70  pc  0000007180b6d610  pst 0000000080000000
06-26 21:33:28.873 19480 19480 F DEBUG   : backtrace:
06-26 21:33:28.873 19480 19480 F DEBUG   :       #00 pc 0000000000013610  /vendor/lib64/libSmartAE.so (android::SmartAE::Init(char const*)+840) (BuildId: bb95727f20e8dc1d07081d616d47a71cfa8a5301)
06-26 21:33:28.873 19480 19480 F DEBUG   :       #01 pc 0000000000015500  /vendor/lib64/libSmartAE.so (initSmartAEAlgo+68) (BuildId: bb95727f20e8dc1d07081d616d47a71cfa8a5301)
06-26 21:33:28.873 19480 19480 F DEBUG   :       #02 pc 00000000002aaeb0  /vendor/lib64/libcamera_algo.so (android::SmartAEDLibLoader::LINK_smartAE_init(char*, int)+652) (BuildId: db8a1063aeb3003e75cd15a2e0aec9d3)
06-26 21:33:28.873 19480 19480 F DEBUG   :       #03 pc 00000000002a8bb0  /vendor/lib64/libcamera_algo.so (android::IppAlgoSmartAE::initSmartAE()+176) (BuildId: db8a1063aeb3003e75cd15a2e0aec9d3)
06-26 21:33:28.873 19480 19480 F DEBUG   :       #04 pc 00000000002a89ec  /vendor/lib64/libcamera_algo.so (android::IppAlgoSmartAE::onCreate(android::HwaIppFrame*)+580) (BuildId: db8a1063aeb3003e75cd15a2e0aec9d3)
06-26 21:33:28.873 19480 19480 F DEBUG   :       #05 pc 0000000000266aec  /vendor/lib64/libcamera_algo.so (android::HwaIppAlgoExecutor::selfCheck(android::HwaIppFrame*)+444) (BuildId: db8a1063aeb3003e75cd15a2e0aec9d3)
06-26 21:33:28.873 19480 19480 F DEBUG   :       #06 pc 0000000000267024  /vendor/lib64/libcamera_algo.so (android::HwaIppAlgoExecutor::processFrameSync(android::HwaIppFrame*, android::HwaIppFrame**)+56) (BuildId: db8a1063aeb3003e75cd15a2e0aec9d3)
06-26 21:33:28.873 19480 19480 F DEBUG   :       #07 pc 000000000026518c  /vendor/lib64/libcamera_algo.so (android::HwaIppPluginImpl::transformFrame(android::HwaIppFrame*, android::HwaIppFrame**)+652) (BuildId: db8a1063aeb3003e75cd15a2e0aec9d3)
06-26 21:33:28.873 19480 19480 F DEBUG   :       #08 pc 00000000002fe46c  /odm/lib64/hwcam/hwcam.kirin970.m.BLANC.so (hw::IppAlgo::_processFrame(hw::IBuffer*, _meta_data_t*, hw::IBuffer**, int, int*)+120) (BuildId: 6da5386347250808a19685c09e63b39a)
06-26 21:33:28.874 19480 19480 F DEBUG   :       #09 pc 00000000002ff868  /odm/lib64/hwcam/hwcam.kirin970.m.BLANC.so (hw::IppAlgoFilter::processFrame(hw::IBuffer*)+480) (BuildId: 6da5386347250808a19685c09e63b39a)
06-26 21:33:28.874 19480 19480 F DEBUG   :       #10 pc 00000000002ff52c  /odm/lib64/hwcam/hwcam.kirin970.m.BLANC.so (hw::IppAlgoPortIn::receive(hw::IBuffer*)+656) (BuildId: 6da5386347250808a19685c09e63b39a)
06-26 21:33:28.874 19480 19480 F DEBUG   :       #11 pc 00000000002ffb94  /odm/lib64/hwcam/hwcam.kirin970.m.BLANC.so (non-virtual thunk to hw::IppAlgoPortIn::receive(hw::IBuffer*)+12) (BuildId: 6da5386347250808a19685c09e63b39a)
06-26 21:33:28.874 19480 19480 F DEBUG   :       #12 pc 000000000050d528  /odm/lib64/hwcam/hwcam.kirin970.m.BLANC.so (hw::CPortOutHISPBase::dequeueBuffer(hw::CIntfPtr<hw::IBuffer>)+1324) (BuildId: 6da5386347250808a19685c09e63b39a)
06-26 21:33:28.874 19480 19480 F DEBUG   :       #13 pc 000000000050aec0  /odm/lib64/hwcam/hwcam.kirin970.m.BLANC.so (hw::CPortOutHISPBase::BufferRespond::handleMessage(android::Message const&)+72) (BuildId: 6da5386347250808a19685c09e63b39a)
06-26 21:33:28.874 19480 19480 F DEBUG   :       #14 pc 0000000000013fec  /apex/com.android.vndk.v28/lib64/libutils.so (android::Looper::pollInner(int)+336) (BuildId: 712be0228fdea19952ef01334ed8a8d7)
06-26 21:33:28.874 19480 19480 F DEBUG   :       #15 pc 0000000000013e00  /apex/com.android.vndk.v28/lib64/libutils.so (android::Looper::pollOnce(int, int*, int*, void**)+60) (BuildId: 712be0228fdea19952ef01334ed8a8d7)
06-26 21:33:28.874 19480 19480 F DEBUG   :       #16 pc 000000000057fd28  /odm/lib64/hwcam/hwcam.kirin970.m.BLANC.so (hw::CLooperThread::Thread::threadLoop()+112) (BuildId: 6da5386347250808a19685c09e63b39a)
06-26 21:33:28.874 19480 19480 F DEBUG   :       #17 pc 000000000000fa08  /apex/com.android.vndk.v28/lib64/libutils.so (android::Thread::_threadLoop(void*)+280) (BuildId: 712be0228fdea19952ef01334ed8a8d7)
06-26 21:33:28.874 19480 19480 F DEBUG   :       #18 pc 00000000000b1a50  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+264) (BuildId: 77fa03547404bb2bbaa67c8a128f9ff3)
06-26 21:33:28.874 19480 19480 F DEBUG   :       #19 pc 000000000005152c  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64) (BuildId: 77fa03547404bb2bbaa67c8a128f9ff3)




....



06-26 21:33:28.974  1113  1113 I mediacomm@2.1-service: serviceDied:532: +.
06-26 21:33:28.974  1113  1113 E mediacomm@2.1-service: serviceDied:549: The client died, pid[16141]!
06-26 21:33:28.974  1113  1113 I mediacomm@2.1-service: getMdcClientByPid:148: get client<Camera, 2, 16141>, channel<4, 1>, perf=3, power=0.
06-26 21:33:28.974  1113  1113 I mediacomm@2.1-service: serviceDied:560: client<Camera 2, 16141> died, clear resource.
06-26 21:33:28.974  1113  1113 I mediacomm@2.1-service: destroyClient:321: destroy client<Camera, 2, 16141>, channel<4, 1>, perf=3, power=0.
06-26 21:33:28.974  1113  1113 I mediacomm@2.1-service: destroyClient:332: set copybit perf low.
06-26 21:33:28.974  1113  1113 I mediacomm@2.1-service: serviceDied:564: -.
06-26 21:33:28.975  1273 16140 I CameraProviderManager: Camera provider 'legacy/0-2' has died; removing it
06-26 21:33:28.975  1273 16140 I CameraService: onDeviceStatusChanged: Status changed for cameraId=0, newStatus=0
06-26 21:33:28.977  1273 19436 E Camera3-Device: processBatchCaptureRequests: Transaction error: Status(EX_TRANSACTION_FAILED): 'DEAD_OBJECT: '
06-26 21:33:28.979  1297  1366 I Sensors@1.0-impl: activate-7 enabled-0 fwkOals-1 camOals-1 fwkOcolor-0 camOcolor-1 fwkOtof-0 camOtof-0
06-26 21:33:28.979  1297  1366 D SensorHub: enableSensor-> handle: 7 enable : 0
06-26 21:33:28.979  1297  1366 D SensorHub: Channel activate-> handle: 7, enabled:0, err: 0
06-26 21:33:28.981  1273 19436 E Camera3-Device: Camera 0: sendRequestsBatch: RequestThread: Unable to submit capture request 7 to HAL device: Broken pipe (-32)
06-26 21:33:28.983 15657 16072 E CAM_FatalErrorHandler: Handling Camera Access Failure:
06-26 21:33:28.983 15657 16072 E CAM_FatalErrorHandler: java.lang.Exception
06-26 21:33:28.983 15657 16072 E CAM_FatalErrorHandler:         at com.android.camera.FatalErrorHandlerImpl.onGenericCameraAccessFailure(FatalErrorHandlerImpl.java:84)
06-26 21:33:28.983 15657 16072 E CAM_FatalErrorHandler:         at com.android.camera.one.v2.Camera2OneCameraOpenerImpl$1.onError(Camera2OneCameraOpenerImpl.java:154)
06-26 21:33:28.983 15657 16072 E CAM_FatalErrorHandler:         at android.hardware.camera2.impl.CameraDeviceImpl.notifyError(CameraDeviceImpl.java:1809)
06-26 21:33:28.983 15657 16072 E CAM_FatalErrorHandler:         at android.hardware.camera2.impl.CameraDeviceImpl.$r8$lambda$KBQCqQRdhVVn7uHI9Xdha6OqnsU(Unknown Source:0)
06-26 21:33:28.983 15657 16072 E CAM_FatalErrorHandler:         at android.hardware.camera2.impl.CameraDeviceImpl$$ExternalSyntheticLambda0.accept(Unknown Source:8)
06-26 21:33:28.983 15657 16072 E CAM_FatalErrorHandler:         at com.android.internal.util.function.pooled.PooledLambdaImpl.doInvoke(PooledLambdaImpl.java:281)
06-26 21:33:28.983 15657 16072 E CAM_FatalErrorHandler:         at com.android.internal.util.function.pooled.PooledLambdaImpl.invoke(PooledLambdaImpl.java:204)
06-26 21:33:28.983 15657 16072 E CAM_FatalErrorHandler:         at com.android.internal.util.function.pooled.OmniFunction.run(OmniFunction.java:97)
06-26 21:33:28.983 15657 16072 E CAM_FatalErrorHandler:         at android.os.Handler.handleCallback(Handler.java:938)
06-26 21:33:28.983 15657 16072 E CAM_FatalErrorHandler:         at android.os.Handler.dispatchMessage(Handler.java:99)
06-26 21:33:28.983 15657 16072 E CAM_FatalErrorHandler:         at android.os.Looper.loopOnce(Looper.java:201)
06-26 21:33:28.983 15657 16072 E CAM_FatalErrorHandler:         at android.os.Looper.loop(Looper.java:288)
06-26 21:33:28.983 15657 16072 E CAM_FatalErrorHandler:         at android.os.HandlerThread.run(HandlerThread.java:67)
06-26 21:33:28.984 15657 16072 E CAM_CameraUtil: Show fatal error dialog
```

I can send you the full logs if needed, although I'd prefer to send them through e-mail for privacy reasons.

**Comment by acastillorobles77** [comment]
I have the same exact issue on my Huawei P smart 2019 (POT-LX3)

**Comment by CN-Mark-Zhang** [comment]
Same here, Huawei P20 Pro (CLT-AL00, kirin970) running PE+12/LOS19

**Comment by Iceows** [comment]
Same issue on TrebleDroid 13 with POT-LX1A and P20 Pro
Issue don't appear in Arrow 13 GSI TrebleDroid
