### ISSUE TITLE
Huawei - No default sound and list of system sound (ringtones, alarms, notify) is empty

### ISSUE THREAD

**Issue by Iceows** [phhusson/treble_experimentations#2386]
### Current Behavior:
The phone should come with a default sound list for ringtone, alarm and notification.
Default sounds should be set
  
### Describe the bug
No default sound for ringtone, notification and alarm in the settings
No system sound are display in the settings

### To Reproduce
To reproduce, start the phone,  goto Settings, goto Sound : 
Phone ringtone, default notification sound, and default alarm sound is empty
Phone ringtone list is also empty

### Expected behavior
phone ringtone must be Ring_Synth_04.ogg, same value of property :  ro.config.ringtone
[ro.config.ringtone]: [Ring_Synth_04.ogg]

same behavior with alarm and notification property

### Smartphone (please complete the following information):
 - Device: P20 Lite - ANE-LX1
 - Build Flavor: arm64 ab64
 - Version : v414

### Additional context

07-04 21:18:25.326  2509  3066 I MediaProvider: Begin Intent { act=com.android.providers.media.action.SCAN_VOLUME (has extras) }
07-04 21:18:25.334  2509  3066 E ModernMediaScanner: Couldn't find directory to scan
07-04 21:18:25.334  2509  3066 E ModernMediaScanner: java.io.FileNotFoundException: Can't find volume for /system/media
07-04 21:18:25.334  2509  3066 E ModernMediaScanner: 	at com.android.providers.media.util.FileUtils.getStorageVolume(FileUtils.java:885)
07-04 21:18:25.334  2509  3066 E ModernMediaScanner: 	at com.android.providers.media.scan.ModernMediaScanner$Scan.<init>(ModernMediaScanner.java:371)
07-04 21:18:25.334  2509  3066 E ModernMediaScanner: 	at com.android.providers.media.scan.ModernMediaScanner.scanDirectory(ModernMediaScanner.java:247)
07-04 21:18:25.334  2509  3066 E ModernMediaScanner: 	at com.android.providers.media.MediaProvider.scanDirectory(MediaProvider.java:1266)
07-04 21:18:25.334  2509  3066 E ModernMediaScanner: 	at com.android.providers.media.MediaService.onScanVolume(MediaService.java:194)
07-04 21:18:25.334  2509  3066 E ModernMediaScanner: 	at com.android.providers.media.MediaService.onScanVolume(MediaService.java:162)
07-04 21:18:25.334  2509  3066 E ModernMediaScanner: 	at com.android.providers.media.MediaService.onHandleWork(MediaService.java:95)
07-04 21:18:25.334  2509  3066 E ModernMediaScanner: 	at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:396)
07-04 21:18:25.334  2509  3066 E ModernMediaScanner: 	at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:387)
07-04 21:18:25.334  2509  3066 E ModernMediaScanner: 	at android.os.AsyncTask$3.call(AsyncTask.java:394)
07-04 21:18:25.334  2509  3066 E ModernMediaScanner: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
07-04 21:18:25.334  2509  3066 E ModernMediaScanner: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
07-04 21:18:25.334  2509  3066 E ModernMediaScanner: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
07-04 21:18:25.334  2509  3066 E ModernMediaScanner: 	at java.lang.Thread.run(Thread.java:920)
07-04 21:18:25.337  2509  3066 E ModernMediaScanner: Couldn't find directory to scan
07-04 21:18:25.337  2509  3066 E ModernMediaScanner: java.io.FileNotFoundException: Can't find volume for /oem/media
07-04 21:18:25.337  2509  3066 E ModernMediaScanner: 	at com.android.providers.media.util.FileUtils.getStorageVolume(FileUtils.java:885)
.......
.......
07-04 21:18:25.337  2509  3066 E ModernMediaScanner: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
07-04 21:18:25.337  2509  3066 E ModernMediaScanner: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
07-04 21:18:25.337  2509  3066 E ModernMediaScanner: 	at java.lang.Thread.run(Thread.java:920)
07-04 21:18:25.339  2509  3066 E ModernMediaScanner: Couldn't find directory to scan
07-04 21:18:25.339  2509  3066 E ModernMediaScanner: java.io.FileNotFoundException: Can't find volume for /system/product/media
07-04 21:18:25.339  2509  3066 E ModernMediaScanner: 	at com.android.providers.media.util.FileUtils.getStorageVolume(FileUtils.java:885)
07-04 21:18:25.339  2509  3066 E ModernMediaScanner: 	at com.android.providers.media.scan.ModernMediaScanner$Scan.<init>(ModernMediaScanner.java:371)

**Comment by Iceows** [comment]
An identical problem already exists in A11 on the a-only version (perhaps also ab version)

**Comment by Iceows** [comment]
Fix A11 patch

     public static @NonNull String getVolumeName(@NonNull Context context, @NonNull File path) {
         if (contains(Environment.getStorageDirectory(), path)) {
-            return context.getSystemService(StorageManager.class).getStorageVolume(path)
-                    .getMediaStoreVolumeName();
+            StorageManager storage=context.getSystemService(StorageManager.class);
+            if (storage.getStorageVolume(path)!=null)
+                return storage.getStorageVolume(path).getMediaStoreVolumeName();
+            else
+                return MediaStore.VOLUME_INTERNAL;
         } else {
             return MediaStore.VOLUME_INTERNAL;
         }

https://github.com/Iceows/aosp_patches_leaos/tree/main/patches/personal/packages_providers_MediaProvider

**Comment by Iceows** [comment]
Fix A12/lineage 19.1 patch https://github.com/Iceows/lineage_patches_leaos/blob/lineage-19.1/patches_platform_iceows/packages_providers_MediaProvider/0001-Fixed-errors-on-the-ModermMediaScanner-Huawei.patch

**Comment by phhusson** [comment]
Thanks. What's the root cause for system volume null being null?

**Comment by Iceows** [comment]
I haven't found it yet, the error exists since Android version 11. I have
the impression that it comes from the Huawei files, because the problem is
present at the level of the vold calls too

**Comment by Iceows** [comment]
I will have to fix the problem probably at the source (under vold) it will be cleaner.  This error volumename null I also saw it elsewhere in the logs
