### ISSUE TITLE
[OPPO A12] Fingerprint scanner not working

### ISSUE THREAD

**Issue by olsdf** [phhusson/treble_experimentations#2641]
### Current Behavior:
  
I can't set up the scanner, just nothing happens on the screen
### Describe the bug
I found out something here, it turns out that the scanner works, and even if you somehow force it to function in the system, you can register your finger.
But due to the fact that my android.hardware.biometrics.fingerprint@2.1-service.oppo.compat is not compatible with this model, instead of launching the scanner the following happens:
07-16 10:39:16.937 899 899 E android.hardware.biometrics.fingerprint@2.1-service.oppo.compat: preEnroll
07-16 10:39:16.937 939 939 E fingerprint: fingerprint_pre_enroll
07-16 10:39:20.605 1244 2212 I ActivityTaskManager: START u0 {cmp=com.android.settings/.biometrics.fingerprint.FingerprintEnrollFindSensor (has extras)} from uid 1000
07-16 10:39:20.663 1244 1244 D FingerprintService: setActiveUser(0)
07-16 10:39:20.665 1244 1634 D PHH-Enroll: at com.android.server.biometrics.fingerprint.FacolaView.show(FacolaView.java:296)
07-16 10:39:20.665 1244 1634 D PHH-Enroll: at com.android.server.biometrics.fingerprint.FingerprintService$FingerprintServiceWrapper.enroll(FingerprintService.java:233)
07-16 10:39:20.665 1244 1634 D PHH-Enroll: at android.hardware.fingerprint.IFingerprintService$Stub.onTransact(IFingerprintService.java:387)
07-16 10:39:20.665 1244 1244 V FingerprintService: starting client EnrollClientImpl(com.android.settings) targetUserId: 0 currentUserId: 0 cookie: 0/0
07-16 10:39:20.665 899 899 E android.hardware.biometrics.fingerprint@2.1-service.oppo.compat: enroll
07-16 10:39:20.666 939 939 E fingerprint: fingerprint_enroll
07-16 10:39:20.666 939 939 D android.hardware.biometrics.fingerprint@2.1-service: onError(result:1, error:1)
07-16 10:39:20.667 899 899 E android.hardware.biometrics.fingerprint@2.1-service.oppo.compat: onError 488844177408 0
07-16 10:39:20.667 1244 1244 V FingerprintService: handleError(client=com.android.settings, error = 1)
07-16 10:39:20.668 1244 1244 V FingerprintService: Done with client: com.android.settings
07-16 10:39:20.668 1244 1244 W FingerprintService: Got ERROR_HW_UNAVAILABLE; try reconnecting next client.
07-16 10:39:22.652 939 1053 D fingerprint: [silead_worker]I[_worker_set_state_unlock:139] set to STATE_IDLE************
07-16 10:39:22.963 939 1053 D android.hardware.biometrics.fingerprint@2.1-service: onTouchUp()
07-16 10:39:22.963 939 1053 D fingerprint: [silead_worker]I[_worker_set_state_unlock:139] set to STATE_NAV************
07-16 10:39:22.963 939 1053 D fingerprint: [silead_worker]I[_worker_command_loop:244] work STATE_NAV
07-16 10:39:22.963 939 1053 D fingerprint: [silead_worker]I[_worker_command_loop:260] dispatch (3) STATE_NAV
07-16 10:39:22.963 939 1053 D fingerprint: [silead_nav]I[silfp_nav_command:90] nav-------------
07-16 10:39:24.820 939 1053 D fingerprint: [silead_worker]I[_worker_set_state_unlock:139] set to STATE_IDLE************
07-16 10:39:26.463 939 1053 D android.hardware.biometrics.fingerprint@2.1-service: onTouchUp()
07-16 10:39:26.463 939 1053 D fingerprint: [silead_worker]I[_worker_set_state_unlock:139] set to STATE_NAV************
07-16 10:39:26.464 939 1053 D fingerprint: [silead_worker]I[_worker_command_loop:244] work STATE_NAV
07-16 10:39:26.464 939 1053 D fingerprint: [silead_worker]I[_worker_command_loop:260] dispatch (3) STATE_NAV

I was chatting with one user from the 4PDA forum and after he read my logs, he sent me a line with the content android.hardware.biometrics.fingerprint@2.1-service.oppo.compat
and points out to me that the scanner is not working because of this. For a long time we tried to understand what the reason was. I even removed this component from the system, but then I lost the ability to configure the scanner.
I tried many methods that would help me finally set up the scanner, but to no avail. I scoured the entire forum and even wrote in the “Development and porting of GSI” topics and in my Oppo A12 topic - Discussion,
but no one wanted to help me or had no idea how to work with this scanner.
I don’t want to give up, I’ve already walked this path, but nothing can be done. I will try to configure it somehow, but I do not have such knowledge and the device tree that I could write this component myself, which interferes or prevents me from setting up the scanner. Or, in fact, there is no need to write it, and the answer is generally on the surface, but who knows. I repeat for the second time, I do not have such knowledge.
After the scanner cannot initialize itself, it enters the gesture navigation mode and therefore the scanner starts working. On Android 12 the situation is more interesting - after I try to configure the scanner, a window pops up with an error that the scanner could not be configured.
Although there are no errors at all on Android 10 and I already understand why. Because it initialized itself as “gesture navigation”, so no errors appear on the screen, and on Android 12 it doesn’t work that way.
Although please note that oplus.compat is present in Android 12, unlike Android 10 (I haven’t tested it on Android 11)
### To Reproduce
 
1. Go to 'Settings'
2. Click on 'Secutiry'
3. Scroll down to 'Fingerprint'

### Expected behavior
The scanner would have continued to be set up and I would have completed it successfully

### Photos
![Screenshot_20240716-124718](https://github.com/user-attachments/assets/b18720ec-9c09-41d1-a793-b10cb250e094)
![Screenshot_20240716-124710](https://github.com/user-attachments/assets/4e09567c-a7c6-40b6-8b8c-39738ff341ab)

### Smartphone (please complete the following information):
 - Device: OPPO A12
 - Build Flavor: system-quack-arm64-ab-vanilla.img
 - Version: v215

### Additional context
[fingerprintaosp.txt](https://github.com/user-attachments/files/16243642/fingerprintaosp.txt)

**Comment by Goku9650** [comment]
what is your build version can you please tell me i also want to install gsi on my oppo a12
