### ISSUE TITLE
LineageOS 16.0 SystemUI keeps stopping

### ISSUE THREAD

**Issue by milankragujevic** [phhusson/treble_experimentations#304]
```
12-01 19:14:55.105  3312  3312 D AndroidRuntime: Shutting down VM
12-01 19:14:55.108  3312  3312 E AndroidRuntime: FATAL EXCEPTION: main
12-01 19:14:55.108  3312  3312 E AndroidRuntime: Process: com.android.systemui, PID: 3312
12-01 19:14:55.108  3312  3312 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke interface method 'lineageos.app.Profile lineageos.app.IProfileManager.getActiveProfile()' on a null object reference
12-01 19:14:55.108  3312  3312 E AndroidRuntime:        at lineageos.app.ProfileManager.getActiveProfile(ProfileManager.java:307)
12-01 19:14:55.108  3312  3312 E AndroidRuntime:        at com.android.systemui.keyguard.KeyguardViewMediator.isKeyguardDisabled(KeyguardViewMediator.java:1054)
12-01 19:14:55.108  3312  3312 E AndroidRuntime:        at com.android.systemui.keyguard.KeyguardViewMediator.maybeSendUserPresentBroadcast(KeyguardViewMediator.java:1030)
12-01 19:14:55.108  3312  3312 E AndroidRuntime:        at com.android.systemui.keyguard.KeyguardViewMediator.handleSystemReady(KeyguardViewMediator.java:801)
12-01 19:14:55.108  3312  3312 E AndroidRuntime:        at com.android.systemui.keyguard.KeyguardViewMediator.access$4800(KeyguardViewMediator.java:137)
12-01 19:14:55.108  3312  3312 E AndroidRuntime:        at com.android.systemui.keyguard.KeyguardViewMediator$5.handleMessage(KeyguardViewMediator.java:1645)
12-01 19:14:55.108  3312  3312 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
12-01 19:14:55.108  3312  3312 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:193)
12-01 19:14:55.108  3312  3312 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6680)
12-01 19:14:55.108  3312  3312 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
12-01 19:14:55.108  3312  3312 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
12-01 19:14:55.108  3312  3312 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
12-01 19:14:55.115   960  2561 V RescueParty: Disabled because of active USB connection
12-01 19:14:55.117   960  2561 W ActivityManager: Process com.android.systemui has crashed too many times: killing!
12-01 19:14:55.122  3312  3312 I Process : Sending signal. PID: 3312 SIG: 9
```

arm, vanilla, a-only, no su.

**Comment by milankragujevic** [comment]
Doesn't seem to be a problem of phhusson until proven otherwise. Closed.

**Comment by svoboda18** [comment]
This Same Happen For Me Also, Built LOS16 Yesterday (Using Phh's Trees), It Seems It A Patch Issue!.

**Comment by AndyCGYan** [comment]
@milankragujevic @svoboda18 I seem to have solved it by removing [the reference to getActiveProfile()](https://github.com/LineageOS/android_frameworks_base/blob/8f7726cc447f76dd163e9813f1aef8de3907141e/packages/SystemUI/src/com/android/systemui/keyguard/KeyguardViewMediator.java#L1054), that is, removing the logic around disabling keyguard based on Profile status (L1053~L1061) entirely. A very dirty solution but it got me into the OS and I'll live with it. If you have a better idea in the future please also let know.
