### ISSUE TITLE
[Xiaomi MIX 2S] Zygote died with exception "java.lang.NullPointerException: Attempt to read from field 'android.content.pm.Signature[] android.content.pm.PackageParser$Package.mSignatures' on a null object reference"

### ISSUE THREAD

**Issue by notsyncing** [phhusson/treble_experimentations#44]
Hello, I compiled and flashed the lineage gsi and flashed to my Xiaomi MIX 2S, and it stucked at the boot animation. adb logcat shows:

```
05-20 17:55:08.095  2236  2236 W PackageManager: Removing dangling permission: com.google.android.gms.magictether.permission.DISABLE_SOFT_AP from package com.google.android.gms
05-20 17:55:08.095  2236  2236 W PackageManager: Removing dangling permission: com.android.voicemail.permission.ADD_VOICEMAIL from package android
05-20 17:55:08.095  2236  2236 W PackageManager: Removing dangling permission: com.google.android.gms.chromesync.permission.METADATA_UPDATED from package com.google.android.gms
05-20 17:55:08.095  2236  2236 E System  : ******************************************
05-20 17:55:08.095  2236  2236 E System  : ************ Failure starting system services
05-20 17:55:08.095  2236  2236 E System  : java.lang.NullPointerException: Attempt to read from field 'android.content.pm.Signature[] android.content.pm.PackageParser$Package.mSignatures' on a null object reference
05-20 17:55:08.095  2236  2236 E System  :      at com.android.server.pm.PackageManagerService.grantSignaturePermission(PackageManagerService.java:13391)
05-20 17:55:08.095  2236  2236 E System  :      at com.android.server.pm.PackageManagerService.grantPermissionsLPw(PackageManagerService.java:13127)
05-20 17:55:08.095  2236  2236 E System  :      at com.android.server.pm.PackageManagerService.updatePermissionsLPw(PackageManagerService.java:12977)
05-20 17:55:08.095  2236  2236 E System  :      at com.android.server.pm.PackageManagerService.updatePermissionsLPw(PackageManagerService.java:12899)
05-20 17:55:08.095  2236  2236 E System  :      at com.android.server.pm.PackageManagerService.removePackageDataLIF(PackageManagerService.java:19783)
05-20 17:55:08.095  2236  2236 E System  :      at com.android.server.pm.PackageManagerService.deleteInstalledPackageLIF(PackageManagerService.java:20060)
05-20 17:55:08.095  2236  2236 E System  :      at com.android.server.pm.PackageManagerService.deletePackageLIF(PackageManagerService.java:20255)
05-20 17:55:08.095  2236  2236 E System  :      at com.android.server.pm.PackageManagerService.updateAllSharedLibrariesLPw(PackageManagerService.java:10657)
05-20 17:55:08.095  2236  2236 E System  :      at com.android.server.pm.PackageManagerService.<init>(PackageManagerService.java:2932)
05-20 17:55:08.095  2236  2236 E System  :      at com.android.server.pm.PackageManagerService.main(PackageManagerService.java:2334)
05-20 17:55:08.095  2236  2236 E System  :      at com.android.server.SystemServer.startBootstrapServices(SystemServer.java:605)
05-20 17:55:08.095  2236  2236 E System  :      at com.android.server.SystemServer.run(SystemServer.java:409)
05-20 17:55:08.095  2236  2236 E System  :      at com.android.server.SystemServer.main(SystemServer.java:274)
05-20 17:55:08.095  2236  2236 E System  :      at java.lang.reflect.Method.invoke(Native Method)
05-20 17:55:08.095  2236  2236 E System  :      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
05-20 17:55:08.095  2236  2236 E System  :      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:787)
05-20 17:55:08.095  2236  2236 D SystemServerTiming: StartPackageManagerService took to complete: 1721ms
05-20 17:55:08.095  2236  2236 E Zygote  : System zygote died with exception
05-20 17:55:08.095  2236  2236 E Zygote  : java.lang.NullPointerException: Attempt to read from field 'android.content.pm.Signature[] android.content.pm.PackageParser$Package.mSignatures' on a null object reference
05-20 17:55:08.095  2236  2236 E Zygote  :      at com.android.server.pm.PackageManagerService.grantSignaturePermission(PackageManagerService.java:13391)
05-20 17:55:08.095  2236  2236 E Zygote  :      at com.android.server.pm.PackageManagerService.grantPermissionsLPw(PackageManagerService.java:13127)
05-20 17:55:08.095  2236  2236 E Zygote  :      at com.android.server.pm.PackageManagerService.updatePermissionsLPw(PackageManagerService.java:12977)
05-20 17:55:08.095  2236  2236 E Zygote  :      at com.android.server.pm.PackageManagerService.updatePermissionsLPw(PackageManagerService.java:12899)
05-20 17:55:08.095  2236  2236 E Zygote  :      at com.android.server.pm.PackageManagerService.removePackageDataLIF(PackageManagerService.java:19783)
05-20 17:55:08.095  2236  2236 E Zygote  :      at com.android.server.pm.PackageManagerService.deleteInstalledPackageLIF(PackageManagerService.java:20060)
05-20 17:55:08.095  2236  2236 E Zygote  :      at com.android.server.pm.PackageManagerService.deletePackageLIF(PackageManagerService.java:20255)
05-20 17:55:08.095  2236  2236 E Zygote  :      at com.android.server.pm.PackageManagerService.updateAllSharedLibrariesLPw(PackageManagerService.java:10657)
05-20 17:55:08.095  2236  2236 E Zygote  :      at com.android.server.pm.PackageManagerService.<init>(PackageManagerService.java:2932)
05-20 17:55:08.095  2236  2236 E Zygote  :      at com.android.server.pm.PackageManagerService.main(PackageManagerService.java:2334)
05-20 17:55:08.095  2236  2236 E Zygote  :      at com.android.server.SystemServer.startBootstrapServices(SystemServer.java:605)
05-20 17:55:08.095  2236  2236 E Zygote  :      at com.android.server.SystemServer.run(SystemServer.java:409)
05-20 17:55:08.095  2236  2236 E Zygote  :      at com.android.server.SystemServer.main(SystemServer.java:274)
05-20 17:55:08.095  2236  2236 E Zygote  :      at java.lang.reflect.Method.invoke(Native Method)
05-20 17:55:08.095  2236  2236 E Zygote  :      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
05-20 17:55:08.095  2236  2236 E Zygote  :      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:787)
05-20 17:55:08.096  2236  2236 D AndroidRuntime: Shutting down VM
05-20 17:55:08.096  2236  2236 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: main
05-20 17:55:08.096  2236  2236 E AndroidRuntime: java.lang.NullPointerException: Attempt to read from field 'android.content.pm.Signature[] android.content.pm.PackageParser$Package.mSignatures' on a null object reference
05-20 17:55:08.096  2236  2236 E AndroidRuntime:        at com.android.server.pm.PackageManagerService.grantSignaturePermission(PackageManagerService.java:13391)
05-20 17:55:08.096  2236  2236 E AndroidRuntime:        at com.android.server.pm.PackageManagerService.grantPermissionsLPw(PackageManagerService.java:13127)
05-20 17:55:08.096  2236  2236 E AndroidRuntime:        at com.android.server.pm.PackageManagerService.updatePermissionsLPw(PackageManagerService.java:12977)
05-20 17:55:08.096  2236  2236 E AndroidRuntime:        at com.android.server.pm.PackageManagerService.updatePermissionsLPw(PackageManagerService.java:12899)
05-20 17:55:08.096  2236  2236 E AndroidRuntime:        at com.android.server.pm.PackageManagerService.removePackageDataLIF(PackageManagerService.java:19783)
05-20 17:55:08.096  2236  2236 E AndroidRuntime:        at com.android.server.pm.PackageManagerService.deleteInstalledPackageLIF(PackageManagerService.java:20060)
05-20 17:55:08.096  2236  2236 E AndroidRuntime:        at com.android.server.pm.PackageManagerService.deletePackageLIF(PackageManagerService.java:20255)
05-20 17:55:08.096  2236  2236 E AndroidRuntime:        at com.android.server.pm.PackageManagerService.updateAllSharedLibrariesLPw(PackageManagerService.java:10657)
05-20 17:55:08.096  2236  2236 E AndroidRuntime:        at com.android.server.pm.PackageManagerService.<init>(PackageManagerService.java:2932)
05-20 17:55:08.096  2236  2236 E AndroidRuntime:        at com.android.server.pm.PackageManagerService.main(PackageManagerService.java:2334)
05-20 17:55:08.096  2236  2236 E AndroidRuntime:        at com.android.server.SystemServer.startBootstrapServices(SystemServer.java:605)
05-20 17:55:08.096  2236  2236 E AndroidRuntime:        at com.android.server.SystemServer.run(SystemServer.java:409)
05-20 17:55:08.096  2236  2236 E AndroidRuntime:        at com.android.server.SystemServer.main(SystemServer.java:274)
05-20 17:55:08.096  2236  2236 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
05-20 17:55:08.096  2236  2236 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
05-20 17:55:08.096  2236  2236 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:787)
05-20 17:55:08.096  2236  2236 E AndroidRuntime: Error reporting crash
05-20 17:55:08.096  2236  2236 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke interface method 'void android.app.IActivityManager.handleApplicationCrash(android.os.IBinder, android.app.ApplicationErrorReport$ParcelableCrashInfo)' on a null object reference
05-20 17:55:08.096  2236  2236 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$KillApplicationHandler.uncaughtException(RuntimeInit.java:116)
05-20 17:55:08.096  2236  2236 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
05-20 17:55:08.096  2236  2236 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1063)
05-20 17:55:08.096  2236  2236 E AndroidRuntime:        at java.lang.Thread.dispatchUncaughtException(Thread.java:1955)
05-20 17:55:08.096  2236  2236 I Process : Sending signal. PID: 2236 SIG: 9
05-20 17:55:08.106   562   562 I ServiceManager: service 'batterystats' died
05-20 17:55:08.106   562   562 I ServiceManager: service 'appops' died
05-20 17:55:08.106   562   562 I ServiceManager: service 'power' died
05-20 17:55:08.106   562   562 I ServiceManager: service 'recovery' died
05-20 17:55:08.106   562   562 I ServiceManager: service 'display' died
05-20 17:55:08.106   562   562 I ServiceManager: service 'device_identifiers' died
05-20 17:55:08.107  2202  2202 E Zygote  : Exit zygote because system server (2236) has terminated
05-20 17:55:08.118   562   562 I ServiceManager: service 'media.audio_flinger' died
05-20 17:55:08.118   562   562 I ServiceManager: service 'media.audio_policy' died
05-20 17:55:08.118   562   562 I ServiceManager: service 'media.sound_trigger_hw' died
```

The image from your xda thread (2018-05-19) shows the same result.

It seems a signing problem. Could you please tell me how could I resolve the problem, or what else should I provide to help fixing this? Thank you very much!

**Comment by phhusson** [comment]
You did a factory reset after flashing it, right?

**Comment by notsyncing** [comment]
Oh my fault :/
After a factory reset it boots ok.
Thanks very much for the rapid response!
