### ISSUE TITLE
[Galaxy S9] When disabling keylock, SystemUI crashes

### ISSUE THREAD

**Issue by phhusson** [phhusson/treble_experimentations#62]
05-30 13:33:23.026  7583  7583 W FingerprintManager: Invalid error message: 8, 1004
05-30 13:33:23.026  7583  7583 D AndroidRuntime: Shutting down VM
05-30 13:33:23.027  7583  7583 E AndroidRuntime: FATAL EXCEPTION: main
05-30 13:33:23.027  7583  7583 E AndroidRuntime: Process: com.android.systemui, PID: 7583
05-30 13:33:23.027  7583  7583 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String java.lang.CharSequence.toString()' on a null object reference
05-30 13:33:23.027  7583  7583 E AndroidRuntime: 	at com.android.keyguard.KeyguardUpdateMonitor$7.onAuthenticationError(KeyguardUpdateMonitor.java:840)
05-30 13:33:23.027  7583  7583 E AndroidRuntime: 	at android.hardware.fingerprint.FingerprintManager$MyHandler.sendErrorResult(FingerprintManager.java:940)
05-30 13:33:23.027  7583  7583 E AndroidRuntime: 	at android.hardware.fingerprint.FingerprintManager$MyHandler.handleMessage(FingerprintManager.java:888)
05-30 13:33:23.027  7583  7583 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
05-30 13:33:23.027  7583  7583 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
05-30 13:33:23.027  7583  7583 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6494)
05-30 13:33:23.027  7583  7583 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-30 13:33:23.027  7583  7583 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
05-30 13:33:23.027  7583  7583 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by phhusson** [comment]
Fixed, or at least work-arounded by https://github.com/phhusson/platform_frameworks_base/commit/efd54d79723c85b80220ddb510debb11b4ce8337
