### ISSUE TITLE
Sargo (Pix 3A) System UI crash

### ISSUE THREAD

**Issue by nroach44** [phhusson/treble_experimentations#623]
LineageOS 16 on Sargo boots fine, following the Pixel 2 instructions (s/walleye/sargo) but it constantly has SystemUI crashes and eventually boots to recovery. If you constantly dismiss the pop up, you can get through the LOS setup wizard fine.

```
08-07 00:18:31.197   902  1172 I chatty  : uid=0(root) usb@1.1-service identical 3 lines
08-07 00:18:31.198   902  1172 I android.hardware.usb.gadget@1.0-service.bonito: event=1 on fd=16
08-07 00:18:31.199  1329  1433 I InputReader: Reconfiguring input devices.  changes=0x00000004
08-07 00:18:31.199  1329  1364 W ActivityManager: setHasOverlayUi called on unknown pid: 5748
08-07 00:18:31.200  1329  2517 W PinnedSliceState: Unable to contact content://0@com.android.systemui.keyguard/main
08-07 00:18:31.200  1329  2517 W PinnedSliceState: android.os.DeadObjectException
08-07 00:18:31.200  1329  2517 W PinnedSliceState: 	at android.os.BinderProxy.transactNative(Native Method)
08-07 00:18:31.200  1329  2517 W PinnedSliceState: 	at android.os.BinderProxy.transact(Binder.java:1127)
08-07 00:18:31.200  1329  2517 W PinnedSliceState: 	at android.content.ContentProviderProxy.call(ContentProviderNative.java:649)
08-07 00:18:31.200  1329  2517 W PinnedSliceState: 	at android.content.ContentProviderClient.call(ContentProviderClient.java:492)
08-07 00:18:31.200  1329  2517 W PinnedSliceState: 	at com.android.server.slice.PinnedSliceState.handleSendUnpinned(PinnedSliceState.java:203)
08-07 00:18:31.200  1329  2517 W PinnedSliceState: 	at com.android.server.slice.PinnedSliceState.lambda$t5Vl61Ns1u_83c4ri7920sczEu0(Unknown Source:0)
08-07 00:18:31.200  1329  2517 W PinnedSliceState: 	at com.android.server.slice.-$$Lambda$PinnedSliceState$t5Vl61Ns1u_83c4ri7920sczEu0.run(Unknown Source:2)
08-07 00:18:31.200  1329  2517 W PinnedSliceState: 	at android.os.Handler.handleCallback(Handler.java:873)
08-07 00:18:31.200  1329  2517 W PinnedSliceState: 	at android.os.Handler.dispatchMessage(Handler.java:99)
08-07 00:18:31.200  1329  2517 W PinnedSliceState: 	at android.os.Looper.loop(Looper.java:193)
08-07 00:18:31.200  1329  2517 W PinnedSliceState: 	at android.os.HandlerThread.run(HandlerThread.java:65)
08-07 00:18:31.200  1329  2517 W PinnedSliceState: 	at com.android.server.ServiceThread.run(ServiceThread.java:44)
08-07 00:18:31.202   902  1172 I android.hardware.usb.gadget@1.0-service.bonito: event=1 on fd=16
08-07 00:18:31.217  1329  1358 I ActivityManager: Start proc 5812:com.android.systemui/u0a32 for restart com.android.systemui
08-07 00:18:31.218   902  1172 I chatty  : uid=0(root) usb@1.1-service identical 7 lines

```
I have a full log if required.

**Comment by phhusson** [comment]
that doesn't seem to be the actual issue, so yes please provide full log.
Does the same crash happen on my aosp as well?

**Comment by nroach44** [comment]
Full log here: https://nroach44.id.au/sargo-lineageos16-vanilla-su

I'll get an AOSP/vanilla/su build going

**Comment by nroach44** [comment]
Well, I've tried building "aosp90 arm64-ab-vanilla-su" but it fails :

```
packages/apps/Bluetooth/src/com/android/bluetooth/hearingaid/HearingAidService.java:611: error: cannot find symbol
            mAudioManager.setHearingAidDeviceConnectionState(mPreviousAudioDevice,
                         ^
  symbol:   method setHearingAidDeviceConnectionState(BluetoothDevice,int)
  location: variable mAudioManager of type AudioManager
packages/apps/Bluetooth/src/com/android/bluetooth/hearingaid/HearingAidService.java:619: error: cannot find symbol
                mAudioManager.setHearingAidDeviceConnectionState(mPreviousAudioDevice,
                             ^
  symbol:   method setHearingAidDeviceConnectionState(BluetoothDevice,int)
  location: variable mAudioManager of type AudioManager
packages/apps/Bluetooth/src/com/android/bluetooth/hearingaid/HearingAidService.java:622: error: cannot find symbol
            mAudioManager.setHearingAidDeviceConnectionState(device,
                         ^
  symbol:   method setHearingAidDeviceConnectionState(BluetoothDevice,int)
  location: variable mAudioManager of type AudioManager
3 errors
[ 34% 2118/6078] Compiling SDK Stubs: out/target/common/obj/JAVA_LIBRARIES/android_stubs_current_intermediates/classes.jar
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
[ 34% 2119/6078] Compiling SDK Stubs: out/target/common/obj/JAVA_LIBRARIES/android_test_stubs_current_intermediates/classes.jar
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
[ 34% 2120/6078] Compiling SDK Stubs: out/target/common/obj/JAVA_LIBRARIES/android_system_stubs_current_intermediates/classes.jar
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
[ 34% 2122/6078] target dex2oat: out/target/product/phhgsi_arm64_ab/dex_bootjars/system/framework/arm64/boot.art
ninja: build stopped: subcommand failed.
14:49:47 ninja failed with: exit status 1

```
This is after completely cleaning out the tree and starting fresh again - should I make another ticket for that?

**Comment by nroach44** [comment]
Sargo boots fine with a treble_arm64_bvS-userdebug build, and system UI doesn't crash. Closing.
