### ISSUE TITLE
[10.0 v200.d] [Nokia 1] "locksettings" doesn't work and crashes the system if you try to set a new password

### ISSUE THREAD

**Issue by 0x15f2d** [phhusson/treble_experimentations#788]
If you try to put a PIN. It will hang the system and ask for one that doesn't exist >> Reset the phone.

Put a pattern will also hang the system and reboot, but it doesnt ask for it.

Put a password will produces either one of those 2 problem above.

Clearing it will cause this:

FRT:/ # locksettings clear
android.os.DeadObjectException
        at android.os.BinderProxy.transactNative(Native Method)
        at android.os.BinderProxy.transact(BinderProxy.java:510)
        at android.os.BinderProxy.shellCommand(BinderProxy.java:609)
        at com.android.commands.locksettings.LockSettingsCmd.onRun(LockSettingsCmd.java:74)
        at com.android.internal.os.BaseCommand.run(BaseCommand.java:56)
        at com.android.commands.locksettings.LockSettingsCmd.main(LockSettingsCmd.java:62)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:338)

**Comment by phhusson** [comment]
does it work on v119?

**Comment by 0x15f2d** [comment]
my phone can't flash it due to lack of memory but i can assure that android 9 works well with my device. except secure boot password confirmation before booting the actual system (if you typed wrong password it will say the phone's userdata broken and needs a factory reset. but rebooting it and typing the correct password will boot the os normally).

this will not happen on android 8 gsi though.

the vendor and boot that compatible with all of your gsi images is just android 8's boot and vendor.

**Comment by 0x15f2d** [comment]
> does it work on v119? 
@phhusson No it doesn't work and yeah I dumped the phone anyway. It was strict hardware encryption by Nokia I guess.
