### ISSUE TITLE
[AOSP 10.0 v202] BV9500: No flashlight, camera, SMS

### ISSUE THREAD

**Issue by cernodile** [phhusson/treble_experimentations#845]
Camera apps don't work, some apps depending on the permission crashes. Flashlight can't be toggled on. No received SMS. All of those worked in AOSP 9.0 builds.

OpenCamera app spit this out:
```
11-04 19:45:28.573 14626 14777 W CameraBase: An error occurred while connecting to camera 0: Status(-8, EX_SERVICE_SPECIFIC): '4: validateConnectLocked:940: No camera device with ID "" available'
11-04 19:45:28.574 14626 14777 W System.err: java.lang.RuntimeException: Fail to connect to camera service
11-04 19:45:28.574 14626 14777 W System.err: 	at android.hardware.Camera.<init>(Camera.java:551)
11-04 19:45:28.574 14626 14777 W System.err: 	at android.hardware.Camera.open(Camera.java:396)
11-04 19:45:28.575 14626 14777 W System.err: 	at net.sourceforge.opencamera.cameracontroller.CameraController1.<init>(CameraController1.java:62)
11-04 19:45:28.575 14626 14777 W System.err: 	at net.sourceforge.opencamera.preview.Preview.openCameraCore(Preview.java:1557)
11-04 19:45:28.575 14626 14777 W System.err: 	at net.sourceforge.opencamera.preview.Preview.access$1000(Preview.java:106)
11-04 19:45:28.576 14626 14777 W System.err: 	at net.sourceforge.opencamera.preview.Preview$1.doInBackground(Preview.java:1458)
11-04 19:45:28.576 14626 14777 W System.err: 	at net.sourceforge.opencamera.preview.Preview$1.doInBackground(Preview.java:1451)
11-04 19:45:28.576 14626 14777 W System.err: 	at android.os.AsyncTask$3.call(AsyncTask.java:378)
11-04 19:45:28.576 14626 14777 W System.err: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
11-04 19:45:28.576 14626 14777 W System.err: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
11-04 19:45:28.576 14626 14777 W System.err: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
11-04 19:45:28.576 14626 14777 W System.err: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
11-04 19:45:28.577 14626 14777 W System.err: 	at java.lang.Thread.run(Thread.java:919)
--- spams this 10s of times
11-04 19:42:19.829   336   336 E SELinux : avc:  denied  { find } for interface=vendor.samsung.hardware.light::ISecLight sid=u:r:system_server:s0 pid=1163 scontext=u:r:system_server:s0 tcontext=u:object_r:default_android_hwservice:s0 tclass=hwservice_manager permissive=0
11-04 19:42:19.833   576   576 D lights  : write_int open fd=7
```

**Comment by cernodile** [comment]
Camera and flashlight fixed by v206.
SMS requires workaround of SMSC set manually. This was not necessary before in Pie.
