### ISSUE TITLE
[Xiaomi MIX 2S] NFC does not work on LineageOS build

### ISSUE THREAD

**Issue by notsyncing** [phhusson/treble_experimentations#91]
Hello, I'm compiling LineageOS from your latest source, and the NFC still does not work (no NFC in system settings). I only got those log lines:

```
03-15 19:52:02.184  1372  1372 E PackageManager: updateAllSharedLibrariesLPw failed: Package com.android.nfc requires unavailable shared library com.nxp.nfc.nq; failing!
06-21 22:21:04.545  1372  1387 I ActivityManager: Start proc 2911:com.android.nfc/1027 for added application com.android.nfc
06-21 22:21:04.545  2911  2911 E SELinux : seapp_context_lookup:  No match for app with uid 1027, seinfo default, name com.android.nfc
06-21 22:21:04.545  2911  2911 E Zygote  : selinux_android_setcontext(1027, 0, "default:targetSdkVersion=26:complete", "com.android.nfc") failed
06-21 22:21:13.435  4072  4072 I getprop : type=1400 audit(0.0:235): avc: denied { open } for path="/dev/__properties__/u:object_r:nfc_nq_prop:s0" dev="tmpfs" ino=24590 scontext=u:r:phhsu_daemon:s0 tcontext=u:object_r:nfc_nq_prop:s0 tclass=file permissive=1
06-21 22:21:13.435  4072  4072 I getprop : type=1400 audit(0.0:236): avc: denied { getattr } for path="/dev/__properties__/u:object_r:nfc_nq_prop:s0" dev="tmpfs" ino=24590 scontext=u:r:phhsu_daemon:s0 tcontext=u:object_r:nfc_nq_prop:s0 tclass=file permissive=1
06-21 22:21:14.547  1372  1387 W ActivityManager: Process ProcessRecord{b1d0431 2911:com.android.nfc/1027} failed to attach
06-21 22:21:14.547  1372  1387 I ActivityManager: Killing 2911:com.android.nfc/1027 (adj -10000): start timeout
06-21 22:21:14.548  1372  1387 E ActivityManager: Removing process that hasn't been killed: ProcessRecord{b1d0431 2911:com.android.nfc/1027}
06-21 22:21:14.548  1372  1387 E ActivityManager: android.util.Log$TerribleFailure: Removing process that hasn't been killed: ProcessRecord{b1d0431 2911:com.android.nfc/1027}

```

NFC works in AOSP since v20 (I only tried v20). I've tried to replace the lineage nfc parts by aosp ones (replace `LineageOS/android_packages_apps_Nfc` and `LineageOS/android_system_nfc` to aosp) and still got the same logs. Now I have no idea why it does not work. Would you mind telling me where to start? Thanks very much!

**Comment by phhusson** [comment]
FWIW this is for all devices.

I'd say you could try by checking this com.nxp.nfc.nq thing.
Is this lib in AOSP build?
Check NFC apk Android Manifest, to see if this lib is an added requirement
from Lineage's NFC APK, or if it is already in AOSP's NFC APK


Le jeu. 21 juin 2018 à 16:47, Song Fuchang <notifications@github.com> a
écrit :

**Comment by notsyncing** [comment]
I checked v20 AOSP image and did not find this library com.nxp.nfc.nq.
I've compared the lineage manifest with aosp manifest, and aosp manifest did not have this library too.

**Comment by notsyncing** [comment]
I commented out the line `ifeq ($(strip $(TARGET_USES_NQ_NFC)),true)` in `vendor/nxp/opensource/frameworks/Android.mk` and got the `com.nxp.nfc.nq.jar`. Now the log shows a crash:

```
06-24 18:35:25.965  1380  1404 I ActivityManager: Start proc 2819:com.android.nfc/1027 for added application com.android.nfc
06-24 18:35:25.976  2819  2819 F libc    : Fatal signal 6 (SIGABRT), code -6 in tid 2819 (main), pid 2819 (main)
06-24 18:35:25.977  1380  1404 I ActivityManager: Start proc 2832:org.lineageos.audiofx/u0a10 for added application org.lineageos.audiofx
06-24 18:35:25.996  1380  1404 I ActivityManager: User 0 state changed from RUNNING_UNLOCKING to RUNNING_UNLOCKED
06-24 18:35:25.997  1380  1397 I LockSettingsService: Disabling escrow token on user 0
06-24 18:35:25.997  1380  1404 I PreBootBroadcaster: Pre-boot of {com.android.managedprovisioning/com.android.managedprovisioning.ota.PreBootListener} for user 0
06-24 18:35:26.014  1380  1380 V NotificationListeners: enabling notification listener for 0: ComponentInfo{org.kde.kdeconnect_tp/org.kde.kdeconnect.Plugins.NotificationsPlugin.NotificationReceiver}
06-24 18:35:26.018  2843  2843 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
06-24 18:35:26.018  2843  2843 F DEBUG   : LineageOS Version: '15.1-20180624-UNOFFICIAL-'
06-24 18:35:26.018  2843  2843 F DEBUG   : Build fingerprint: 'Android/treble_arm64_avN/phhgsi_arm64_a:8.1.0/OPM2.171026.006/180624:userdebug/test-keys'
06-24 18:35:26.018  2843  2843 F DEBUG   : Revision: '0'
06-24 18:35:26.018  2843  2843 F DEBUG   : ABI: 'arm64'
06-24 18:35:26.018  2843  2843 F DEBUG   : pid: 2819, tid: 2819, name: main  >>> zygote64 <<<
06-24 18:35:26.018  2843  2843 F DEBUG   : signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
06-24 18:35:26.018  2843  2843 F DEBUG   : Abort message: ''
06-24 18:35:26.018  2843  2843 F DEBUG   :     x0   0000000000000000  x1   0000000000000b03  x2   0000000000000006  x3   0000000000000008
06-24 18:35:26.018  2843  2843 F DEBUG   :     x4   0000000000000000  x5   0000000000000000  x6   0000000000000000  x7   0080808080808080
06-24 18:35:26.018  2843  2843 F DEBUG   :     x8   0000000000000083  x9   95821217cfe747b7  x10  0000000000000000  x11  0000000000000001
06-24 18:35:26.018  2843  2843 F DEBUG   :     x12  ffffffffffffffff  x13  0000000000000008  x14  ffffffffffffffff  x15  0000bb2e4b5422a8
06-24 18:35:26.018  2843  2843 F DEBUG   :     x16  0000005f77398fa8  x17  0000007776df705c  x18  0000000000000008  x19  0000000000000b03
06-24 18:35:26.018  2843  2843 F DEBUG   :     x20  0000000000000b03  x21  0000000000000000  x22  000000777b57ca40  x23  0000007ff93b7439
06-24 18:35:26.018  2843  2843 F DEBUG   :     x24  0000000000000040  x25  0000000000000081  x26  0000000000000079  x27  000000777a3e71a8
06-24 18:35:26.018  2843  2843 F DEBUG   :     x28  000000777a3e6300  x29  0000007ff93b73e0  x30  0000007776daba2c
06-24 18:35:26.018  2843  2843 F DEBUG   :     sp   0000007ff93b73a0  pc   0000007776daba48  pstate 0000000060000000
06-24 18:35:26.019  2843  2843 F DEBUG   : 
06-24 18:35:26.019  2843  2843 F DEBUG   : backtrace:
06-24 18:35:26.019  2843  2843 F DEBUG   :     #00 pc 000000000001da48  /system/lib64/libc.so (abort+104)
06-24 18:35:26.019  2843  2843 F DEBUG   :     #01 pc 000000000001da28  /system/lib64/libc.so (abort+72)

...

06-24 18:35:35.966  1380  1404 W ActivityManager: Process ProcessRecord{7f3a024 2819:com.android.nfc/1027} failed to attach
06-24 18:35:35.966  1380  1404 I ActivityManager: Killing 2819:com.android.nfc/1027 (adj -10000): start timeout
06-24 18:35:35.970  1380  1404 E ActivityManager: Removing process that hasn't been killed: ProcessRecord{7f3a024 2819:com.android.nfc/1027}
06-24 18:35:35.970  1380  1404 E ActivityManager: android.util.Log$TerribleFailure: Removing process that hasn't been killed: ProcessRecord{7f3a024 2819:com.android.nfc/1027}
06-24 18:35:35.970  1380  1404 E ActivityManager:       at android.util.Log.wtf(Log.java:299)
06-24 18:35:35.970  1380  1404 E ActivityManager:       at android.util.Slog.wtfStack(Slog.java:98)
06-24 18:35:35.970  1380  1404 E ActivityManager:       at com.android.server.am.ActivityManagerService.removeLruProcessLocked(ActivityManagerService.java:3428)
06-24 18:35:35.970  1380  1404 E ActivityManager:       at com.android.server.am.ActivityManagerService.processStartTimedOutLocked(ActivityManagerService.java:6956)
06-24 18:35:35.970  1380  1404 E ActivityManager:       at com.android.server.am.ActivityManagerService.-wrap9(Unknown Source:0)
06-24 18:35:35.970  1380  1404 E ActivityManager:       at com.android.server.am.ActivityManagerService$MainHandler.handleMessage(ActivityManagerService.java:2043)
06-24 18:35:35.970  1380  1404 E ActivityManager:       at android.os.Handler.dispatchMessage(Handler.java:106)
06-24 18:35:35.970  1380  1404 E ActivityManager:       at android.os.Looper.loop(Looper.java:164)
06-24 18:35:35.970  1380  1404 E ActivityManager:       at android.os.HandlerThread.run(HandlerThread.java:65)
06-24 18:35:35.970  1380  1404 E ActivityManager:       at com.android.server.ServiceThread.run(ServiceThread.java:46)
```

**Comment by notsyncing** [comment]
I copied the following files:

```
/system/app/NfcNci/*
/system/lib64/libnfc_nci_jni.so
/system/lib64/libnfc-nci.so
```

from v20 AOSP rom to LineageOS, and NFC worked!

Seems lineage does not build these files, they did not exist in lineage rom.

**Comment by notsyncing** [comment]
Funny, although mix2s has nfc app in `/vendor`, but it depends on the `com.nxp.nfc.nq` in stock `/system`! The aosp `NfcNci` app will take over it:

```
03-18 18:39:52.929  1383  1383 I PackageManager: /system/app/NfcNci changed; collecting certs
03-18 18:39:53.083  1383  1383 I PackageManager: /vendor/app/NQNfcNci changed; collecting certs
03-18 18:39:53.085  1383  1383 W PackageManager: Failed to scan /vendor/app/NQNfcNci: Application package com.android.nfc already installed.  Skipping duplicate.
06-24 21:08:34.468  1383  1398 I ActivityManager: Start proc 2786:com.android.nfc/1027 for added application com.android.nfc
``` 

thus NFC worked. LineageOS did not build `NfcNci` app and die on the non-exist `com.nxp.nfc.nq` library.

I've added the following line in `device/phh/treble/base.mk`:

```
PRODUCT_PACKAGES += \
        NfcNci  
```

Is this an appropriate fix? If it was, I could make a PR for it. Thanks very much.

**Comment by phhusson** [comment]
Thanks for that debugging
Sounds like an appropriate fix indeed.
The two .so libs are built part of NfcNci app? (I guess yes)

Le dim. 24 juin 2018 à 15:31, Song Fuchang <notifications@github.com> a
écrit :

**Comment by notsyncing** [comment]
Yes, they are.

**Comment by notsyncing** [comment]
Verified with Lineage v21 release. NFC is working. Thanks!
