### ISSUE TITLE
[Global] [AOSP 10.0] Alarm doesn't sound always

### ISSUE THREAD

**Issue by arwarw** [phhusson/treble_experimentations#936]
Running AOSP10 release v204, vanilla.

Maybe related to #189, but my alarm doesn't go off ever, and the clock application crashes when it should go off. Seems to be a permission problem according to the logcat:

```
11-20 01:03:39.373  7342  7342 D Events  : [Timer] [Start] [DeskClock]
11-20 01:03:40.412  6809  6809 I EventStreamServiceX: %%%%%%%%  MXEventListener: onLiveEventsChunkProcessed[s1161779162_757268999_494191_384121772_232194941_987039_35714262_18779464_63504->s1161781253_757268999_495536_384122682_232195654_987039_35714445_18779519_63504]
11-20 01:03:40.414  6809  6809 I EventStreamServiceX: onLiveEventsChunkProcessed : no Active call
11-20 01:03:40.415  6809  6809 I EventStreamServiceX: ## stop(): the service is stopped
11-20 01:03:40.523  6809  6809 I VectorService: ## onDestroy() : im.vector.services.EventStreamServiceX@c2d33
11-20 01:03:40.525  6809  6809 I EventStreamServiceX: ## getBackgroundBehavior: Using Work Manager
11-20 01:03:40.525  6809  6809 I EventStreamServiceX: ## service is schedule to restart in 60000 millis, if network is connected
11-20 01:03:40.582  3202  4904 D PackageManager: Instant App installer not found with android.intent.action.INSTALL_INSTANT_APP_PACKAGE
11-20 01:03:40.582  3202  4904 D PackageManager: Clear ephemeral installer activity
11-20 01:03:41.607  4005  4005 V AvrcpMediaPlayerList: mPackageChangedBroadcastReceiver: action: android.intent.action.PACKAGE_CHANGED
11-20 01:03:41.607  4005  4005 D AvrcpMediaPlayerList: Name of package changed: im.vector.alpha
11-20 01:03:41.624  3202  3716 I InputReader: Reconfiguring input devices.  changes=0x00000010
11-20 01:03:41.630  3202  3202 I RoleManagerService: Granting default permissions...
11-20 01:03:41.676  4351  4351 E PhoneInterfaceManager: [PhoneIntfMgr] getCarrierPackageNamesForIntent: No UICC
11-20 01:03:41.676  4351  4351 D CarrierSvcBindHelper: No carrier app for: 0
11-20 01:03:41.684  4351  4351 D CarrierSvcBindHelper: No carrier app for: 1
11-20 01:03:41.758  3202  3202 W Looper  : Slow dispatch took 124ms main h=android.app.ActivityThread$H c=android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA@f878244 m=0
11-20 01:03:41.788  3202  3202 I Telecom : DefaultDialerCache: Refreshing default dialer for user 0: now com.android.dialer: DDC.oR@AI8
11-20 01:03:41.832  3202  3275 W VoiceInteractionManagerService: no available voice interaction services found for user 0
11-20 01:03:42.224  3202  3275 I RoleUserState: Wrote roles.xml successfully
11-20 01:03:46.690   573   573 E SELinux : avc:  denied  { find } for interface=vendor.samsung.hardware.light::ISecLight sid=u:r:system_server:s0 pid=3202 scontext=u:r:system_server:s0 tcontext=u:object_r:default_android_hwservice:s0 tclass=hwservice_manager permissive=0
11-20 01:03:46.694  3202  3283 E LightsService: Light requested not available on this device. 2
11-20 01:03:49.391  7342  7342 D Events  : [Timer] [Fire] [Intent]
11-20 01:03:49.397  7342  7342 I AlarmClock: TimerKlaxon.start()
11-20 01:03:49.398  7342  7342 D AsyncRingtonePlayer: Posting play.
11-20 01:03:49.402  7342  7710 I AsyncRingtonePlayer: Play ringtone via android.media.Ringtone.
11-20 01:03:49.422  3202  5872 W ActivityManager: Permission Denial: startForeground from pid=7342, uid=10068 requires android.permission.FOREGROUND_SERVICE
11-20 01:03:49.423  7342  7342 D AndroidRuntime: Shutting down VM
11-20 01:03:49.424  7342  7342 E AndroidRuntime: FATAL EXCEPTION: main
11-20 01:03:49.424  7342  7342 E AndroidRuntime: Process: com.android.deskclock, PID: 7342
11-20 01:03:49.424  7342  7342 E AndroidRuntime: java.lang.RuntimeException: Unable to start service com.android.deskclock.timer.TimerService@e98b693 with Intent { act=com.android.deskclock.action.TIMER_EXPIRED flg=0x4 cmp=com.android.deskclock/.timer.TimerService (has extras) }: java.lang.SecurityException: Permission Denial: startForeground from pid=7342, uid=10068 requires android.permission.FOREGROUND_SERVICE
11-20 01:03:49.424  7342  7342 E AndroidRuntime:        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4105)
11-20 01:03:49.424  7342  7342 E AndroidRuntime:        at android.app.ActivityThread.access$1800(ActivityThread.java:219)
11-20 01:03:49.424  7342  7342 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1891)
11-20 01:03:49.424  7342  7342 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:107)
11-20 01:03:49.424  7342  7342 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:214)
11-20 01:03:49.424  7342  7342 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7356)
11-20 01:03:49.424  7342  7342 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
11-20 01:03:49.424  7342  7342 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
11-20 01:03:49.424  7342  7342 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
11-20 01:03:49.424  7342  7342 E AndroidRuntime: Caused by: java.lang.SecurityException: Permission Denial: startForeground from pid=7342, uid=10068 requires android.permission.FOREGROUND_SERVICE
11-20 01:03:49.424  7342  7342 E AndroidRuntime:        at android.os.Parcel.createException(Parcel.java:2071)
11-20 01:03:49.424  7342  7342 E AndroidRuntime:        at android.os.Parcel.readException(Parcel.java:2039)
11-20 01:03:49.424  7342  7342 E AndroidRuntime:        at android.os.Parcel.readException(Parcel.java:1987)
11-20 01:03:49.424  7342  7342 E AndroidRuntime:        at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:6136)
11-20 01:03:49.424  7342  7342 E AndroidRuntime:        at android.app.Service.startForeground(Service.java:707)
11-20 01:03:49.424  7342  7342 E AndroidRuntime:        at com.android.deskclock.data.TimerModel.updateHeadsUpNotification(TimerModel.java:805)
11-20 01:03:49.424  7342  7342 E AndroidRuntime:        at com.android.deskclock.data.TimerModel.updateTimer(TimerModel.java:267)
11-20 01:03:49.424  7342  7342 E AndroidRuntime:        at com.android.deskclock.data.TimerModel.expireTimer(TimerModel.java:252)
11-20 01:03:49.424  7342  7342 E AndroidRuntime:        at com.android.deskclock.data.DataModel.expireTimer(DataModel.java:518)
11-20 01:03:49.424  7342  7342 E AndroidRuntime:        at com.android.deskclock.timer.TimerService.onStartCommand(TimerService.java:177)
11-20 01:03:49.424  7342  7342 E AndroidRuntime:        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4087)
11-20 01:03:49.424  7342  7342 E AndroidRuntime:        ... 8 more
11-20 01:03:49.424  7342  7342 E AndroidRuntime: Caused by: android.os.RemoteException: Remote stack trace:
11-20 01:03:49.424  7342  7342 E AndroidRuntime:        at com.android.server.am.ActivityManagerService.enforcePermission(ActivityManagerService.java:5928)
11-20 01:03:49.424  7342  7342 E AndroidRuntime:        at com.android.server.am.ActiveServices.setServiceForegroundInnerLocked(ActiveServices.java:1259)
11-20 01:03:49.424  7342  7342 E AndroidRuntime:        at com.android.server.am.ActiveServices.setServiceForegroundLocked(ActiveServices.java:914)
11-20 01:03:49.424  7342  7342 E AndroidRuntime:        at com.android.server.am.ActivityManagerService.setServiceForeground(ActivityManagerService.java:13942)
11-20 01:03:49.424  7342  7342 E AndroidRuntime:        at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2784)
11-20 01:03:49.424  7342  7342 E AndroidRuntime: 
11-20 01:03:49.429  3202  4319 W ActivityTaskManager:   Force finishing activity com.android.deskclock/.DeskClock
11-20 01:03:49.431  3202  7711 I DropBoxManagerService: add tag=system_app_crash isTagEnabled=true flags=0x2
11-20 01:03:49.459  3202  3268 I ActivityManager: Showing crash dialog for package com.android.deskclock u0
11-20 01:03:49.459  3202  3268 E system_server: Invalid ID 0x00000000.

```

**Comment by misspaulo** [comment]
AOSP10 v204 arm64-ab-vanilla, Umidigi A5 Pro, default alarm has same issue. Alarm/timers doesn't go off , and the clock app crashes. Other alarm apps work fine.

**Comment by phhusson** [comment]
Looks like master branch of DeskClock is fixed.
I integrated it into my release ( https://github.com/phhusson/treble_manifest/commit/430eda0ebdaea7770d98fc8169f95a92e18e20c6 and https://github.com/phhusson/platform_packages_apps_DeskClock/commit/8256fa44f303af89c7692c87e87d66c1d21ba5bc )

Please tell me the result on next release v206.
