### ISSUE TITLE
[AOSP] [204] [DEEN] Google Wellbeing crashing

### ISSUE THREAD

**Issue by lucasdeeiroz** [phhusson/treble_experimentations#952]
Wellbeing crashing after some time in v204. Logcat says:
`E AndroidRuntime: FATAL EXCEPTION: main
E AndroidRuntime: Process: com.google.android.apps.wellbeing, PID: 4849
E AndroidRuntime: kqq: 
E AndroidRuntime: 	at tk_trace.DeviceUsageDataSource.fetchAndStoreData()(Unknown Source:0)
E AndroidRuntime: 	at tk_trace.DataSource fetchAndStoreData()(Unknown Source:0)
E AndroidRuntime: 	at tk_trace.onAccountReady(Unknown Source:0)
E AndroidRuntime: 	at tk_trace.onPostCreate SettingsActivity(Unknown Source:0)
E AndroidRuntime: 	at tk_trace.Intenting into SettingsActivity(Unknown Source:0)
**E AndroidRuntime: Caused by: java.lang.SecurityException: getUnsuspendablePackagesForUser: Neither user 10060 nor current process has android.permission.SUSPEND_APPS.**
E AndroidRuntime: 	at android.os.Parcel.createException(Parcel.java:2071)
E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:2039)
E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:1987)
E AndroidRuntime: 	at android.content.pm.IPackageManager$Stub$Proxy.getUnsuspendablePackagesForUser(IPackageManager.java:7072)
E AndroidRuntime: 	at android.app.ApplicationPackageManager.getUnsuspendablePackages(ApplicationPackageManager.java:2368)
E AndroidRuntime: 	at bwo.get(PG:1)
E AndroidRuntime: 	at dou.get(PG:11)
E AndroidRuntime: 	at bwm.a(PG:2)
E AndroidRuntime: 	at kqd.a(PG:3)
E AndroidRuntime: 	at lgf.a(PG:3)
E AndroidRuntime: 	at lgg.run(PG:27)
E AndroidRuntime: 	at lix.run(PG:3)
E AndroidRuntime: 	at jnr.run(PG:3)
E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E AndroidRuntime: 	at jlt.run(PG:4)
E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:919)
E AndroidRuntime: Caused by: android.os.RemoteException: Remote stack trace:
E AndroidRuntime: 	at android.app.ContextImpl.enforce(ContextImpl.java:1896)
E AndroidRuntime: 	at android.app.ContextImpl.enforceCallingOrSelfPermission(ContextImpl.java:1924)
E AndroidRuntime: 	at com.android.server.pm.PackageManagerService.getUnsuspendablePackagesForUser(PackageManagerService.java:13911)
E AndroidRuntime: 	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:3326)
E AndroidRuntime: 	at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:4021)`
How could I set SUSPEND_APPS permission?

**Comment by kukuruyukpagi** [comment]
facing same issue on my Lenovo S5, temporary fix was by clear data and cache from application but some other time it happened again..

**Comment by alexa-v2** [comment]
Not phh issue
Missing a xml in /system/etc/permissions. Whatever mod you used to get wellbeing should have came with it

Recommend closing

**Comment by lucasdeeiroz** [comment]
> Not phh issue
> Missing a xml in /system/etc/permissions. Whatever mod you used to get wellbeing should have came with it
> 
> Recommend closing

AOSP Gapps comes with Wellbeing built-in.
