### ISSUE TITLE
[AOSP 10 v205+]  Handwave gesture and wake screen on new notifications showing lock icon

### ISSUE THREAD

**Issue by kjp4756** [phhusson/treble_experimentations#996]
Phone: Moto Z (2016)
A-Only arm64
w/ gapps

In PHH settings I have handwave gesture enabled and I also have the wake screen on new notifications enabled.  When I get a new notification or I wake the screen with a handwave, I get an ambient display version of a lock symbol (greyish lock on top of screen) and the notification does not show.

I've captured a logcat and it looks like something is crashing.  This started happening with v205 and the issue persists in v206. 

```
[ 12-09 18:32:30.654   787:  867 I/MotoSensors ]
Proximity covered

[ 12-09 18:32:30.668 17319:17319 D/PHH      ]
Pocket got updated proximity to 3.0

[ 12-09 18:32:30.717   787:  867 I/MotoSensors ]
Proximity uncovered

[ 12-09 18:32:30.723 17319:17319 D/PHH      ]
Pocket got updated proximity to 100.0

[ 12-09 18:32:30.723 17319:17319 D/PHH      ]
Got handwave event

[ 12-09 18:32:30.734   787: 1606 D/MotoSensors ]
batch:255 +

[ 12-09 18:32:30.735   787: 1606 I/MotoSensors ]
Sensorhub hal batch: sensor="BMI160 3-axis Accelerometer" handle=0 period=5000000ns timeout=0ns

[ 12-09 18:32:30.737   787: 1606 D/MotoSensors ]
activate:236 +

[ 12-09 18:32:30.738   787: 1606 D/MotoSensors ]
activate:96 +

[ 12-09 18:32:30.738   787: 1606 I/MotoSensors ]
Sensorhub hal setEnable: sensor="BMI160 3-axis Accelerometer" handle=0 enable=1

[ 12-09 18:32:30.752 17319:17348 D/PHH      ]
Got 10.0029745 true

[ 12-09 18:32:30.753   787: 1606 D/MotoSensors ]
activate:236 +

[ 12-09 18:32:30.753   787: 1606 D/MotoSensors ]
activate:96 +

[ 12-09 18:32:30.753   787: 1606 I/MotoSensors ]
Sensorhub hal setEnable: sensor="BMI160 3-axis Accelerometer" handle=0 enable=0

[ 12-09 18:32:30.759  1263: 6582 E/ActivityManager ]
Sending non-protected broadcast com.android.systemui.doze.pulse from system 17319:me.phh.treble.app/1000 pkg me.phh.treble.app
java.lang.Throwable
        at com.android.server.am.ActivityManagerService.checkBroadcastFromSystem(ActivityManagerService.java:14779)
        at com.android.server.am.ActivityManagerService.broadcastIntentLocked(ActivityManagerService.java:15331)
        at com.android.server.am.ActivityManagerService.broadcastIntentLocked(ActivityManagerService.java:14796)
        at com.android.server.am.ActivityManagerService.broadcastIntent(ActivityManagerService.java:15567)
        at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:1950)
        at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2741)
        at android.os.Binder.execTransactInternal(Binder.java:1021)
        at android.os.Binder.execTransact(Binder.java:994)


[ 12-09 18:32:30.780  1263: 6582 I/DropBoxManagerService ]
add tag=system_server_wtf isTagEnabled=true flags=0x2

[ 12-09 18:32:30.792  1263: 6582 E/ActivityManager ]
Sending non-protected broadcast com.android.systemui.doze.pulse from system 17319:me.phh.treble.app/1000 pkg me.phh.treble.app
java.lang.Throwable
        at com.android.server.am.ActivityManagerService.checkBroadcastFromSystem(ActivityManagerService.java:14779)
        at com.android.server.am.ActivityManagerService.broadcastIntentLocked(ActivityManagerService.java:15425)
        at com.android.server.am.ActivityManagerService.broadcastIntentLocked(ActivityManagerService.java:14796)
        at com.android.server.am.ActivityManagerService.broadcastIntent(ActivityManagerService.java:15567)
        at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:1950)
        at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2741)
        at android.os.Binder.execTransactInternal(Binder.java:1021)
        at android.os.Binder.execTransact(Binder.java:994)


[ 12-09 18:32:30.815   787:  787 D/MotoSensors ]
batch:255 +
```
![IMG_6891](https://user-images.githubusercontent.com/2547166/70485927-e5801280-1ab5-11ea-95d9-df835be7eba3.jpg)

**Comment by phhusson** [comment]
Yup looks like a global issue, I reproduce it here as well.

**Comment by kjp4756** [comment]
Starting with v210 ambient display doesn't turn on at all now.  The lock icon isn't even shown like the picture in the OP shows.  Always on display does work.

I am on v212 now.  When ambient display is triggered to turn on via new notifications or by manually invoking intent "com.android.systemui.doze.pulse" this fatal exception occurs.  I'm not sure if this lineageactions stuff is part of my unofficial treble or if its part of the GSI.

`[ 02-23 14:45:11.812 13350:13350 E/AndroidRuntime ]
FATAL EXCEPTION: main
Process: org.lineageos.settings.device, PID: 13350
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/android/internal/hardware/AmbientDisplayConfiguration;
        at org.lineageos.settings.device.LineageActionsSettings.isDozeEnabled(LineageActionsSettings.java:75)
        at org.lineageos.settings.device.LineageActionsSettings.isDozeEnabled(LineageActionsSettings.java:83)
        at org.lineageos.settings.device.LineageActionsSettings.isIrWakeupEnabled(LineageActionsSettings.java:87)
        at org.lineageos.settings.device.doze.GlanceSensor.screenTurnedOff(GlanceSensor.java:58)
        at org.lineageos.settings.device.LineageActionsService.screenTurnedOff(LineageActionsService.java:110)
        at org.lineageos.settings.device.LineageActionsService.updateState(LineageActionsService.java:118)
        at org.lineageos.settings.device.LineageActionsService.<init>(LineageActionsService.java:87)
        at org.lineageos.settings.device.ServiceWrapper.onCreate(ServiceWrapper.java:48)
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:3953)
        at android.app.ActivityThread.access$1500(ActivityThread.java:219)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1875)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
Caused by: java.lang.ClassNotFoundException: com.android.internal.hardware.AmbientDisplayConfiguration
        ... 17 more`

**Comment by phhusson** [comment]
My GSI doesn't have any reference to lineage.
I have a device on v212 with working ambient display.
However on that device I couldn't get handwave to work, so I'll debug that.

**Comment by kjp4756** [comment]
Just flashed v214 and ambient display and handwave gesture are working again.  I don't know what you did but thanks!  I can close this issue now.
